import {describe,expect,it} from 'vitest';
import {HttpRouter} from '../src/http/runtime.js';
import type {HttpProgram} from '../src/http/ir.js';
import {primitive} from '../src/types/type-ref.js';

const program:HttpProgram={routes:[{id:'get-user',method:'GET',path:'/users/:id',pathParams:[{name:'id',type:primitive('text'),required:true}],query:[],headers:[],status:200,handlerId:'users.get'}]};
describe('HTTP runtime',()=>{
 it('dispatches typed route handlers with decoded params',async()=>{const seen:string[]=[];const router=new HttpRouter(program).register('users.get',(_req,p)=>{seen.push(p.id);return {status:200,headers:{},body:{id:p.id}}});await expect(router.dispatch({method:'GET',url:'/users/a%20b'})).resolves.toMatchObject({status:200,body:{id:'a b'}});expect(seen).toEqual(['a b']);});
 it('returns 404 and 405 without dynamic method lookup',async()=>{const router=new HttpRouter(program).register('users.get',()=>({status:200,headers:{}}));await expect(router.dispatch({method:'GET',url:'/missing'})).resolves.toMatchObject({status:404});await expect(router.dispatch({method:'POST',url:'/users/x'})).resolves.toMatchObject({status:405});});
 it('maps handler failures to structured 500',async()=>{const router=new HttpRouter(program).register('users.get',()=>{throw new Error('boom')});await expect(router.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:500,body:{error:'internal_error'}});});
 it('runs middleware in registration order around the static handler',async()=>{const events:string[]=[];const router=new HttpRouter(program).use(async(_req,next)=>{events.push('before-a');const r=await next();events.push('after-a');return r;}).use(async(_req,next)=>{events.push('before-b');const r=await next();events.push('after-b');return r;}).register('users.get',()=>{events.push('handler');return {status:200,headers:{}}});await router.dispatch({method:'GET',url:'/users/x'});expect(events).toEqual(['before-a','before-b','handler','after-b','after-a']);});
 it('enforces declared route capabilities',async()=>{const secured={routes:[{...program.routes[0],capabilities:['database' as const]}]};const missing=new HttpRouter(secured).register('users.get',()=>({status:200,headers:{}}));await expect(missing.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:500,body:{error:'missing_capability'}});const supplied=new HttpRouter(secured,new Set(['database'])).register('users.get',()=>({status:200,headers:{}}));await expect(supplied.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:200});});
 it('enforces route authorization before invoking handlers',async()=>{let called=false;const secured={routes:[{...program.routes[0],policyId:'admin'}]};const router=new HttpRouter(secured).registerPolicy('admin',()=>false).register('users.get',()=>{called=true;return {status:200,headers:{}}});await expect(router.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:403,body:{error:'forbidden'}});expect(called).toBe(false);});
 it('validates and forwards declared query parameters',async()=>{const queried={routes:[{...program.routes[0],query:[{name:'limit',type:{kind:'primitive',name:'integer'} as const,required:true}]}]};let received:Record<string,string>|undefined;const router=new HttpRouter(queried).register('users.get',(_r,p)=>{received=p;return {status:200,headers:{}}});await expect(router.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:400,body:{error:'missing_query_param'}});await router.dispatch({method:'GET',url:'/users/x?limit=10'});expect(received?.limit).toBe('10');});
 it('rejects invalid primitive query values',async()=>{const queried={routes:[{...program.routes[0],query:[{name:'limit',type:{kind:'primitive',name:'integer'} as const,required:true}]}]};const router=new HttpRouter(queried).register('users.get',()=>({status:200,headers:{}}));await expect(router.dispatch({method:'GET',url:'/users/x?limit=nope'})).resolves.toMatchObject({status:400,body:{error:'invalid_query_param'}});});
 it('validates headers case-insensitively and forwards them',async()=>{const secured={routes:[{...program.routes[0],headers:[{name:'Authorization',type:{kind:'primitive',name:'text'} as const,required:true}]}]};let received:Record<string,string>|undefined;const router=new HttpRouter(secured).register('users.get',(_r,p)=>{received=p;return {status:200,headers:{}}});await expect(router.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:400,body:{error:'missing_header'}});await router.dispatch({method:'GET',url:'/users/x',headers:{authorization:'Bearer x'}});expect(received?.['header:Authorization']).toBe('Bearer x');});
 it('requires bodies for routes with a request contract',async()=>{const bodyRoute={routes:[{...program.routes[0],requestBody:{kind:'primitive',name:'text'} as const}]};const router=new HttpRouter(bodyRoute).register('users.get',()=>({status:200,headers:{}}));await expect(router.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:400,body:{error:'missing_body'}});});
 it('enforces declared response status and body contracts',async()=>{const bodyRoute={routes:[{...program.routes[0],responseBody:{kind:'primitive',name:'text'} as const}]};const wrong=new HttpRouter(bodyRoute).register('users.get',()=>({status:201,headers:{},body:'ok'}));await expect(wrong.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:500,body:{error:'contract_status_mismatch'}});const missing=new HttpRouter(bodyRoute).register('users.get',()=>({status:200,headers:{}}));await expect(missing.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:500,body:{error:'missing_response_body'}});});
 it('rejects mismatched tagged semantic response bodies',async()=>{const bodyRoute={routes:[{...program.routes[0],responseBody:{kind:'primitive',name:'integer'} as const}]};const router=new HttpRouter(bodyRoute).register('users.get',()=>({status:200,headers:{},body:{kind:'text',value:'wrong'}}));await expect(router.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:500,body:{error:'invalid_response_body'}});});
 it('serializes valid tagged responses losslessly',async()=>{const bodyRoute={routes:[{...program.routes[0],responseBody:{kind:'primitive',name:'integer'} as const}]};const router=new HttpRouter(bodyRoute).register('users.get',()=>({status:200,headers:{},body:{kind:'integer',value:7n}}));await expect(router.dispatch({method:'GET',url:'/users/x'})).resolves.toMatchObject({status:200,body:{version:1,kind:'integer',value:'7'}});});
 it('decodes declared JSON request bodies before handlers',async()=>{const bodyRoute={routes:[{...program.routes[0],requestBody:{kind:'primitive',name:'integer'} as const}]};let body:unknown;const router=new HttpRouter(bodyRoute).register('users.get',req=>{body=req.body;return {status:200,headers:{}}});await expect(router.dispatch({method:'GET',url:'/users/x',body:'{"version":1,"kind":"integer","value":"7"'})).resolves.toMatchObject({status:400,body:{error:'invalid_body'}});const valid=JSON.stringify({version:1,kind:'integer',value:'7'});await router.dispatch({method:'GET',url:'/users/x',body:valid});expect((body as any).kind).toBe('integer');});
 it('rejects non-JSON content types for typed JSON bodies',async()=>{const bodyRoute={routes:[{...program.routes[0],requestBody:{kind:'primitive',name:'integer'} as const}]};const router=new HttpRouter(bodyRoute).register('users.get',()=>({status:200,headers:{}}));await expect(router.dispatch({method:'GET',url:'/users/x',headers:{'content-type':'text/plain'},body:'x'})).resolves.toMatchObject({status:415,body:{error:'unsupported_media_type'}});});
});
