import Database from 'better-sqlite3';
import {mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
import type {ProjectIR,IRTypeField} from '../ir/ir.js';
import {migrate,MigrationError} from './migration.js';

export class RuntimeError extends Error { constructor(public code:string,public kind:string,message:string,public details:Record<string,unknown>={}){super(message);this.name='RuntimeError'} }
export class RuntimeValidationError extends RuntimeError { constructor(message:string,d:Record<string,unknown>={}){super('PIPE-VAL-001','invalid_value',message,d)} }
export class RuntimeMediaTypeError extends RuntimeError { constructor(){super('PIPE-NET-003','unsupported_media_type','Content-Type must be application/json')} }

const q=(s:string)=>`"${s.replace(/"/g,'""')}"`;
const base=(t:string)=>t.endsWith('?')?t.slice(0,-1):t;
const fieldKind=(f:IRTypeField)=>f.typeRef?.kind==='primitive'?f.typeRef.name:base(f.type);
const int64=(value:unknown):bigint|undefined=>{if(typeof value==='bigint')return value;if(typeof value==='number'&&Number.isSafeInteger(value))return BigInt(value);if(typeof value==='string'&&/^-?(0|[1-9]\d*)$/.test(value))return BigInt(value);return undefined};
const moneyMinor=(value:unknown):bigint|undefined=>{if(value&&typeof value==='object'&&!Array.isArray(value)){const v=value as any;if(v.scale===2&&typeof v.minor==='string'&&/^-?(0|[1-9]\d*)$/.test(v.minor))return BigInt(v.minor)}if(typeof value==='string'&&/^-?(?:\d+)(?:\.\d{1,2})?$/.test(value)){const neg=value.startsWith('-'),clean=neg?value.slice(1):value,[whole,fraction='']=clean.split('.'),minor=BigInt(whole)*100n+BigInt((fraction+'00').slice(0,2));return neg?-minor:minor}if(typeof value==='number'&&Number.isFinite(value)){const minor=Math.round(value*100);return Number.isSafeInteger(minor)?BigInt(minor):undefined}return undefined};
const validDate=(value:string)=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!m)return false;const d=new Date(Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3])));return d.getUTCFullYear()===Number(m[1])&&d.getUTCMonth()===Number(m[2])-1&&d.getUTCDate()===Number(m[3]);};
const validDateTime=(value:string)=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(value)&&Number.isFinite(Date.parse(value))&&validDate(value.slice(0,10));

export class PipeDatabase {
 private db:Database.Database;
 constructor(private readonly ir:ProjectIR,file:string){mkdirSync(dirname(file),{recursive:true});this.db=new Database(file);this.db.pragma('journal_mode = WAL');try{migrate(this.db,ir)}catch(e){this.db.close();throw e}}
 private model(n:string){const m=this.ir.models.find(x=>x.name===n);if(!m)throw new RuntimeError('PIPE-DB-001','unknown_model',`Unknown model "${n}"`,{model:n});return m}
 private validate(m:ProjectIR['models'][number],input:Record<string,unknown>,partial=false){if(!input||typeof input!=='object'||Array.isArray(input))throw new RuntimeValidationError('Request body must be a JSON object');const v:Record<string,unknown>={},names=new Set(m.fields.map(f=>f.name));for(const k of Object.keys(input))if(!names.has(k))throw new RuntimeValidationError(`Unknown field "${k}"`,{model:m.name,field:k});for(const f of m.fields){if(!(f.name in input)){if(!partial&&f.required&&f.default===undefined)throw new RuntimeError('PIPE-VAL-002','required_value_missing',`${m.name}.${f.name} is required`,{model:m.name,field:f.name,operation:partial?'update':'create'});continue}const x=input[f.name];if(x===null||x===undefined||x===''){if(f.required)throw new RuntimeError('PIPE-VAL-002','required_value_missing',`${m.name}.${f.name} is required`,{model:m.name,field:f.name});v[f.name]=null;continue}const type=fieldKind(f),ref=this.ir.models.find(r=>r.name===type);if(ref){const id=int64(x);if(id===undefined||id<0n||id>BigInt(Number.MAX_SAFE_INTEGER))throw new RuntimeValidationError(`${f.name} must be a non-negative integer reference`);if(!this.db.prepare(`SELECT 1 FROM ${q(`pipe_${ref.name}`)} WHERE id=?`).get(Number(id)))throw new RuntimeError('PIPE-DB-002','referenced_record_missing',`${m.name}.${f.name} references missing ${ref.name} ${id}`,{model:m.name,field:f.name,reference:ref.name,id:Number(id)});v[f.name]=Number(id);continue}if(type==='boolean'){if(typeof x!=='boolean')throw new RuntimeValidationError(`Invalid value for ${m.name}.${f.name}`);v[f.name]=x?1:0}else if(type==='number'){if(typeof x!=='number'||!Number.isFinite(x))throw new RuntimeValidationError(`Invalid value for ${m.name}.${f.name}`);v[f.name]=x}else if(type==='money'){const minor=moneyMinor(x);if(minor===undefined||minor<-(2n**63n)||minor>2n**63n-1n)throw new RuntimeValidationError(`Invalid exact money value for ${m.name}.${f.name}`);v[f.name]=minor}else if(type==='integer'){const n=int64(x);if(n===undefined||n<-(2n**63n)||n>2n**63n-1n)throw new RuntimeValidationError(`Invalid signed int64 value for ${m.name}.${f.name}`);v[f.name]=n}else if(type==='id'){const n=int64(x);if(n===undefined||n<0n||n>BigInt(Number.MAX_SAFE_INTEGER))throw new RuntimeValidationError(`Invalid id value for ${m.name}.${f.name}`);v[f.name]=Number(n)}else{if(typeof x!=='string')throw new RuntimeValidationError(`Invalid value for ${m.name}.${f.name}`);if(type==='date'&&!validDate(x)||type==='datetime'&&!validDateTime(x)||type==='id'&&!/^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/.test(x))throw new RuntimeValidationError(`Invalid ${type} value for ${m.name}.${f.name}`);v[f.name]=x}}return v}
 private row(m:ProjectIR['models'][number],row:Record<string,unknown>|undefined){if(!row)return null;const out={...row};for(const f of m.fields){const type=fieldKind(f),value=out[f.name];if(value===null||value===undefined)continue;if(typeof value==='bigint'){if(this.ir.models.some(x=>x.name===type))out[f.name]=Number(value);else if(type==='id')out[f.name]=Number(value);else if(type==='integer')out[f.name]=value>=BigInt(Number.MIN_SAFE_INTEGER)&&value<=BigInt(Number.MAX_SAFE_INTEGER)?Number(value):value.toString();else if(type==='money')out[f.name]={minor:value.toString(),scale:2};else if(type==='boolean')out[f.name]=value?1:0}}if(typeof out.id==='bigint')out.id=Number(out.id);return out}
 list(n:string){const m=this.model(n);return (this.db.prepare(`SELECT * FROM ${q(`pipe_${m.name}`)} ORDER BY id`).safeIntegers().all() as Record<string,unknown>[]).map(x=>this.row(m,x))}
 get(n:string,id:number){const m=this.model(n);return this.row(m,this.db.prepare(`SELECT * FROM ${q(`pipe_${m.name}`)} WHERE id=?`).safeIntegers().get(id) as Record<string,unknown>|undefined)}
 create(n:string,input:Record<string,unknown>){const m=this.model(n),v=this.validate(m,input),keys=Object.keys(v),t=q(`pipe_${m.name}`),r=keys.length?this.db.prepare(`INSERT INTO ${t} (${keys.map(q).join(',')}) VALUES (${keys.map(()=>'?').join(',')})`).run(...keys.map(k=>v[k])):this.db.prepare(`INSERT INTO ${t} DEFAULT VALUES`).run();return this.get(n,Number(r.lastInsertRowid))}
 update(n:string,id:number,input:Record<string,unknown>){const m=this.model(n),v=this.validate(m,input,true),keys=Object.keys(v),t=q(`pipe_${m.name}`);if(!keys.length)throw new RuntimeValidationError('No fields to update');const r=this.db.prepare(`UPDATE ${t} SET ${keys.map(k=>`${q(k)}=?`).join(',')} WHERE id=?`).run(...keys.map(k=>v[k]),id);if(!r.changes)throw new RuntimeError('PIPE-DB-003','record_not_found',`Record ${id} not found`,{model:n,id});return this.get(n,id)}
 delete(n:string,id:number){const m=this.model(n),r=this.db.prepare(`DELETE FROM ${q(`pipe_${m.name}`)} WHERE id=?`).run(id);if(!r.changes)throw new RuntimeError('PIPE-DB-003','record_not_found',`Record ${id} not found`,{model:n,id})}
 transaction<T>(work:(database:this)=>T):T {if(typeof work!=='function')throw new RuntimeError('PIPE-DB-005','invalid_transaction','Transaction callback is required');return this.db.transaction(()=>work(this))()}
 close(){if(this.db.open)this.db.close()}
}
export {MigrationError};
