import {createHash} from 'node:crypto';
import {validateDbSchema,type DbField,type DbIndex,type DbModel,type DbSchema} from '../db/ir.js';
import type {TypeRef} from '../types/type-ref.js';

interface PgResult {rows:Record<string,unknown>[];rowCount?:number|null}
interface PgClient {query(text:string,values?:unknown[]):Promise<PgResult>;release():void}
interface PgPool {connect():Promise<PgClient>}

const q=(value:string)=>`"${value.replace(/"/g,'""')}"`;
const stableName=(prefix:string,value:string)=>`${prefix}_${createHash('sha256').update(value).digest('hex').slice(0,20)}`;
function normalizePostgresType(value:string):string {
 const normalized=value.toLowerCase().replace(/character varying|character/g,'text');
 return normalized==='timestamp with time zone'?'timestamptz':normalized;
}
function sqlType(type:TypeRef):string {
 const value=type.kind==='optional'?type.inner:type;
 if(value.kind==='primitive')return value.name==='number'?'double precision':value.name==='boolean'?'boolean':value.name==='integer'||value.name==='id'||value.name==='money'?'bigint':value.name==='date'?'date':value.name==='datetime'?'timestamptz':'text';
 if(value.kind==='model')return 'bigint';
 if(value.kind==='enum')return 'text';
 throw new Error(`PIPE-MIG-001: PostgreSQL does not support database type "${value.kind}"`);
}
function literal(value:unknown):string {
 if(value===null)return 'NULL';if(typeof value==='boolean')return value?'TRUE':'FALSE';if(typeof value==='number'&&Number.isFinite(value))return String(value);if(typeof value==='bigint')return value.toString();if(typeof value==='string')return `'${value.replace(/'/g,"''")}'`;
 throw new Error('PIPE-MIG-001: PostgreSQL defaults must be scalar literals');
}
const fieldType=(field:DbField)=>sqlType(field.type);
function columnDefinition(field:DbField):string {
 let sql=`${q(field.name)} ${field.primaryKey?'bigint GENERATED BY DEFAULT AS IDENTITY':fieldType(field)}`;
 if(field.primaryKey)sql+=' PRIMARY KEY';else if(field.required)sql+=' NOT NULL';
 if(field.default!==undefined)sql+=` DEFAULT ${literal(field.default)}`;
 return sql;
}
async function apply(client:PgClient,schema:DbSchema):Promise<void> {
 const changes:string[]=[];
 await client.query('CREATE TABLE IF NOT EXISTS "_bmec_migrations" (version BIGSERIAL PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now(), changes JSONB NOT NULL)');
 for(const model of schema.models){
  const existing=await client.query('SELECT 1 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name=$1',[model.name]);
  if(!existing.rows.length){await client.query(`CREATE TABLE ${q(model.name)} (${model.fields.map(columnDefinition).join(', ')})`);changes.push(`add model ${model.name}`);continue;}
  const columns=await client.query('SELECT column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=$1',[model.name]);
  const byName=new Map(columns.rows.map(row=>[String(row.column_name),row]));
  for(const field of model.fields){
   const old=byName.get(field.name);
   if(!old){if(field.required&&field.default===undefined)throw new Error(`PIPE-MIG-001: Cannot add required field ${model.name}.${field.name} without a default`);await client.query(`ALTER TABLE ${q(model.name)} ADD COLUMN ${columnDefinition(field)}`);changes.push(`add field ${model.name}.${field.name}`);continue;}
   const wanted=fieldType(field),actual=normalizePostgresType(String(old.data_type));
   if(actual!==wanted)throw new Error(`PIPE-MIG-001: Unsafe PostgreSQL type change. ${model.name}.${field.name} changed from ${actual} to ${wanted}.`);
   if(String(old.is_nullable)===(field.required?'YES':'NO'))throw new Error(`PIPE-MIG-001: PostgreSQL nullability change is not supported safely for ${model.name}.${field.name}.`);
  }
  const wanted=new Set(model.fields.map(field=>field.name));for(const name of byName.keys())if(!wanted.has(name))throw new Error(`PIPE-MIG-001: PostgreSQL field removal is not supported safely. ${model.name}.${name} must remain in the schema.`);
 }
 for(const model of schema.models)for(const foreign of model.foreignKeys??[]){
  const name=stableName('bmec_fk',`${model.name}.${foreign.field}->${foreign.references.modelId}.${foreign.references.field}`);
  const found=await client.query('SELECT 1 FROM pg_constraint WHERE conrelid=to_regclass($1) AND conname=$2',[q(model.name),name]);
  if(found.rows.length)continue;
  const target=schema.models.find(candidate=>candidate.id===foreign.references.modelId)!;
  await client.query(`ALTER TABLE ${q(model.name)} ADD CONSTRAINT ${q(name)} FOREIGN KEY (${q(foreign.field)}) REFERENCES ${q(target.name)} (${q(foreign.references.field)})`);
  changes.push(`add foreign key ${model.name}.${foreign.field}`);
 }
 for(const model of schema.models){
  const uniqueIndexes=[...(model.uniqueConstraints??[]).map(fields=>({fields})),...model.fields.filter(field=>field.unique&&!field.primaryKey).map(field=>({fields:[field.name]}))];
  for(const unique of uniqueIndexes){const name=stableName('bmec_uq',`${model.name}:${unique.fields.join(',')}`);await ensureIndex(client,model,{name,fields:unique.fields},changes,true);}
  for(const index of model.indexes??[])await ensureIndex(client,model,index,changes);
 }
 if(changes.length){const version=await client.query('SELECT COALESCE(MAX(version),0)+1 AS version FROM "_bmec_migrations"');await client.query('INSERT INTO "_bmec_migrations"(version,changes) VALUES($1,$2::jsonb)',[Number(version.rows[0]?.version??1),JSON.stringify(changes)]);}
}

async function ensureIndex(client:PgClient,model:DbModel,index:DbIndex,changes:string[],unique=false):Promise<void>{
 const found=await client.query(`SELECT array_agg(a.attname ORDER BY k.ordinality) AS fields, bool_or(i.indisunique) AS is_unique FROM pg_class table_ref JOIN pg_namespace ns ON ns.oid=table_ref.relnamespace JOIN pg_index i ON i.indrelid=table_ref.oid JOIN pg_class index_ref ON index_ref.oid=i.indexrelid CROSS JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS k(attnum,ordinality) JOIN pg_attribute a ON a.attrelid=table_ref.oid AND a.attnum=k.attnum WHERE ns.nspname=current_schema() AND table_ref.relname=$1 AND index_ref.relname=$2 AND k.ordinality<=i.indnkeyatts GROUP BY index_ref.relname`,[model.name,index.name]);
 if(found.rows.length){const raw=found.rows[0]?.fields;const columns=Array.isArray(raw)?raw.map(String):typeof raw==='string'&&raw.startsWith('{')&&raw.endsWith('}')?raw.slice(1,-1).split(',').map(value=>value.replace(/^"|"$/g,'')):[];if(JSON.stringify(columns)!==JSON.stringify(index.fields)||Boolean(found.rows[0]?.is_unique)!==unique)throw new Error(`PIPE-MIG-001: Index ${index.name} changed definition; add a new index name and review the old index before removal.`);return;}
 await client.query(`CREATE ${unique?'UNIQUE ':''}INDEX ${q(index.name)} ON ${q(model.name)} (${index.fields.map(q).join(', ')})`);
 changes.push(`add ${unique?'unique ':''}index ${index.name} on ${model.name} (${index.fields.join(', ')})`);
}

/** Apply safe additive model changes and declared indexes in one PostgreSQL transaction. */
export async function migratePostgresSchema(pool:PgPool,schema:DbSchema):Promise<void>{
 const errors=validateDbSchema(schema);if(errors.length)throw new Error(`PIPE-MIG-001: Invalid canonical database schema. ${errors.join('; ')}`);
 const client=await pool.connect();
 try{await client.query('BEGIN');await apply(client,schema);await client.query('COMMIT');}
 catch(error){try{await client.query('ROLLBACK')}catch{}throw error;}
 finally{client.release();}
}
