import {describe,it,expect,afterEach} from 'vitest';import Database from 'better-sqlite3';import {compile} from '../src/compiler.js';import {startRuntime,type RuntimeHandle} from '../src/runtime/server.js';import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const v1='app X\nmodel Task { title text required }';const v2='app X\nmodel Task { title text required done boolean default false }';const rel='app X\nmodel User { name text required }\nmodel Task { title text required owner User }\napi /tasks from Task';let hs:RuntimeHandle[]=[];afterEach(async()=>{for(const h of hs.splice(0))await h.close()});
async function boot(s:string,file?:string){const r=compile(s);expect(r.ir).toBeTruthy();const root=mkdtempSync(join(tmpdir(),'pipe-a3-'));const h=await startRuntime(r.ir!,join(root,'out'),file||join(root,'x.db'),0);hs.push(h);return {h,root}};
describe('Alpha 3 migrations and APIs',()=>{
 it('adds a defaulted column without losing rows',async()=>{const a=await boot(v1);await fetch(a.h.url+'/api/Task',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'old'})});await a.h.close();hs=[];const r=compile(v2),h=await startRuntime(r.ir!,join(a.root,'out2'),join(a.root,'x.db'),0);hs.push(h);const row=(await (await fetch(h.url+'/api/Task')).json())[0];expect(row.title).toBe('old');expect(row.done).toBe(0);const db=new Database(join(a.root,'x.db'));expect((db.prepare('select count(*) n from _pipe_migrations').get() as any).n).toBe(2);db.close()})
 it('supports explicit API collection and item routes',async()=>{const {h}=await boot(rel);const u=await (await fetch(h.url+'/api/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'t'})})).json() as any;expect(u.id).toBe(1);expect((await (await fetch(h.url+'/api/tasks/1')).json()).title).toBe('t');expect((await fetch(h.url+'/api/tasks/99')).status).toBe(404)})
 it('supports complete explicit API CRUD',async()=>{const {h}=await boot(rel);const created=await (await fetch(h.url+'/api/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'t'})})).json() as any;expect((await (await fetch(h.url+'/api/tasks')).json()).length).toBe(1);const updated=await (await fetch(h.url+`/api/tasks/${created.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({title:'updated'})})).json() as any;expect(updated.title).toBe('updated');expect((await fetch(h.url+`/api/tasks/${created.id}`,{method:'DELETE'})).status).toBe(204);expect((await (await fetch(h.url+'/api/tasks')).json()).length).toBe(0)})
 it('validates relationship existence',async()=>{const {h}=await boot(rel);const r=await fetch(h.url+'/api/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'t',owner:99})});expect(r.status).toBe(400);expect((await r.json()).diagnostic.kind).toBe('referenced_record_missing')})
 it('accepts a persisted relationship',async()=>{const {h}=await boot(rel);const u=await (await fetch(h.url+'/api/User',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'u'})})).json() as any;const t=await (await fetch(h.url+'/api/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'t',owner:u.id})})).json() as any;expect(t.owner).toBe(u.id)})
 it('rejects unsafe type migration',async()=>{const a=await boot(v1);await fetch(a.h.url+'/api/Task',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'old'})});await a.h.close();hs=[];const r=compile('app X\nmodel Task { title integer }');await expect(startRuntime(r.ir!,join(a.root,'out2'),join(a.root,'x.db'),0)).rejects.toThrow('PIPE-MIG-001')})
 it('reports unknown API model',()=>expect(compile('api /x from Missing').diagnostics[0]).toMatchObject({code:'PIPE-API-002',kind:'unknown_reference'}));
});
