import {describe,it,expect} from 'vitest';import {lex,PipeLexError} from '../src/lexer/lexer.js';import {parse,PipeParseError} from '../src/parser/parser.js';import {compile} from '../src/compiler.js';import {toIR} from '../src/ir/ir.js';import {graph} from '../src/graph/graph.js';
describe('Alpha 3 compiler edge cases',()=>{
 it.each(['style "unterminated','app X @','model X { a text ! }'])('rejects malformed source %s',s=>expect(()=>parse(s)).toThrow());
 it('keeps locations after mixed whitespace',()=>expect(lex('\r\n\t app X')[0].span.start).toMatchObject({line:2,column:3}));
 it('supports route punctuation',()=>expect(lex('api /tasks-from from Task').map(x=>x.value)).toContain('/'));
 it('decodes escaped quotes',()=>expect(lex('style "a\\\"b"')[1].value).toBe('a"b'));
 it('rejects incomplete API',()=>expect(()=>parse('api /x')).toThrow(PipeParseError));
 it('rejects incomplete page',()=>expect(()=>parse('page P { crud')).toThrow());
 it('rejects unknown declaration',()=>expect(()=>parse('widget X')).toThrow());
 it('rejects missing model name',()=>expect(()=>parse('model {')).toThrow());
 it.each(['model M { x boolean default 1 }','model M { x integer default "x" }','model M { x number default false }'])('rejects invalid default %s',s=>expect(compile(s).diagnostics[0].code).toBe('PIPE-TYPE-002'));
 it('accepts forward relationship references',()=>expect(compile('model A { b B } model B {}').diagnostics).toEqual([]));
 it('rejects missing relationship reference',()=>expect(compile('model A { b B }').diagnostics[0].code).toBe('PIPE-TYPE-001'));
 it('rejects duplicate API routes',()=>expect(compile('model M {} api /m from M api /m from M').diagnostics[0].code).toBe('PIPE-API-001'));
 it('rejects unknown API model',()=>expect(compile('api /m from M').diagnostics[0].code).toBe('PIPE-API-002'));
 it('serializes relationship type in IR',()=>expect(toIR(parse('model User {} model Task { owner User }')).models[1].fields[0].type).toBe('User'));
 it('creates API operations in IR',()=>expect(toIR(parse('model M {} api /m from M')).apis[0].operations).toEqual(['create','read','update','delete']));
 it('gives APIs stable IDs',()=>expect(toIR(parse('model M {} api /m from M')).apis[0].id).toBe('API-001'));
 it('links relationship fields in graph',()=>expect(graph(toIR(parse('model U {} model T { u U }'))).find(n=>n.name==='u')?.references).toEqual(['DB-001']));
 it('links APIs in graph',()=>expect(graph(toIR(parse('model M {} api /m from M'))).find(n=>n.kind==='api')?.references).toEqual(['DB-001']));
 it('keeps graph deterministic',()=>expect(graph(toIR(parse('model M {} api /m from M')))).toEqual(graph(toIR(parse('model M {} api /m from M')))));
 it('reports source file in diagnostics',()=>expect(compile('model M { x nope }','x.pipe').diagnostics[0].file).toBe('x.pipe'));
 it('reports diagnostic path for API model',()=>expect(compile('api /m from M').diagnostics[0].path).toBe('api./m.model'));
 it('allows comments around API',()=>expect(parse('#x\nmodel M {}\n//x\napi /m from M').declarations).toHaveLength(2));
 it('allows empty models',()=>expect(compile('app X model M {}').diagnostics).toEqual([]));
 it('allows multiple models',()=>expect(toIR(parse('model A {} model B {}')).models).toHaveLength(2));
 it('allows unique text fields',()=>expect(compile('model M { email text unique }').diagnostics).toEqual([]));
 it('allows numeric negative defaults',()=>expect(compile('model M { n integer default -2 }').diagnostics).toEqual([]));
 it('rejects unexpected field token',()=>expect(()=>parse('model M { 2 text }')).toThrow());
 it('rejects unexpected lexer character',()=>expect(()=>lex('model M { x text; }')).toThrow(PipeLexError));
 it('preserves API route spelling',()=>expect(toIR(parse('model M {} api /my-tasks from M')).apis[0].route).toBe('/my-tasks'));
 it('exposes APIs as app children',()=>expect(graph(toIR(parse('model M {} api /m from M')))[0].children).toContain('API-001'));
 it('exposes nested UI child nodes and component references',()=>{const nodes=graph(toIR(parse('app Demo\ncomponent Card { text "Hi" }\npage Home { use Card }')));const page=nodes.find(node=>node.id==='UI-001')!,child=nodes.find(node=>node.id==='UI-001:ui:0')!,component=nodes.find(node=>node.id==='COMP-001')!;expect(page.children).toEqual(['UI-001:ui:0']);expect(child).toMatchObject({kind:'ui-node',name:'component COMP-001',references:['COMP-001']});expect(component.children).toEqual(['COMP-001:ui:0']);});
 it('preserves deterministic source order and graph ownership for lists and feedback',()=>{const nodes=graph(toIR(parse('app Demo\ncomponent Row { text "row" }\npage Home { state items list<text> list items item Row loading "Loading" error "Failed" }')));const page=nodes.find(node=>node.id==='UI-001')!,loading=nodes.find(node=>node.id==='UI-001:ui:1')!,list=nodes.find(node=>node.id==='UI-001:ui:0')!,listChild=nodes.find(node=>node.id==='UI-001:ui:0:ui:0')!;expect(page.children).toEqual(['UI-001:ui:0','UI-001:ui:1','UI-001:ui:2']);expect(list).toMatchObject({name:'list items',children:['UI-001:ui:0:ui:0']});expect(listChild).toMatchObject({name:'component COMP-001',references:['COMP-001']});expect(loading).toMatchObject({name:'feedback loading',children:[],facts:{state:'loading',message:'Loading'}});});
 it('exposes typed list empty-state facts in the UI graph',()=>{const nodes=graph(toIR(parse('app Demo\ncomponent Row { text "row" }\npage Home { state items list<text> list items item Row empty "No rows" }')));expect(nodes.find(node=>node.id==='UI-001:ui:0')).toMatchObject({name:'list items',facts:{source:'items',item:'item',empty:'No rows'}});});
 it('exposes typed filter and page-size settings in UI graph facts',()=>{const nodes=graph(toIR(parse('app Demo\nmodel Task { title text }\ncomponent Row { show task title }\npage Home { state tasks list<Task> for each task in tasks show Row filter by title paginate 25 }')));expect(nodes.find(node=>node.id==='UI-001:ui:0')).toMatchObject({name:'list tasks',facts:{source:'tasks',item:'task',filterBy:'title',pageSize:25}});});
});
