import {describe,expect,it} from 'vitest';
import {readFileSync,mkdtempSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {compile} from '../src/compiler.js';
import {generate} from '../src/generator/generate.js';
import {buildRelease} from '../src/release/release.js';

describe('generated browser bundle runtime',()=>{
 it('submits typed path parameters in the URL and keeps them out of the JSON body',async()=>{
  const source='app Shop\nmodel OrderUpdate { quantity integer }\nfunction updateOrder(orderId id, body OrderUpdate) -> integer { return body.quantity }\nhttp PUT /orders/:orderId -> updateOrder\ncomponent EditOrder form { input orderId id input quantity integer button "Save" on save }\npage Editor { event save(orderId id, quantity integer) sends PUT "/orders/:orderId" use EditOrder }';
  const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-dynamic-action-')),'release');buildRelease(compiled.ir!,directory,{packageName:'shop',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});expect(readFileSync(join(directory,'index.html'),'utf8')).toContain('pathParameters');
  const inputs:any={orderId:{value:'a/b',dataset:{pipeType:'id'}},quantity:{value:'3',dataset:{pipeType:'integer'}}};const form:any={elements:{namedItem:(name:string)=>inputs[name]},querySelectorAll:()=>[]};const status:any={dataset:{pipeActionStatus:'save'},textContent:'',setAttribute(){}};const button:any={dataset:{pipeEvent:'save',pipeAction:JSON.stringify({method:'PUT',path:'/orders/:orderId',pathParameters:['orderId'],fields:{orderId:'id',quantity:'integer'}})},listeners:{} as Record<string,(event:any)=>void>,closest:()=>form,nextElementSibling:status,addEventListener(name:string,fn:(event:any)=>void){this.listeners[name]=fn}};const document={querySelectorAll(selector:string){return selector==='button[data-pipe-event]'?[button]:[] as any[]}};const requests:any[]=[];let refreshed=0;class FormDataShim{[Symbol.iterator](){return [['orderId','a/b'],['quantity','3']][Symbol.iterator]()}};const context:any={document,PIPE_UI_REFRESH:async()=>{refreshed++},FormData:FormDataShim,fetch:async(path:string,init:any)=>{requests.push({path,init});return {ok:true}}};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);button.listeners.click({});await new Promise(resolve=>setTimeout(resolve,0));expect(requests[0]?.path).toBe('/orders/a%2Fb');expect(JSON.parse(requests[0]?.init.body)).toEqual({quantity:3});expect(status.textContent).toBe('Submitted.');expect(refreshed).toBe(1);
 });
 it('submits a type-checked BMEC page action to its declared route',async()=>{
  const source='app Shop\nmodel Order { productId id required quantity integer required }\nasync function createOrder(db capability<database>, body Order) -> task<integer> { return wait for add body to Order using db }\nhttp POST /orders requires database -> createOrder\ncomponent CartForm form { input productId id input quantity integer button "Add" on add }\npage Store { event add(productId id, quantity integer) sends POST "/orders" use CartForm }';
  const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-action-')),'release');buildRelease(compiled.ir!,directory,{packageName:'shop',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const inputs:any={productId:{value:'cup-1',dataset:{pipeType:'id'}},quantity:{value:'3',dataset:{pipeType:'integer'}}};const form:any={elements:{namedItem:(name:string)=>inputs[name]},querySelectorAll:()=>[],};const status:any={dataset:{pipeActionStatus:'add'},textContent:'',setAttribute(){}};const button:any={dataset:{pipeEvent:'add',pipeAction:JSON.stringify({method:'POST',path:'/orders',fields:{productId:'id',quantity:'integer'}})},listeners:{} as Record<string,(event:any)=>void>,closest:()=>form,nextElementSibling:status,addEventListener(name:string,fn:(event:any)=>void){this.listeners[name]=fn}};const document={querySelectorAll(selector:string){return selector==='button[data-pipe-event]'?[button]:[] as any[]}};const requests:any[]=[];class FormDataShim{[Symbol.iterator](){return [['productId','cup-1'],['quantity','3']][Symbol.iterator]()}};const context:any={document,FormData:FormDataShim,fetch:async(path:string,init:any)=>{requests.push({path,init});return {ok:true}}};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);button.listeners.click({});await new Promise(resolve=>setTimeout(resolve,0));expect(requests[0]?.path).toBe('/orders');expect(requests[0]?.init.method).toBe('POST');expect(JSON.parse(requests[0]?.init.body)).toEqual({productId:'cup-1',quantity:3});expect(status.textContent).toBe('Submitted.');expect(readFileSync(join(directory,'server-ir.json'),'utf8')).toContain('createOrder');expect(readFileSync(join(directory,'app.js'),'utf8')).not.toContain('createOrder');expect(readFileSync(join(directory,'pipe-ir.json'),'utf8')).not.toContain('createOrder');
 });
 it('submits typed parameters from the clicked repeated-list row',async()=>{
  const source='app Shop\nmodel Product { sku text required }\nmodel CartLine { sku text required }\napi /cart-lines from CartLine\ncomponent ProductRow { button "Add" on add with sku from product.sku }\npage Store { event add(sku text) sends POST "/cart-lines" state products list<Product> for each product in products show ProductRow }';
  const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-row-action-')),'release');buildRelease(compiled.ir!,directory,{packageName:'shop',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const status:any={dataset:{pipeActionStatus:'add'},textContent:'',setAttribute(){}};const row:any={dataset:{pipeRowItem:'product',pipeRow:JSON.stringify({sku:'cup-1'})}};const button:any={dataset:{pipeEvent:'add',pipeAction:JSON.stringify({method:'POST',path:'/cart-lines',pathParameters:[],fields:{sku:'text'},arguments:{sku:{path:'product.sku'}}})},listeners:{} as Record<string,(event:any)=>void>,closest:(selector:string)=>selector==='form'?null:row,nextElementSibling:status,addEventListener(name:string,fn:(event:any)=>void){this.listeners[name]=fn}};const document={querySelectorAll(selector:string){return selector==='button[data-pipe-event]'?[button]:[] as any[]}};const requests:any[]=[];const context:any={document,PIPE_UI_STATE:{},fetch:async(path:string,init:any)=>{requests.push({path,init});return {ok:true,json:async()=>({state:'ok',value:true})}}};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);button.listeners.click({});await new Promise(resolve=>setTimeout(resolve,0));expect(requests[0]?.path).toBe('/cart-lines');expect(requests[0]?.init.method).toBe('POST');expect(JSON.parse(requests[0]?.init.body)).toEqual({sku:'cup-1'});expect(status.textContent).toBe('Submitted.');
 });
  it('combines persisted typed page state with form values in an HTTP action',async()=>{
   const source='app Shop\nmodel CartLine { name text required quantity integer required }\nmodel CheckoutRequest { customerName text required customerEmail text required items list<CartLine> required }\napi /checkout from CheckoutRequest\ncomponent CheckoutForm form { input customerName text input customerEmail text button "Complete" on checkout with items from cart }\npage Store { event checkout(customerName text, customerEmail text, items list<CartLine>) sends POST "/checkout" use CheckoutForm state cart list<CartLine> = [] persisted in local storage }';
   const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'bmec-browser-state-action-')),'release');buildRelease(compiled.ir!,directory,{packageName:'shop',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});expect(readFileSync(join(directory,'index.html'),'utf8')).toContain('&quot;source&quot;:&quot;state&quot;');
   const inputs:any={customerName:{value:'Marin'},customerEmail:{value:'marin@example.test'}};const form:any={elements:{namedItem:(name:string)=>inputs[name]},querySelectorAll:()=>[]};const cart=[{name:'Notebook',quantity:2}];const action={method:'POST',path:'/checkout',pathParameters:[],fields:{customerName:'text',customerEmail:'text',items:'compound'},arguments:{items:{path:'cart',source:'state'}}};const status:any={dataset:{pipeActionStatus:'checkout'},textContent:'',setAttribute(){}};const button:any={dataset:{pipeEvent:'checkout',pipeAction:JSON.stringify(action)},listeners:{} as Record<string,(event:any)=>void>,closest:()=>form,nextElementSibling:status,addEventListener(name:string,fn:(event:any)=>void){this.listeners[name]=fn}};const document={querySelectorAll(selector:string){return selector==='button[data-pipe-event]'?[button]:[] as any[]}};const requests:any[]=[];class FormDataShim{[Symbol.iterator](){return [['customerName','Marin'],['customerEmail','marin@example.test']][Symbol.iterator]()}};const context:any={document,PIPE_UI_STATE:{cart},FormData:FormDataShim,fetch:async(path:string,init:any)=>{requests.push({path,init});return {ok:true,json:async()=>({state:'ok',value:true})}}};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);button.listeners.click({});await new Promise(resolve=>setTimeout(resolve,0));expect(requests[0]?.path).toBe('/checkout');expect(JSON.parse(requests[0]?.init.body)).toEqual({customerName:'Marin',customerEmail:'marin@example.test',items:cart});expect(status.textContent).toBe('Submitted.');
  });
  it('updates a typed list from a row and restores validated persisted state after reload',()=>{
  const source='app Tasks\nmodel Task { title text required }\ncomponent TaskRow { button "Add" on add with task from task }\npage Home { event add(task Task) appends task to tasks state tasks list<Task> = [] persisted in local storage for each task in tasks show TaskRow }';const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'bmec-browser-persisted-state-')),'release');buildRelease(compiled.ir!,directory,{packageName:'tasks',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});const page=compiled.ir!.ui!.components[0]!,update=page.events[0]!.stateUpdate!,storageKey=page.state[0]!.storageKey!;const storage=new Map<string,string>();const makeContext=(initial:Record<string,unknown>)=>{const listeners:Record<string,((event:any)=>void)[]>={};const row:any={dataset:{pipeRowItem:'task',pipeRow:JSON.stringify({id:4,title:'Tea'})}};const button:any={dataset:{pipeEvent:'add',pipeStateUpdate:JSON.stringify({...update,arguments:{task:{path:'task'}}})},listeners,closest:(selector:string)=>selector==='[data-pipe-row]'?row:null,addEventListener(name:string,handler:(event:any)=>void){(listeners[name]??=[]).push(handler)}};const document={querySelectorAll(selector:string){if(selector==='button[data-pipe-state-update]'||selector==='button[data-pipe-event]')return [button];return [] as any[]}};const localStorage={getItem:(key:string)=>storage.get(key)??null,setItem:(key:string,value:string)=>storage.set(key,value),removeItem:(key:string)=>storage.delete(key)};const context:any={document,PIPE_UI_STATE:initial,localStorage,location:{hash:'',pathname:'/'},addEventListener(){},setTimeout,clearTimeout};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);return {context,button}};const first=makeContext({});first.button.listeners.click!.forEach(handler=>handler({preventDefault(){}}));first.button.listeners.click![0]!({preventDefault(){}});expect(first.context.PIPE_UI_STATE.tasks).toEqual([{id:4,title:'Tea'},{id:4,title:'Tea'}]);expect(JSON.parse(storage.get(storageKey)!)).toEqual([{id:4,title:'Tea'},{id:4,title:'Tea'}]);const reloaded=makeContext({});expect(reloaded.context.PIPE_UI_STATE.tasks).toEqual([{id:4,title:'Tea'},{id:4,title:'Tea'}]);storage.set(storageKey,JSON.stringify([{id:5,title:12}]));const invalid=makeContext({});expect(invalid.context.PIPE_UI_STATE.tasks).toEqual([]);expect(storage.has(storageKey)).toBe(false);
 });
 it('projects a repeated product row into the persisted cart-line shape',()=>{
  const source='app Shop\nmodel Product { id integer name text price money }\ntype CartLine { productId integer name text unitPrice money quantity integer }\ncomponent ProductRow { button "Add" on add with product from product }\npage Store { event add(product Product) appends product as CartLine { productId: product.id, name: product.name, unitPrice: product.price, quantity: 1 } to cart state cart list<CartLine> = [] persisted in local storage state products list<Product> = [] for each product in products show ProductRow }';
  const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'bmec-browser-cart-projection-')),'release');buildRelease(compiled.ir!,directory,{packageName:'shop',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});const component=compiled.ir!.ui!.components.find(item=>item.name==='Store')!,update=component.events[0]!.stateUpdate!,storageKey=component.state.find(item=>item.name==='cart')!.storageKey!;const storage=new Map<string,string>(),listeners:Record<string,(event:any)=>void>={};const row:any={dataset:{pipeRowItem:'product',pipeRow:JSON.stringify({id:12,name:'Tea',price:{minor:450,currency:'USD'},stock:5})}};const button:any={dataset:{pipeEvent:'add',pipeStateUpdate:JSON.stringify({...update,arguments:{product:{path:'product'}}})},listeners,closest:(selector:string)=>selector==='[data-pipe-row]'?row:null,addEventListener(name:string,handler:(event:any)=>void){listeners[name]=handler}};const document={querySelectorAll(selector:string){return selector==='button[data-pipe-state-update]'?[button]:[] as any[]}};const localStorage={getItem:(key:string)=>storage.get(key)??null,setItem:(key:string,value:string)=>storage.set(key,value),removeItem:(key:string)=>storage.delete(key)};const context:any={document,PIPE_UI_STATE:{},localStorage,location:{hash:'',pathname:'/'},addEventListener(){},setTimeout,clearTimeout};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);button.listeners.click({preventDefault(){}});expect(button.dataset.pipeError).toBeUndefined();expect(context.PIPE_UI_STATE.cart).toEqual([{productId:12,name:'Tea',unitPrice:{minor:450,currency:'USD'},quantity:1}]);expect(JSON.parse(storage.get(storageKey)!)).toEqual([{productId:12,name:'Tea',unitPrice:{minor:450,currency:'USD'},quantity:1}]);
 });
 it('projects an in-memory product row without a generated id into a persistent cart',()=>{
  const source='app Shop\nmodel Product { name text price integer }\ntype CartLine { productName text price integer quantity integer }\ncomponent ProductRow { button "Add" on add with product from product }\npage Store { event add(product Product) appends product as CartLine { productName: product.name, price: product.price, quantity: 1 } to cart state cart list<CartLine> = [] persisted in local storage state products list<Product> = [] for each product in products show ProductRow }';
  const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'bmec-browser-cart-without-model-id-')),'release');buildRelease(compiled.ir!,directory,{packageName:'shop',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});const component=compiled.ir!.ui!.components.find(item=>item.name==='Store')!,update=component.events[0]!.stateUpdate!,storageKey=component.state.find(item=>item.name==='cart')!.storageKey!;const storage=new Map<string,string>(),listeners:Record<string,(event:any)=>void>={};const row:any={dataset:{pipeRowItem:'product',pipeRow:JSON.stringify({name:'Tidepool Sketchbook',price:2400})}};const button:any={dataset:{pipeEvent:'add',pipeStateUpdate:JSON.stringify({...update,arguments:{product:{path:'product'}}})},listeners,closest:(selector:string)=>selector==='[data-pipe-row]'?row:null,addEventListener(name:string,handler:(event:any)=>void){listeners[name]=handler}};const document={querySelectorAll(selector:string){return selector==='button[data-pipe-state-update]'?[button]:[] as any[]}};const localStorage={getItem:(key:string)=>storage.get(key)??null,setItem:(key:string,value:string)=>storage.set(key,value),removeItem:(key:string)=>storage.delete(key)};const context:any={document,PIPE_UI_STATE:{},localStorage,location:{hash:'',pathname:'/'},addEventListener(){},setTimeout,clearTimeout};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);button.listeners.click({preventDefault(){}});expect(button.dataset.pipeError).toBeUndefined();expect(context.PIPE_UI_STATE.cart).toEqual([{productName:'Tidepool Sketchbook',price:2400,quantity:1}]);expect(JSON.parse(storage.get(storageKey)!)).toEqual([{productName:'Tidepool Sketchbook',price:2400,quantity:1}]);
 });
 it('omits an absent optional row-bound action field',async()=>{
  const source='app Shop\nmodel Product { sku text? }\nmodel CartLine { sku text? }\napi /cart-lines from CartLine\ncomponent ProductRow { button "Add" on add with sku from product.sku }\npage Store { event add(sku text?) sends POST "/cart-lines" state products list<Product> for each product in products show ProductRow }';
  const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-optional-row-action-')),'release');buildRelease(compiled.ir!,directory,{packageName:'shop',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const status:any={dataset:{pipeActionStatus:'add'},textContent:'',setAttribute(){}};const row:any={dataset:{pipeRowItem:'product',pipeRow:JSON.stringify({sku:null})}};const button:any={dataset:{pipeEvent:'add',pipeAction:JSON.stringify({method:'POST',path:'/cart-lines',pathParameters:[],fields:{sku:'text'},optionalFields:['sku'],arguments:{sku:{path:'product.sku'}}})},listeners:{} as Record<string,(event:any)=>void>,closest:(selector:string)=>selector==='form'?null:row,nextElementSibling:status,addEventListener(name:string,fn:(event:any)=>void){this.listeners[name]=fn}};const document={querySelectorAll(selector:string){return selector==='button[data-pipe-event]'?[button]:[] as any[]}};const requests:any[]=[];const context:any={document,PIPE_UI_STATE:{},fetch:async(path:string,init:any)=>{requests.push({path,init});return {ok:true,json:async()=>({state:'ok',value:true})}}};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);button.listeners.click({});await new Promise(resolve=>setTimeout(resolve,0));expect(JSON.parse(requests[0]?.init.body)).toEqual({});expect(status.textContent).toBe('Submitted.');
 });
 it('preserves compound values from a typed repeated row',async()=>{
  const source='app Shop\ntype ProductInfo { label text }\nmodel Product { info ProductInfo }\nmodel CartLine { info ProductInfo }\napi /cart-lines from CartLine\ncomponent ProductRow { button "Add" on add with info from product.info }\npage Store { event add(info ProductInfo) sends POST "/cart-lines" state products list<Product> for each product in products show ProductRow }';
  const compiled=compile(source);expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-compound-row-action-')),'release');buildRelease(compiled.ir!,directory,{packageName:'shop',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const status:any={dataset:{pipeActionStatus:'add'},textContent:'',setAttribute(){}};const info={label:'special edition'};const row:any={dataset:{pipeRowItem:'product',pipeRow:JSON.stringify({info})}};const button:any={dataset:{pipeEvent:'add',pipeAction:JSON.stringify({method:'POST',path:'/cart-lines',pathParameters:[],fields:{info:'compound'},arguments:{info:{path:'product.info'}}})},listeners:{} as Record<string,(event:any)=>void>,closest:(selector:string)=>selector==='form'?null:row,nextElementSibling:status,addEventListener(name:string,fn:(event:any)=>void){this.listeners[name]=fn}};const document={querySelectorAll(selector:string){return selector==='button[data-pipe-event]'?[button]:[] as any[]}};const requests:any[]=[];const context:any={document,PIPE_UI_STATE:{},fetch:async(path:string,init:any)=>{requests.push({path,init});return {ok:true,json:async()=>({state:'ok',value:true})}}};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),context);button.listeners.click({});await new Promise(resolve=>setTimeout(resolve,0));expect(JSON.parse(requests[0]?.init.body)).toEqual({info});expect(status.textContent).toBe('Submitted.');
 });
 it('omits unused event runtimes from static browser pages',()=>{
  const compiled=compile('app Static\npage Home { }');
  expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-static-')),'release');
  buildRelease(compiled.ir!,directory,{packageName:'static',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const script=readFileSync(join(directory,'app.js'),'utf8');
  expect(script).not.toContain('PIPE_UI_EVENTS');
  expect(script.length).toBeLessThan(7000);
 });
 it('emits deterministic bound-field hydration for generated page lists',()=>{
  const compiled=compile('app Tasks\nmodel User { name text }\ncomponent Row { show task name }\npage Home { state tasks list<User> for each task in tasks show Row }');
  expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-binding-')),'release');buildRelease(compiled.ir!,directory,{packageName:'tasks',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const html=readFileSync(join(directory,'index.html'),'utf8'),script=readFileSync(join(directory,'app.js'),'utf8');expect(html).toContain('data-pipe-bind="task.name"');expect(script).toContain('data-pipe-bind');expect(script).toContain('pipeItem');
 });
 it('executes generated page-list filtering and accessible no-match feedback',()=>{
  const compiled=compile('app Tasks\nenum TaskStatus { Inbox Active Done }\nmodel Task { title text status TaskStatus }\ncomponent Row { show task title show task status }\npage Home { state tasks list<Task> for each task in tasks show Row filter by title paginate 1 }');expect(compiled.diagnostics).toEqual([]);
  const directory=mkdtempSync(join(tmpdir(),'pipe-generated-list-filter-'));generate(compiled.ir!,directory);const html=readFileSync(join(directory,'index.html'),'utf8'),match=/<script>([\s\S]*?)<\/script>/.exec(html);expect(match).toBeTruthy();
  const make=(tag:string)=>({tag,dataset:{} as Record<string,string>,attributes:{} as Record<string,string>,children:[] as any[],listeners:{} as Record<string,(event?:unknown)=>void>,appendChild(child:any){this.children.push(child)},replaceChildren(...children:any[]){this.children=children},addEventListener(name:string,handler:(event?:unknown)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}});
  const search:any=make('input');search.value='';const previous:any=make('button'),next:any=make('button'),range:any=make('span');const bind:any={dataset:{pipeBind:'task.title'},textContent:''},enumBind:any={dataset:{pipeBind:'task.status'},textContent:''};const template:any={cloneNode(){const clonedBind:any={...bind,dataset:{...bind.dataset}},clonedEnumBind:any={...enumBind,dataset:{...enumBind.dataset}};return {dataset:{},querySelectorAll:()=>[clonedBind,clonedEnumBind],bind:clonedBind,enumBind:clonedEnumBind}}};
  const list:any=make('div');list.dataset={pipeList:'tasks',pipeItem:'task',pipeListFilterBy:'title',pipeListPageSize:'1',pipeListLoadingState:'loading',pipeListErrorState:'error'};list.firstElementChild=template;list.parentElement={querySelector:(selector:string)=>({'[data-pipe-list-filter]':search,'[data-pipe-list-prev]':previous,'[data-pipe-list-next]':next,'[data-pipe-list-range]':range}[selector])};
  const document:any={querySelectorAll(selector:string){if(selector==='[data-pipe-list]')return [list];return []},createElement:(tag:string)=>make(tag)};
  let rebound=0;const globalThis={PIPE_UI_REBIND_EVENTS(){rebound++},PIPE_UI_STATE:{tasks:[{title:'Alpha',status:{variant:'Inbox'}},{title:'Beta',status:{variant:'Active'}}],loading:false,error:false}};vm.runInNewContext(match![1]!,{document,globalThis});expect(rebound).toBe(1);expect(list.children.map((row:any)=>row.bind.textContent)).toEqual(['Alpha']);expect(list.children[0].enumBind.textContent).toBe('Inbox');expect(range.textContent).toBe('Showing 1-1 of 2');
  next.listeners.click();expect(rebound).toBe(2);expect(list.children.map((row:any)=>row.bind.textContent)).toEqual(['Beta']);expect(list.children[0].enumBind.textContent).toBe('Active');expect(range.textContent).toBe('Showing 2-2 of 2');search.value='bet';search.listeners.input();expect(rebound).toBe(3);expect(list.children.map((row:any)=>row.bind.textContent)).toEqual(['Beta']);expect(range.textContent).toBe('Showing 1-1 of 1');search.value='missing';search.listeners.input();expect(list.children[0]).toMatchObject({tag:'p',textContent:'No matching items.',attributes:{role:'status','aria-live':'polite'}});search.value='';search.listeners.input();expect(list.children.map((row:any)=>row.bind.textContent)).toEqual(['Alpha']);
 });
 it('uses declared server search and carries the search term into cursor requests',async()=>{
  const compiled=compile(readFileSync('examples/journal/main.bmec','utf8'),'examples/journal/main.bmec');expect(compiled.diagnostics).toEqual([]);
  const directory=mkdtempSync(join(tmpdir(),'bmec-journal-server-search-'));generate(compiled.ir!,directory);const html=readFileSync(join(directory,'index.html'),'utf8'),match=/<script>([\s\S]*?)<\/script>/.exec(html);expect(match).toBeTruthy();
  const make=(tag:string)=>({tag,dataset:{} as Record<string,string>,attributes:{} as Record<string,string>,children:[] as any[],listeners:{} as Record<string,((event?:unknown)=>void)[]>,appendChild(child:any){this.children.push(child)},replaceChildren(...children:any[]){this.children=children},addEventListener(name:string,handler:(event?:unknown)=>void){(this.listeners[name]??=[]).push(handler)},setAttribute(name:string,value:string){this.attributes[name]=value},removeAttribute(name:string){delete this.attributes[name]}});
  const input:any=make('input');input.value='';const button:any=make('button'),status:any=make('p'),loading:any=make('p'),failure:any=make('p');const template:any={cloneNode(){return {querySelectorAll:()=>[]}}};
  const region:any={querySelector(selector:string){return ({'[data-pipe-list-filter]':input,'[data-pipe-cursor-state="posts"]':button,'[data-pipe-cursor-status="posts"]':status,'[data-pipe-list-loading]':loading,'[data-pipe-list-error]':failure} as Record<string,any>)[selector]}};
  const list:any=make('div');list.dataset={pipeList:'posts',pipeItem:'post',pipeListFilterBy:'title',pipeListLoadingState:'loading',pipeListErrorState:'error'};list.firstElementChild=template;list.closest=()=>region;list.parentElement=region;
  const host:any={dataset:{pipePage:'/articles'},style:{display:''},querySelectorAll:()=>[list]};const document:any={querySelectorAll(selector:string){if(selector==='[data-pipe-page]')return [host];if(selector==='[data-pipe-list]')return [list];return []},createElement:(tag:string)=>make(tag)};
  const timers:Array<()=>Promise<void>>=[];const requests:string[]=[];const context:any={document,globalThis:{PIPE_UI_STATE:{},location:{hash:''},addEventListener(){}},clearTimeout(){},setTimeout(callback:()=>Promise<void>){timers.push(callback);return timers.length},fetch:async(path:string)=>{requests.push(path);const rows=path==='/published-posts'?[{title:'First article',slug:'first-article',published:true}]:path.includes('/pages/')?[{title:'Needle & more next result',slug:'needle-next',published:true}]:[{title:'Needle & more first result',slug:'needle-first',published:true}];return {ok:true,json:async()=>rows}}};
  vm.runInNewContext(match![1]!,context);await new Promise(resolve=>setTimeout(resolve,0));expect(requests).toContain('/published-posts');
  input.value='Needle & more';input.listeners.input!.forEach(handler=>handler());await timers.at(-1)!();expect(requests).toContain('/published-posts/search/Needle%20%26%20more');expect(status.textContent).toBe('1 matching items loaded.');
  await button.onclick();expect(requests.at(-1)).toBe('/published-posts/search/Needle%20%26%20more/pages/needle-first');
  input.value='';input.listeners.input!.forEach(handler=>handler());await timers.at(-1)!();expect(requests.at(-1)).toBe('/published-posts');expect(status.textContent).toBe('Search cleared.');
 });
 it('executes typed source input events from the bundled artifact',()=>{
  const compiled=compile('app Counter\npage Home { event create(id integer) input count integer on create }');
  expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-runtime-')),'release');
  buildRelease(compiled.ir!,directory,{packageName:'counter',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const listeners:Record<string,((event:any)=>void)[]>= {};
  const input:any={value:'7',checked:false,dataset:{pipeEvent:'create',pipeType:'integer',pipeValidation:''},addEventListener(name:string,handler:(event:any)=>void){(listeners[name]??=[]).push(handler)}};
  const document={querySelectorAll(selector:string){if(selector==='[data-pipe-event]')return [input];return [] as any[]}};
  const calls:unknown[]=[];
  vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),{document,PIPE_UI_EVENTS:{create:(value:unknown)=>calls.push(value)}});
  listeners.input!.forEach(handler=>handler({target:input}));
  expect(calls).toEqual([7n]);
  input.value='not-an-integer';listeners.input!.forEach(handler=>handler({target:input}));
  expect(input.dataset.pipeError).toBe('invalid integer');
 });

 it('executes compiled named button events from the bundled artifact',()=>{
  const compiled=compile('app Login\ncomponent Form { button "Save" on Save }\npage Home { when Save is clicked use Form }');
  expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-button-runtime-')),'release');
  buildRelease(compiled.ir!,directory,{packageName:'login',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const listeners:Record<string,(event:any)=>void>={};
  const button:any={dataset:{pipeEvent:'Save'},addEventListener(name:string,handler:(event:any)=>void){listeners[name]=handler}};
  const document={querySelectorAll(selector:string){return selector==='button[data-pipe-event]'?[button]:[]}};
  const calls:unknown[]=[];
  vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),{document,PIPE_UI_EVENTS:{Save:(value:unknown,event:unknown)=>calls.push([value,event])}});
  const event={type:'click'};listeners.click(event);
  expect(calls).toEqual([[undefined,event]]);
 });

 it('gates bundled named button events on semantic form validation',()=>{
  const compiled=compile('app Login\ncomponent Form form { input Email text validate email button "Save" on Save }\npage Home { use Form }');
  expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-form-events-')),'release');
  buildRelease(compiled.ir!,directory,{packageName:'login',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const listeners:Record<string,(event:any)=>void>={};let invalid=true;
  const input:any={dataset:{pipeValidation:'email',pipeError:'expected email'},dispatchEvent(){if(!invalid)delete this.dataset.pipeError},focus(){this.focused=true}};
  const form:any={querySelectorAll:()=>[input]};
  const button:any={dataset:{pipeEvent:'Save'},closest:()=>form,addEventListener(name:string,handler:(event:any)=>void){listeners[name]=handler}};
  const document={querySelectorAll(selector:string){return selector==='button[data-pipe-event]'?[button]:[]}};
  const calls:unknown[]=[];vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),{document,PIPE_UI_EVENTS:{Save:(value:unknown,event:unknown)=>calls.push([value,event])}});
  const first={type:'click',preventDefault(){this.prevented=true}} as any;listeners.click(first);expect(calls).toEqual([]);expect(first.prevented).toBe(true);expect(input.focused).toBe(true);
  invalid=false;const second={type:'click',preventDefault(){}};listeners.click(second);expect(calls).toHaveLength(1);
 });

 it('preserves optional empty validation values in the generated browser bundle',()=>{
  const compiled=compile('app Links\npage Home { input Website text? validate url }');
  expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-optional-validation-')),'release');
  buildRelease(compiled.ir!,directory,{packageName:'links',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const listeners:Record<string,(event:any)=>void>={};
  const message:any={textContent:'initial'};const attributes:any={};const input:any={value:'',dataset:{pipeValidation:'url',pipeOptional:'true'},parentElement:{querySelector:()=>message},setAttribute(name:string,value:string){attributes[name]=value},removeAttribute(name:string){delete attributes[name]},addEventListener(name:string,handler:(event:any)=>void){listeners[name]=handler}};
  const document={querySelectorAll(selector:string){return selector==='[data-pipe-validation]'?[input]:[]}};
  vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),{document,URL});
  listeners.input({target:input});
  expect(input.dataset.pipeError).toBeUndefined();
  expect(message.textContent).toBe('');
  expect(attributes['aria-invalid']).toBe('false');
  input.value='ftp://example.com';listeners.input({target:input});
  expect(input.dataset.pipeError).toBe('expected http(s) URL');
  expect(message.textContent).toBe('expected http(s) URL');
  expect(attributes['aria-invalid']).toBe('true');
 });

 it('executes the generated source-API form path with a typed wire body',async()=>{
  const compiled=compile('app Tasks\nmodel Task { title text required count integer due date done boolean default false ownerAuthId text? }\napi /tasks from Task\npage Home { crud Task excluding ownerAuthId }');
  expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-crud-')),'release');
  buildRelease(compiled.ir!,directory,{packageName:'tasks',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const html=readFileSync(join(directory,'index.html'),'utf8');expect(html).not.toContain('Owner Auth Id');expect(html).toContain('data-pipe-crud-excluded-fields="[&quot;ownerAuthId&quot;]"');expect(html).toContain('type="number" step="1" data-pipe-type="integer"');expect(html).toContain('type="date" data-pipe-type="date"');expect(html).toContain('type="checkbox" data-pipe-type="boolean"');expect(html).toContain('data-pipe-validation="number"');expect(html).toContain('data-pipe-validation="date"');expect(html).toContain('data-pipe-optional="true"');expect(html).toContain('aria-describedby="pipe-crud-Home-Task-title-error"');expect(html).toContain('id="pipe-crud-Home-Task-title-error"');expect(html).toContain('aria-required="true"');expect(html).toContain('class="pipe-field-error" role="alert"');expect(html).toContain('<fieldset><legend>Add Task</legend>');expect(html).toContain('form>fieldset>div{display:grid');expect(html).toContain('form>fieldset>div>label{padding:.7rem');
  const form:any={onsubmit:undefined,reset(){}};const validationInput:any={value:'',dataset:{pipeError:undefined},dispatchEvent(){if(this.value.trim()==='')this.dataset.pipeError='value is required';else delete this.dataset.pipeError},focus(){this.focused=true}};form.querySelectorAll=(selector:string)=>selector==='[data-pipe-validation]'?[validationInput]:[];let rows:any[]=[];let renderedRows='';let editButton:any,deleteButton:any;const tbody:any={set innerHTML(_html:string){renderedRows=_html;const row=rows[0];editButton=row?{dataset:{edit:String(row.id)},onclick:undefined}:undefined;deleteButton=row?{dataset:{delete:String(row.id)},onclick:undefined}:undefined},querySelectorAll(selector:string){return selector.includes('data-edit')?(editButton?[editButton]:[]):(deleteButton?[deleteButton]:[])} };const error:any={textContent:''};const filterInput:any={value:'',listeners:{} as Record<string,()=>void>,addEventListener(name:string,handler:()=>void){this.listeners[name]=handler}};const sortHeader:any={attributes:{} as Record<string,string>,setAttribute(name:string,value:string){this.attributes[name]=value}};const sortButton:any={dataset:{pipeSort:'title'},closest:()=>sortHeader};const table:any={listeners:{} as Record<string,(event:any)=>void>,addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},querySelectorAll:()=>[sortButton]};
  const section:any={dataset:{model:'Task',api:'/tasks',pipeSourceApi:'true',pipeCrudExcludedFields:'["ownerAuthId"]'},querySelector:(selector:string)=>selector==='form'?form:selector==='tbody'?tbody:selector==='table'?table:selector==='[data-pipe-crud-filter]'?filterInput:error};
  const requests:any[]=[];const fetch=async(path:string,init:any={})=>{requests.push({path,init});const method=init.method??'GET';if(method==='GET')return {ok:true,json:async()=>rows};if(method==='POST'){rows=[{id:1,title:'new task',done:true,ownerAuthId:'member'}];return {ok:true,json:async()=>1};}if(method==='PUT'){const body=JSON.parse(init.body);rows=[{...rows[0],title:body.fields.title.value,done:body.fields.done.value,ownerAuthId:body.fields.ownerAuthId.value}];return {ok:true,json:async()=>1};}rows=[];return {ok:true,json:async()=>1};};
  const document={querySelectorAll(selector:string){if(selector==='[data-model]')return [section];return [] as any[]}};
  class FormDataShim{forEach(callback:(value:string,key:string)=>void){callback('new task','title');callback('on','done');}}
  const prompts:string[]=[];const browserContext:any={document,fetch,FormData:FormDataShim,setTimeout,clearTimeout,prompt:(message:string)=>{prompts.push(message);return message.includes('done')?'false':'edited task'}};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),browserContext);
  await new Promise(resolve=>setTimeout(resolve,0));
  expect(requests[0]?.path).toBe('/tasks');
  await form.onsubmit({preventDefault(){}});
  expect(requests.some(request=>request.init.method==='POST')).toBe(false);expect(validationInput.focused).toBe(true);
  validationInput.value='new task';
  await form.onsubmit({preventDefault(){}});
  const post=requests.find(request=>request.init.method==='POST');expect(post).toBeDefined();const wireBody=JSON.parse(post.init.body);
  expect(wireBody).toMatchObject({version:1,kind:'model',type:{name:'Task',symbol:compiled.ir!.models.find(model=>model.name==='Task')!.typeRef!.symbol},fields:{title:{kind:'text',value:'new task'},done:{kind:'boolean',value:true}}});expect(wireBody.fields).not.toHaveProperty('ownerAuthId');await new Promise(resolve=>setTimeout(resolve,0));expect(editButton).toBeDefined();await editButton.onclick({});await new Promise(resolve=>setTimeout(resolve,0));expect(requests.some(request=>request.init.method==='PUT'&&request.path==='/tasks/1')).toBe(true);expect(prompts).not.toContain('Edit ownerAuthId');expect(renderedRows).not.toContain('ownerAuthId');expect(rows[0].title).toBe('edited task');expect(rows[0].done).toBe(false);expect(rows[0].ownerAuthId).toBe('member');filterInput.value='missing';filterInput.listeners.input();expect(renderedRows).toContain('No matching records.');filterInput.value='edited';filterInput.listeners.input();expect(renderedRows).toContain('edited task');table.listeners.click({target:{closest:()=>sortButton}});expect(sortHeader.attributes['aria-sort']).toBe('ascending');table.listeners.click({target:{closest:()=>sortButton}});expect(sortHeader.attributes['aria-sort']).toBe('descending');await deleteButton.onclick({});await new Promise(resolve=>setTimeout(resolve,0));expect(requests.some(request=>request.init.method==='DELETE'&&request.path==='/tasks/1')).toBe(true);expect(rows).toEqual([]);
 });
 it('reuses a persisted idempotency key for retries and rotates it after success',async()=>{
  const compiled=compile('app Shop\ntype CheckoutRequest { quantity integer }\nasync function submit(body CheckoutRequest, idempotencyKey text) -> task<integer> { return 1 }\nhttp POST /orders headers idempotencyKey -> submit\ncomponent Checkout form { input quantity integer label "Quantity" button "Submit" on submit }\npage Store { event submit(quantity integer) sends POST "/orders" with idempotency key use Checkout }');
  expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-idempotency-')),'release');buildRelease(compiled.ir!,directory,{packageName:'checkout',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const data=new Map<string,string>(),store={getItem:(key:string)=>data.get(key)??null,setItem:(key:string,value:string)=>data.set(key,value),removeItem:(key:string)=>data.delete(key)};
  let random=0;const crypto={randomUUID:()=>`request-${++random}`,subtle:webcrypto.subtle};const requests:any[]=[];let first=true;const fetch=async(path:string,init:any)=>{requests.push({path,init});if(first){first=false;return {ok:false,json:async()=>({state:'err',error:'Please retry'})}}return {ok:true,json:async()=>({state:'ok',value:1})};};
  const form:any={elements:{namedItem:()=>({dataset:{}})},closest:undefined};const input:any={value:'2',dataset:{}};const button:any={dataset:{pipeEvent:'submit',pipeAction:JSON.stringify({method:'POST',path:'/orders',idempotencyKey:true,fields:{quantity:'integer'}})},disabled:false,nextElementSibling:{dataset:{pipeActionStatus:'submit'},textContent:'',setAttribute(){}},closest:(selector:string)=>selector==='form'?form:undefined};let click:(event:any)=>void=()=>{};button.addEventListener=(name:string,handler:(event:any)=>void)=>{if(name==='click')click=handler;};form.querySelectorAll=()=>[];
  class FormDataShim{*[Symbol.iterator](){yield ['quantity','2'] as [string,string]}}
  const document={querySelectorAll:(selector:string)=>selector==='button[data-pipe-event]'?[button]:[]};
  const browser:any={document,fetch,FormData:FormDataShim,crypto,TextEncoder,localStorage:store,location:{pathname:'/store'},setTimeout,clearTimeout};vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),browser);
  await click({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,0));const firstKey=requests[0]!.init.headers.idempotencyKey;expect(firstKey).toBe('request-1');expect(button.dataset.pipeError).toBe('request failed');expect(button.nextElementSibling.textContent).toBe('Please retry');expect(JSON.stringify([...data.values()])).not.toContain('"quantity":"2"');
  await click({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,0));expect(requests[1]!.init.headers.idempotencyKey).toBe(firstKey);
  await click({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,0));expect(requests[2]!.init.headers.idempotencyKey).toBe('request-2');
 });
 it('renders exact money fields in generated model tables as decimal text',async()=>{
  const compiled=compile('app Ledger\nmodel Entry { amount money }\npage Home { crud Entry }');expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-money-')),'release');buildRelease(compiled.ir!,directory,{packageName:'ledger',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  let tableMarkup='';const tbody:any={set innerHTML(value:string){tableMarkup=value},querySelectorAll(){return []}};const form:any={onsubmit:undefined,reset(){},querySelectorAll(){return []}};const error:any={textContent:''};const filterInput:any={value:'',addEventListener(){}};const table:any={addEventListener(){},querySelectorAll(){return []}};
  const section:any={dataset:{model:'Entry',api:'/api/Entry'},querySelector:(selector:string)=>selector==='form'?form:selector==='tbody'?tbody:selector==='table'?table:selector==='[data-pipe-crud-filter]'?filterInput:error};
  const rows=[{id:1,amount:{minor:'1234',scale:2}},{id:2,amount:{minor:'-5',scale:2}},{id:3,amount:{minor:'9223372036854775807',scale:2}}];
  const fetch=async()=>({ok:true,json:async()=>rows});const document={querySelectorAll:(selector:string)=>selector==='[data-model]'?[section]:[]};
  vm.runInNewContext(readFileSync(join(directory,'app.js'),'utf8'),{document,fetch,FormData:class {},setTimeout,clearTimeout});
  await new Promise(resolve=>setTimeout(resolve,0));
  expect(tableMarkup).toContain('<td>12.34</td>');expect(tableMarkup).toContain('<td>-0.05</td>');expect(tableMarkup).toContain('<td>92233720368547758.07</td>');expect(tableMarkup).not.toContain('[object Object]');
 });
 it('uses a restrained action hierarchy for generated CRUD controls',()=>{const compiled=compile('app Reports\nmodel Report { title text required }\npage Home { crud Report }');expect(compiled.diagnostics).toEqual([]);const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-action-hierarchy-')),'release');buildRelease(compiled.ir!,directory,{packageName:'reports',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});const html=readFileSync(join(directory,'index.html'),'utf8'),script=readFileSync(join(directory,'app.js'),'utf8');expect(html).toContain('class="pipe-primary"');expect(html).toContain('.pipe-danger:hover{background:#fef2f2}');expect(script).toContain('pipe-secondary');expect(script).toContain('pipe-danger');});
 it('wraps generated tables in a keyboard-focusable responsive viewport',()=>{
  const compiled=compile('app Reports\nmodel Record { title text required notes text }\npage Home { crud Record }');expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-table-')),'release');buildRelease(compiled.ir!,directory,{packageName:'reports',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const html=readFileSync(join(directory,'index.html'),'utf8');expect(html).toContain('<div class="pipe-table-wrap" role="region"');expect(html).toContain('tabindex="0"');expect(html).toContain('overflow-x:auto');
 });
 it('labels generated CRUD actions with their model and record context',()=>{
  const compiled=compile('app Reports\nmodel Record { title text required }\npage Home { crud Record }');expect(compiled.diagnostics).toEqual([]);
  const directory=join(mkdtempSync(join(tmpdir(),'pipe-browser-actions-')),'release');buildRelease(compiled.ir!,directory,{packageName:'reports',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
  const script=readFileSync(join(directory,'app.js'),'utf8');expect(script).toContain('aria-label');expect(script).toContain('Edit ');expect(script).toContain('Delete ');
 });
});
