import {describe,expect,it} from 'vitest';
import {formatSource} from '../src/tooling/formatter.js';

it('formats controlled-English bound-field children canonically',()=>{const source='app Tasks\ncomponent Row {\nshow task name\n}\npage Home {\nstate tasks list<text>\nfor each task in tasks show Row\n}\n';const formatted=formatSource(source);expect(formatted).toContain('  show task name\n');expect(formatSource(formatted)).toBe(formatted);});
import {parse} from '../src/parser/parser.js';

describe('PIPE formatter',()=>{it('is deterministic, idempotent, and reparsable',()=>{const source='type User { name text } function main(u User) -> text { return u.name }';const formatted=formatSource(source);expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted.pipe')).not.toThrow();});});
it('keeps built-in generic type arguments visually attached and reparsable',()=>{const source='function f(values list<result<integer, text>>, fs capability<filesystem>) -> task<result<list<text>, text>> { return ready() }';const formatted=formatSource(source);expect(formatted).toContain('list<result<integer, text>>');expect(formatted).toContain('capability<filesystem>');expect(formatted).toContain('task<result<list<text>, text>>');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'generic-types.bmec')).not.toThrow();});
it('keeps a space between a generic type and its assignment operator',()=>{const source='type Attendee { name text age integer } function decode(source text) -> result<list<Attendee>,text> { let records result<list<Attendee>,text> = decodeJson(source) return records }';const formatted=formatSource(source);expect(formatted).toContain('result<list<Attendee>, text> = decodeJson(source)');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'generic-assignment.bmec')).not.toThrow();});
it('preserves supported local-binding spellings without changing their syntax',()=>{const source='function equalsForm() -> integer { let answer = 42 return answer } function isForm() -> integer { let answer is 42 return answer } function beForm() -> integer { let answer be 42 return answer }';const formatted=formatSource(source);expect(formatted).toContain('let answer = 42');expect(formatted).toContain('let answer is 42');expect(formatted).toContain('let answer be 42');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'binding-spellings.bmec')).not.toThrow();});
it('keeps spaces around comparison operators',()=>{const formatted=formatSource('function before(left integer, right integer) -> boolean { return left < right }');expect(formatted).toContain('left < right');expect(()=>parse(formatted,'comparison-format.bmec')).not.toThrow();});
it('formats controlled-English API and CRUD declarations canonically',()=>{const source='app Store\nmodel Task { title text required }\napi /tasks from Task requiring authenticated\npage Home { crud Task }';const formatted=formatSource(source);expect(formatted).toContain('api / tasks from Task requiring authenticated');expect(formatted).toContain('crud Task');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'controlled-api.bmec')).not.toThrow();});
describe('typed style formatting',()=>{it('preserves composable layout and alignment modifiers',()=>{const formatted=formatSource('app Demo\nstyle named Dashboard layout is column alignment is center');expect(formatted).toContain('layout is column alignment is center');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted-style.pipe')).not.toThrow();});});
describe('brace-delimited style formatting',()=>{it('keeps style blocks reparsable and idempotent',()=>{const formatted=formatSource('app Demo\nstyle named Card { layout is column alignment is center padding is 12 }');expect(formatted).toContain('style named Card {');expect(formatted).toContain('layout is column alignment is center padding is 12');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted-style-block.pipe')).not.toThrow();});});
describe('nested style state formatting',()=>{it('keeps controlled-English state blocks reparsable',()=>{const formatted=formatSource('app Demo\nstyle named Card { when hovered { background is blue } }');expect(formatted).toContain('when hovered');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted-style-state.pipe')).not.toThrow();});});
describe('focus-ring style formatting',()=>{it('keeps readable focus syntax idempotent',()=>{const formatted=formatSource('app Demo\nstyle named Card { when focused { show focus ring } }');expect(formatted).toContain('show focus ring');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted-style-focus.pipe')).not.toThrow();});});
describe('responsive style formatting',()=>{it('keeps readable small-screen syntax idempotent',()=>{const formatted=formatSource('app Demo\nstyle named Grid { on small screens { columns is 1 } }');expect(formatted).toContain('on small screens');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted-style-responsive.pipe')).not.toThrow();});});
it('handles repeated tokens by position',()=>{const formatted=formatSource('function f(a integer, b integer) -> integer { return a + b }');expect(formatSource(formatted)).toBe(formatted);});
it('preserves typed source HTTP header clauses through formatting',()=>{const source='app Secure\nfunction read(token text) -> text { return token }\nhttp GET /secure headers token -> read';const formatted=formatSource(source);expect(formatted).toContain('headers token -> read');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted-http-headers.pipe')).not.toThrow();});
it('preserves explicit page-action idempotency through formatting',()=>{const source='app Shop\ntype Input { quantity integer }\ncomponent Form form { input quantity integer button "Submit" on submit }\npage Store { event submit(quantity integer) sends POST "/orders" with idempotency key use Form }';const formatted=formatSource(source);expect(formatted).toContain('sends POST "/orders" with idempotency key');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted-idempotency.bmec')).not.toThrow();});
it('preserves typed page quantity updates and derived totals through formatting',()=>{const source='app Shop\nmodel CartLine { price integer quantity integer }\ncomponent Row { button "More" on more with line from line }\ncomponent Summary { show total of cart by price times quantity }\npage Cart { event more(line CartLine) increases quantity of line in cart state cart list<CartLine> for each line in cart show Row use Summary }';const formatted=formatSource(source);expect(formatted).toContain('increases quantity of line in cart');expect(formatted).toContain('show total of cart by price times quantity');expect(formatSource(formatted)).toBe(formatted);expect(()=>parse(formatted,'formatted-page-total.bmec')).not.toThrow();});
it('preserves hash and slash comments while remaining reparsable',()=>{const source='# file header\napp Demo\nmodel Item { # field note\n name text // trailing note\n}\n// final note\n';const formatted=formatSource(source);expect(formatted).toContain('# file header');expect(formatted).toContain('# field note');expect(formatted).toContain('// trailing note');expect(formatted).toContain('// final note');expect(parse(formatted,'comments.pipe').declarations.map(x=>x.kind)).toEqual(['AppDeclaration','ModelDeclaration']);expect(formatSource(formatted)).toBe(formatted);});
