import {describe,expect,it} from 'vitest';
import {compile} from '../src/compiler.js';
import {executeValue,ListValue,Money,PIPE_NONE,RecordValue,ResultValue,VariantValue} from '../src/core/interpreter.js';

describe('higher-order list operations',()=>{
  it('maps and filters through typed closures',()=>{const r=compile('function main() -> list<integer> { let xs = [1, 2, 3] let ys = map(xs, lambda(x integer) -> integer { return x + 1 }) return filter(ys, lambda(x integer) -> boolean { return x > 2 }) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toEqual(new ListValue([3n,4n]))});
  it('folds state and finds values',()=>{const r=compile('function main() -> integer { let xs = [1, 2, 3] let total = fold(xs, 0, lambda(acc integer, x integer) -> integer { return acc + x }) return total }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toBe(6n)});
  it('supports any and all predicates',()=>{const r=compile('function main() -> boolean { let xs = [1, 2, 3] return any(xs, lambda(x integer) -> boolean { return x == 2 }) and all(xs, lambda(x integer) -> boolean { return x > 0 }) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toBe(true)});
  it('returns none when find has no match',()=>{const r=compile('function main() -> integer? { return find([1, 2], lambda(x integer) -> boolean { return x == 9 }) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toBe(PIPE_NONE)});
  it('rejects invalid higher-order callback types',()=>{const r=compile('function main() -> list<integer> { return map([1, 2], lambda(x integer) -> text { return "x" }) }');expect(r.diagnostics.some(x=>x.code==='PIPE-FUNC-009'||x.code==='PIPE-FUNC-006')).toBe(true)});
  it('accepts named and captured callbacks with exact values',()=>{const r=compile('function inc(x integer) -> integer { return x + 1 } function make(delta integer) -> (integer) -> integer { return lambda(x integer) -> integer { return x + delta } } function main() -> list<integer> { let xs = map([1, 2], inc) let add = make(10) return map(xs, add) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toEqual(new ListValue([12n,13n]))});
  it('applies recursion and step limits through callbacks',()=>{const r=compile('function loop(x integer) -> integer { return loop(x) } function main() -> list<integer> { return map([1], loop) }');expect(r.diagnostics).toEqual([]);expect(()=>executeValue(r.ir!.functions,'main',[],{maxCallDepth:4})).toThrow(/Maximum call depth exceeded/)});
  it('preserves exact money through callbacks and handles empty lists',()=>{const r=compile('function add(x money) -> money { return x + 0.01 } function main() -> list<money> { let empty list<money> = [] let unused = map(empty, add) let prices list<money> = [0.01, 0.02] return map(prices, add) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toEqual(new ListValue([new Money(2n),new Money(3n)]))});
  it('defines empty-list results precisely for every higher-order operation',()=>{const r=compile('function mapped() -> list<integer> { let xs list<integer> = [] return map(xs, lambda(x integer) -> integer { return x + 1 }) } function filtered() -> list<integer> { let xs list<integer> = [] return filter(xs, lambda(x integer) -> boolean { return true }) } function folded() -> integer { let xs list<integer> = [] return fold(xs, 7, lambda(a integer, x integer) -> integer { return a + x }) } function found() -> integer? { let xs list<integer> = [] return find(xs, lambda(x integer) -> boolean { return true }) } function anyEmpty() -> boolean { let xs list<integer> = [] return any(xs, lambda(x integer) -> boolean { return true }) } function allEmpty() -> boolean { let xs list<integer> = [] return all(xs, lambda(x integer) -> boolean { return false }) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'mapped',[])).toEqual(new ListValue([]));expect(executeValue(r.ir!.functions,'filtered',[])).toEqual(new ListValue([]));expect(executeValue(r.ir!.functions,'folded',[])).toBe(7n);expect(executeValue(r.ir!.functions,'found',[])).toBe(PIPE_NONE);expect(executeValue(r.ir!.functions,'anyEmpty',[])).toBe(false);expect(executeValue(r.ir!.functions,'allEmpty',[])).toBe(true)});
  it('distinguishes callback arity, parameter type, and return type diagnostics',()=>{expect(compile('function main() -> list<integer> { return map([1], lambda(a integer, b integer) -> integer { return a }) }').diagnostics.map(x=>x.code)).toContain('PIPE-FUNC-008');expect(compile('function main() -> list<integer> { return map([1], lambda(a text) -> integer { return 1 }) }').diagnostics.map(x=>x.code)).toContain('PIPE-FUNC-009');expect(compile('function main() -> list<integer> { return filter([1], lambda(a integer) -> integer { return a }) }').diagnostics.map(x=>x.code)).toContain('PIPE-FUNC-009')});
  it('preserves exact enum, record, Result, and money values through callbacks',()=>{const records=compile('type User { name text } function main() -> list<User> { return map([User { name: "Ada" }], lambda(u User) -> User { return u }) }');expect(records.diagnostics).toEqual([]);expect((executeValue(records.ir!.functions,'main',[]) as ListValue).items[0]).toBeInstanceOf(RecordValue);const states=compile('enum State { Ready Busy } function main(state State) -> State? { return find([state], lambda(s State) -> boolean { return true }) }');expect(states.diagnostics).toEqual([]);expect(executeValue(states.ir!.functions,'main',[new VariantValue('State','Busy')])).toEqual(new VariantValue('State','Busy'));const prices=compile('function main() -> list<money> { let xs list<money> = [0.01, 0.02] return map(xs, lambda(x money) -> money { return x + 0.01 }) }');expect(prices.diagnostics).toEqual([]);expect(executeValue(prices.ir!.functions,'main',[])).toEqual(new ListValue([new Money(2n),new Money(3n)]));const results=compile('function main() -> list<result<integer,text>> { let xs list<result<integer,text>> = [ok(1), err("bad")] return map(xs, lambda(x result<integer,text>) -> result<integer,text> { return x }) }');expect(results.diagnostics).toEqual([]);expect(executeValue(results.ir!.functions,'main',[])).toEqual(new ListValue([new ResultValue('ok',1n),new ResultValue('err','bad')]))});
  it('composes filter, map, and fold with captures',()=>{const r=compile('function main() -> integer { let cutoff = 1 let selected = filter([1, 2, 3], lambda(x integer) -> boolean { return x > cutoff }) let shifted = map(selected, lambda(x integer) -> integer { return x + cutoff }) return fold(shifted, 0, lambda(acc integer, x integer) -> integer { return acc + x }) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toBe(7n)});
});
