import {describe,expect,it} from 'vitest';
import {compile} from '../src/compiler.js';
import {executeValue,FunctionValue,ListValue,Money,NoneValue,ResultValue,VariantValue} from '../src/core/interpreter.js';

describe('typed lambdas and lexical closures',()=>{
  it('parses, types, lowers, and calls a lambda value',()=>{const r=compile('function main() -> integer { let add = lambda(x integer) -> integer { return x + 1 } return add(4) }');expect(r.diagnostics).toEqual([]);expect(r.ast.declarations[0].kind).toBe('FunctionDeclaration');expect(r.ir!.functions[0].body[0].value.kind).toBe('lambda');expect(executeValue(r.ir!.functions,'main',[])).toBe(5n)});
  it('captures only referenced outer values and survives the outer return',()=>{const r=compile('function make(x integer, unused integer) -> (integer) -> integer { return lambda(y integer) -> integer { return x + y } } function main() -> integer { let f = make(3, 99) return f(4) }');expect(r.diagnostics).toEqual([]);const lambda=r.ir!.functions[0].body[0].value;expect(lambda.captures).toEqual(['x']);expect(executeValue(r.ir!.functions,'main',[])).toBe(7n)});
  it('supports nested closures and shadowed parameters',()=>{const r=compile('function make(x integer) -> (integer) -> integer { let outer = lambda(x integer) -> integer { let inner = lambda(y integer) -> integer { return x + y } return inner(2) } return outer } function main() -> integer { let f = make(8) return f(4) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toBe(6n)});
  it('rejects lambda argument, arity, and unresolved-name errors',()=>{const r=compile('function main() -> integer { let f = lambda(x text) -> integer { return missing } return f(1, 2) }');expect(r.diagnostics.map(x=>x.code)).toEqual(expect.arrayContaining(['PIPE-REF-004','PIPE-FUNC-008','PIPE-FUNC-009']))});
  it('rejects wrong lambda returns and calls through non-functions',()=>{const r=compile('function main() -> integer { let f = lambda() -> text { return 1 } let x = 1 return x(2) }');expect(r.diagnostics.map(x=>x.code)).toEqual(expect.arrayContaining(['PIPE-FUNC-006','PIPE-FUNC-007']))});
  it('keeps closures as PIPE FunctionValue instances',()=>{const r=compile('function main() -> (integer) -> integer { return lambda(x integer) -> integer { return x } }');expect(executeValue(r.ir!.functions,'main',[])).toBeInstanceOf(FunctionValue)});
  it('captures in lexical order and keeps invocation captures independent',()=>{const r=compile('function make(a integer, b integer) -> (integer) -> integer { return lambda(x integer) -> integer { return a + b + x } } function main() -> integer { let left = make(1, 2) let right = make(10, 20) return left(0) + right(0) }');expect(r.diagnostics).toEqual([]);expect(r.ir!.functions[0].body[0].value?.captures).toEqual(['a','b']);expect(executeValue(r.ir!.functions,'main',[])).toBe(33n)});
  it('types closures over optional, list, record, Result, enum, and function values',()=>{const source='type User { name text } enum State { Ready Busy } function apply(f (integer) -> integer, x integer) -> integer { return f(x) } function make(user User, state State, result result<integer,text>, xs list<integer>) -> (integer) -> integer { return lambda(x integer) -> integer { return apply(lambda(y integer) -> integer { return x + y }, 1) } } function main() -> integer? { let f = lambda(x integer?) -> integer? { return x } return f(none) }';const r=compile(source);expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toBeInstanceOf(NoneValue)});
  it('applies call-depth and step limits to indirect lambda calls',()=>{const r=compile('function main() -> integer { let f = lambda(x integer) -> integer { return x + 1 } return f(1) }');expect(r.diagnostics).toEqual([]);expect(()=>executeValue(r.ir!.functions,'main',[],{maxSteps:1})).toThrow(/Maximum execution steps exceeded/);expect(()=>executeValue(r.ir!.functions,'main',[],{maxCallDepth:1})).toThrow(/Maximum call depth exceeded/)});
});
