import {describe,expect,it} from 'vitest';
import {mkdtempSync,writeFileSync,readFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {inspectPackageGraph,readManifest,verifyLock,writeLock} from '../src/project/manifest.js';

describe('PIPE project manifest',()=>{it('reads and deterministically locks local dependencies',()=>{const root=mkdtempSync(join(tmpdir(),'pipe-package-'));const file=join(root,'pipe.toml');mkdirSync(join(root,'alpha'));writeFileSync(join(root,'alpha','pipe.toml'),'dependency = true');writeFileSync(file,'[package]\nname = "demo"\nversion = "1.0.0"\nlanguage = "0.1-alpha"\nentry = "src/main.pipe"\n\n[dependencies]\nzeta = "../zeta"\nalpha = "./alpha"\n');const manifest=readManifest(file);expect(manifest.dependencies.map(x=>x.name)).toEqual(['alpha','zeta']);const lock=writeLock(file);expect(lock.dependencies[0].path).toBe('alpha');expect(lock.dependencies[0].integrity).toMatch(/^sha256-/);expect(verifyLock(file,lock)).toEqual([]);expect(JSON.parse(readFileSync(join(root,'pipe.lock'),'utf8')).version).toBe(1);});it('rejects stale, extra, or retargeted lock entries',()=>{const root=mkdtempSync(join(tmpdir(),'pipe-package-'));const file=join(root,'pipe.toml');mkdirSync(join(root,'alpha'));writeFileSync(join(root,'alpha','pipe.toml'),'dependency = true');writeFileSync(file,'[package]\nname = "demo"\nversion = "1.0.0"\nlanguage = "0.1-alpha"\nentry = "main.pipe"\n[dependencies]\nalpha = "./alpha"\n');const lock=writeLock(file);lock.dependencies[0]!.path='other';lock.dependencies.push({name:'extra',path:'extra'});expect(verifyLock(file,lock).map(x=>x.split(':')[0])).toEqual(expect.arrayContaining(['PIPE-PKG-005','PIPE-PKG-007']));});it('rejects malformed or duplicate dependencies',()=>{const root=mkdtempSync(join(tmpdir(),'pipe-package-'));const file=join(root,'pipe.toml');writeFileSync(file,'[package]\nname = "demo"\nversion = "1"\nlanguage = "0.1-alpha"\nentry = "main.pipe"\n[dependencies]\n"bad name" = "./dep"\n');expect(()=>readManifest(file)).toThrow('PIPE-PKG-002');writeFileSync(file,'[package]\nname = "demo"\nversion = "1"\nlanguage = "0.1-alpha"\nentry = "../main.pipe"\n');expect(()=>readManifest(file)).toThrow('PIPE-PKG-002');});});
it('uses locale-independent code-point ordering for dependency names',()=>{const root=mkdtempSync(join(tmpdir(),'pipe-package-order-'));const file=join(root,'pipe.toml');writeFileSync(file,'[package]\nname = "demo"\nversion = "1"\nlanguage = "0.1-alpha"\nentry = "main.pipe"\n[dependencies]\nzeta = "1.0.0"\nalpha = "1.0.0"\nZeta = "1.0.0"\n');expect(readManifest(file).dependencies.map(x=>x.name)).toEqual(['Zeta','alpha','zeta']);});
it('accepts the BMEC 0.1 language version',()=>{const root=mkdtempSync(join(tmpdir(),'bmec-package-'));const file=join(root,'bmec.toml');writeFileSync(file,'[package]\nname = "demo"\nversion = "0.1.0"\nlanguage = "0.1"\nentry = "main.bmec"\n');expect(readManifest(file).language).toBe('0.1');});
it('projects transitive package nodes and reports missing or cyclic edges',()=>{const root=mkdtempSync(join(tmpdir(),'bmec-package-'));const child=join(root,'child');const leaf=join(child,'leaf');mkdirSync(leaf,{recursive:true});const write=(file:string,name:string,dependency?:string)=>writeFileSync(file,`[package]\nname = "${name}"\nversion = "1.0.0"\nlanguage = "0.1"\nentry = "main.bmec"\n${dependency?`\n[dependencies]\n${dependency}`:''}\n`);writeFileSync(join(root,'main.bmec'),'app Root\n');writeFileSync(join(child,'main.bmec'),'app Child\n');writeFileSync(join(leaf,'main.bmec'),'app Leaf\n');write(join(root,'bmec.toml'),'root','child = "./child"');write(join(child,'bmec.toml'),'child','leaf = "./leaf"');write(join(leaf,'bmec.toml'),'leaf');const graph=inspectPackageGraph(join(root,'bmec.toml'));expect(graph.nodes.map(node=>node.id)).toEqual(['PKG-child@1.0.0','PKG-leaf@1.0.0','PKG-root@1.0.0']);expect(graph.edges).toEqual(expect.arrayContaining([expect.objectContaining({from:'PKG-root@1.0.0',to:'PKG-child@1.0.0',name:'child',kind:'local'}),expect.objectContaining({from:'PKG-child@1.0.0',to:'PKG-leaf@1.0.0',name:'leaf',kind:'local'})]));expect(graph.issues).toEqual([]);write(join(leaf,'bmec.toml'),'leaf','root = ".."');expect(inspectPackageGraph(join(root,'bmec.toml')).issues.map(issue=>issue.code)).toContain('PIPE-PKG-013');write(join(child,'bmec.toml'),'child','missing = "./missing"');expect(inspectPackageGraph(join(root,'bmec.toml')).issues.map(issue=>issue.code)).toContain('PIPE-PKG-011');});
it('rejects unknown language versions',()=>{const root=mkdtempSync(join(tmpdir(),'bmec-package-version-'));const file=join(root,'bmec.toml');writeFileSync(file,'[package]\nname = "demo"\nversion = "0.1.0"\nlanguage = "9.9"\nentry = "main.bmec"\n');expect(()=>readManifest(file)).toThrow('PIPE-PKG-014');});
