import {describe,it,expect} from 'vitest';
import Database from 'better-sqlite3';
import {migrate,MigrationError} from '../src/runtime/migration.js';
import type {ProjectIR} from '../src/ir/ir.js';

const ir=(fields:ProjectIR['models'][number]['fields'][],name='Task'):ProjectIR=>({version:'0.1-alpha',app:{id:'APP-001',name:'X'},models:[{id:'DB-001',name,fields}],pages:[],apis:[],functions:[]});
const field=(name:string,type:string,extra:Partial<ProjectIR['models'][number]['fields'][number]>={}):ProjectIR['models'][number]['fields'][number]=>({id:`FIELD-${name}`,name,type,required:false,unique:false,...extra});
describe('migration safety audit',()=>{
  it('rejects malformed canonical DB schema before opening migration DDL',()=>{const db=new Database(':memory:');const broken=ir([field('title','text')]);broken.db={version:1,models:[{id:'DB-001',name:'Task',fields:[]}]};expect(()=>migrate(db,broken)).toThrow('Invalid canonical database schema');expect((db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='_pipe_migrations'").get())).toBeUndefined();db.close()});
  it('rolls back earlier additions when a later change is unsafe',()=>{const db=new Database(':memory:');migrate(db,ir([field('title','text') ]));db.prepare('insert into pipe_Task (title) values (?)').run('old');const before=db.prepare("select sql from sqlite_master where name='pipe_Task'").get() as {sql:string};expect(()=>migrate(db,ir([field('title','text'),field('done','boolean',{default:false}),field('title2','integer',{required:true})]))).toThrow(MigrationError);const after=db.prepare("select sql from sqlite_master where name='pipe_Task'").get() as {sql:string};expect(after.sql).toBe(before.sql);expect((db.prepare('select count(*) n from pipe_Task').get() as {n:number}).n).toBe(1);db.close()});
  it('keeps migration history consistent after rollback',()=>{const db=new Database(':memory:');migrate(db,ir([field('title','text')]));expect(()=>migrate(db,ir([field('title','integer'),field('extra','text')]))).toThrow(MigrationError);expect((db.prepare('select count(*) n from _pipe_migrations').get() as {n:number}).n).toBe(1);db.close()});
  it('applies defaults to existing rows for additive fields',()=>{const db=new Database(':memory:');migrate(db,ir([field('title','text')]));db.prepare('insert into pipe_Task (title) values (?)').run('old');migrate(db,ir([field('title','text'),field('done','boolean',{default:false})]));expect((db.prepare('select done from pipe_Task').get() as {done:number}).done).toBe(0);db.close()});
  it('creates declared SQLite indexes once and records migration status',()=>{const db=new Database(':memory:'),project=ir([field('title','text'),field('status','text')]);project.db={version:1,models:[{id:'DB-001',name:'Task',fields:[{id:'FIELD-id',name:'id',type:{kind:'primitive',name:'integer'},required:true,primaryKey:true},{id:'FIELD-title',name:'title',type:{kind:'primitive',name:'text'}},{id:'FIELD-status',name:'status',type:{kind:'primitive',name:'text'}}],indexes:[{name:'task_status',fields:['status']}]}]};migrate(db,project);migrate(db,project);expect((db.prepare('PRAGMA index_info("task_status")').all() as Array<{name:string}>).map(row=>row.name)).toEqual(['status']);expect((db.prepare('select count(*) n from _pipe_migrations').get() as {n:number}).n).toBe(1);db.close()});
  it('rejects silent constraint drift',()=>{const db=new Database(':memory:');migrate(db,ir([field('title','text',{default:'old'})]));expect(()=>migrate(db,ir([field('title','text',{default:'new'})]))).toThrow(MigrationError);db.close()});
  it('refuses removals even when a table is empty',()=>{const db=new Database(':memory:');migrate(db,ir([field('title','text')]));expect(()=>migrate(db,ir([]))).toThrow(MigrationError);db.close()});
});
