import {describe,it,expect} from 'vitest';
import {mkdtempSync,writeFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {compileProject} from '../src/compiler.js';
import {executeValue} from '../src/core/interpreter.js';

function project(files:Record<string,string>,raw=false){const root=mkdtempSync(join(tmpdir(),'pipe-modules-'));for(const [name,source] of Object.entries(files)){const file=join(root,name);const dir=file.slice(0,file.lastIndexOf('\\'));mkdirSync(dir,{recursive:true});const exported=!raw&&name!=='main.pipe'?source.replace(/(^|\n|}\s+)(?=(model|type|enum|function|interface)\b)/g,'$1public '):source;writeFileSync(file,exported)}return join(root,'main.pipe')}

describe('PIPE static modules',()=>{
 it('accepts explicit built-in standard-library module imports',()=>{const entry=project({'main.pipe':'import { trim } from "std.text"\nfunction main(value text) -> text { return trim(value) }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',['  Ada  '])).toBe('Ada')});
 it('rejects private declarations imported from an ordinary module with repair context',()=>{const entry=project({'main.pipe':'import { hidden } from "./lib.pipe"\nfunction main() -> integer { return hidden() }','lib.pipe':'function hidden() -> integer { return 1 }'},true);const diagnostic=compileProject(entry).diagnostics.find(item=>item.code==='PIPE-MOD-007');expect(diagnostic).toMatchObject({kind:'missing_export',suggestions:[expect.stringContaining('public')],repair:{type:'visibility',value:expect.stringContaining('hidden')},related:[{message:expect.stringContaining('lib.pipe'),span:{start:{file:expect.stringContaining('lib.pipe')}}}]});});
 it('regresses the non-transitive symbol leak with an exact import repair',()=>{const entry=project({'main.pipe':'import { Something } from "./b.pipe"\napp X\npage Home { crud SecretThing }','b.pipe':'import { SecretThing } from "./c.pipe"\nmodel Something {}','c.pipe':'model SecretThing { name text }'});const diagnostic=compileProject(entry).diagnostics.find(item=>item.code==='PIPE-MOD-010');expect(diagnostic).toMatchObject({repair:{type:'import',value:'Import SecretThing from "./c.pipe" before use'},related:[{message:expect.stringContaining('c.pipe')}]});});
 it('rejects an external symbol when the entry module has no import',()=>{const entry=project({'main.pipe':'app X\npage Home { crud Product }','models.pipe':'model Product {}'});const r=compileProject(entry);expect(r.diagnostics.map(d=>d.code)).toContain('PIPE-REF-001');});
 it('resolves named imports transitively and records a deterministic graph',()=>{const entry=project({'main.pipe':'import { User } from "./models.pipe"\nimport { add } from "./math.pipe"\napp X\npage Home { crud User }','models.pipe':'model User { name text }','math.pipe':'function add(a integer, b integer) -> integer { return a + b }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);expect(r.modules.map(m=>m.id)).toEqual(['MOD-001','MOD-002','MOD-003']);expect(r.ir?.modules?.map(m=>m.file)).toHaveLength(3);});
 it('reports missing modules, symbols, collisions, and cycles',()=>{const missing=project({'main.pipe':'import { Nope } from "./missing.pipe"\napp X'});expect(compileProject(missing).diagnostics.map(d=>d.code)).toContain('PIPE-MOD-004');const symbol=project({'main.pipe':'import { Nope } from "./models.pipe"\napp X','models.pipe':'model User {}'});expect(compileProject(symbol).diagnostics.map(d=>d.code)).toContain('PIPE-MOD-007');const cycle=project({'main.pipe':'import { B } from "./b.pipe"\napp X','b.pipe':'import { A } from "./main.pipe"\nmodel B {}'});expect(compileProject(cycle).diagnostics.map(d=>d.code)).toContain('PIPE-MOD-005');});
  it('enforces project-root boundaries and mandatory extension',()=>{const entry=project({'main.pipe':'import { X } from "../outside.pipe"\napp X'});expect(compileProject(entry).diagnostics.map(d=>d.code)).toContain('PIPE-MOD-003');});
  it('reports undeclared package imports without filesystem exceptions',()=>{const entry=project({'main.pipe':'import { X } from "missing/lib.pipe"\napp X'});expect(compileProject(entry).diagnostics.map(d=>d.code)).toContain('PIPE-MOD-001');});
  it('supports directly imported functions and keeps canonical modules singular',()=>{const entry=project({'main.pipe':'import { add } from "./math.pipe"\nfunction main() -> integer { return add(2, 3) }','math.pipe':'function add(a integer, b integer) -> integer { return a + b }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'main',[])).toBe(5n);const same=project({'main.pipe':'import { Product } from "./models.pipe"\nimport { Product } from "./nested/../models.pipe"\npage Home { crud Product }','models.pipe':'model Product {}'});const duplicate=compileProject(same);expect(duplicate.modules).toHaveLength(2);expect(duplicate.diagnostics.map(d=>d.code)).toContain('PIPE-MOD-009');});
  it('keeps same-named functions in separate modules distinct by FunctionId',()=>{const entry=project({'main.pipe':'import { add } from "./math.pipe"\nimport { helper } from "./other.pipe"\nfunction main() -> integer { return add(helper(2), 3) }','math.pipe':'function add(a integer, b integer) -> integer { return a + b }','other.pipe':'function add(a integer, b integer) -> integer { return a - b } function helper(x integer) -> integer { return add(x, 1) }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);const ids=r.ir!.functions.map(f=>String(f.id));expect(new Set(ids).size).toBe(ids.length);expect(executeValue(r.ir!.functions,'main',[])).toBe(4n);const adds=r.ir!.functions.filter(f=>f.name==='add');expect(adds).toHaveLength(2);expect(adds[0].id).not.toBe(adds[1].id);});
  it('rejects local/import collisions',()=>{const entry=project({'main.pipe':'import { Product } from "./models.pipe"\nmodel Product {}','models.pipe':'model Product {}'});expect(compileProject(entry).diagnostics.map(d=>d.code)).toContain('PIPE-MOD-008');});
  it('keeps imported record types visible through list signatures',()=>{const entry=project({'main.pipe':'import { UserProfile } from "./types.pipe"\nfunction firstName(users list<UserProfile>) -> text { let first = users[0] if first != none { return first.name } else { return "none" } }','types.pipe':'type UserProfile { name text nickname text? }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);expect(r.ir?.functions[0].parameters[0].type).toBe('list<UserProfile>');});
  it('resolves an imported interface to a local concrete implementation canonically',()=>{const entry=project({'main.pipe':'import { Printable } from "./iface.pipe"\ntype User { name text }\nimpl Printable for User { function print(self User) -> text { return self.name } }','iface.pipe':'public interface Printable { print(self) -> text }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);expect(r.ir?.implementations?.[0].interfaceId).toMatch(/^MOD-\d+::interface::\d+$/);});
  it('statically dispatches imported constrained receivers to the local implementation',()=>{const entry=project({'main.pipe':'import { Printable } from "./iface.pipe"\ntype User { name text }\nimpl Printable for User { function print(self User) -> text { return self.name } }\nfunction show<T: Printable>(value T) -> text { return value.print() }\nfunction main(user User) -> text { return show(user) }','iface.pipe':'public interface Printable { print(self) -> text }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);const show=r.ir!.functions.find(f=>f.name==='show')!;const print=r.ir!.functions.find(f=>f.name==='print')!;expect((show.body[0] as any).value.implementationFunctionId).toBe(print.id);expect((show.constraints as any)?.[0]?.interfaceId).toBe(r.ir!.implementations?.[0]?.interfaceId);expect(executeValue(r.ir!.functions,'main',[{name:'Ada'}])).toBe('Ada');});
  it('binds same-named interfaces by the explicit import target',()=>{const entry=project({'main.pipe':'import { Printable } from "./iface-a.pipe"\nimport { helper } from "./iface-b.pipe"\ntype User { name text }\nimpl Printable for User { function print(self User) -> text { return self.name } }','iface-a.pipe':'public interface Printable { print(self) -> text }','iface-b.pipe':'public interface Printable { print(self) -> text } public function helper() -> text { return "ok" }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);expect(r.ir?.implementations?.[0].interfaceId).toBe('MOD-002::interface::0');});
  it('dispatches a same-named constrained interface through its explicit import',()=>{const entry=project({'main.pipe':'import { Printable } from "./iface-a.pipe"\nimport { helper } from "./iface-b.pipe"\ntype User { name text }\nimpl Printable for User { function print(self User) -> text { return self.name } }\nfunction show<T: Printable>(value T) -> text { return value.print() }\nfunction main(user User) -> text { return show(user) }','iface-a.pipe':'public interface Printable { print(self) -> text }','iface-b.pipe':'public interface Printable { print(self) -> integer } public function helper() -> text { return "ok" }'});const r=compileProject(entry);expect(r.diagnostics).toEqual([]);const interfaces=r.ir!.interfaces!;expect(new Set(interfaces.map(i=>i.id)).size).toBe(2);const show=r.ir!.functions.find(f=>f.name==='show')!;expect((show.constraints as any)?.[0]?.interfaceId).toBe(r.ir!.implementations?.[0]?.interfaceId);expect(executeValue(r.ir!.functions,'main',[{name:'Ada'}])).toBe('Ada');});
  it('rejects an implementation owned by neither its interface nor its concrete type',()=>{const entry=project({'main.pipe':'import { Printable } from "./iface.pipe"\nimport { User } from "./types.pipe"\nimpl Printable for User { function print(self User) -> text { return "x" } }','iface.pipe':'interface Printable { print(self) -> text }','types.pipe':'type User { name text }'});expect(compileProject(entry).diagnostics.map(d=>d.code)).toContain('PIPE-IFACE-007');});
});
