import {describe,it,expect} from 'vitest';
import {mkdtempSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {parseMultipart} from '../src/http/multipart.js';
import {startNodeHttp,startNodeHttpSource} from '../src/http/node-adapter.js';
import {compile} from '../src/compiler.js';
import {issueCapability} from '../src/runtime/capabilities.js';
import {executeValue,UploadValue,ResultValue} from '../src/core/interpreter.js';

const body=(boundary:string)=>Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="title"\r\n\r\nReport\r\n--${boundary}\r\nContent-Disposition: form-data; name="attachment"; filename="../report.txt"\r\nContent-Type: text/plain\r\n\r\nhello\r\n--${boundary}--\r\n`);
const multiBody=(boundary:string)=>Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="first"; filename="one.txt"\r\nContent-Type: text/plain\r\n\r\none\r\n--${boundary}\r\nContent-Disposition: form-data; name="second"; filename="two.txt"\r\nContent-Type: text/plain\r\n\r\ntwo\r\n--${boundary}--\r\n`);
const boundBody=(boundary:string)=>Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="title"\r\n\r\nReport\r\n--${boundary}\r\nContent-Disposition: form-data; name="attachment"; filename="report.txt"\r\nContent-Type: text/plain\r\n\r\nhello\r\n--${boundary}\r\nContent-Disposition: form-data; name="attachments"; filename="one.txt"\r\nContent-Type: text/plain\r\n\r\none\r\n--${boundary}\r\nContent-Disposition: form-data; name="attachments"; filename="two.txt"\r\nContent-Type: text/plain\r\n\r\ntwo\r\n--${boundary}--\r\n`);
const titleOnlyBody=(boundary:string)=>Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="title"\r\n\r\nReport\r\n--${boundary}--\r\n`);

describe('bounded multipart transport boundary',()=>{
 it('parses fields and bounded file metadata with a safe filename',()=>{const result=parseMultipart(body('bmec-boundary'),'multipart/form-data; boundary=bmec-boundary');expect(result.fields).toEqual({title:['Report']});expect(result.files[0]).toMatchObject({fieldName:'attachment',filename:'report.txt',mediaType:'text/plain',size:5});expect(result.files[0]!.data.toString()).toBe('hello');});
 it('rejects files over the explicit limit',()=>expect(()=>parseMultipart(body('bmec-boundary'),'multipart/form-data; boundary=bmec-boundary',{maxFileBytes:4})).toThrow('PIPE-MULTIPART-006'));
 it('exposes parsed multipart data only at the Node HTTP boundary',async()=>{const route={id:'upload',method:'POST' as const,path:'/upload',pathParams:[],query:[],headers:[],status:200,handlerId:'upload'};const handle=await startNodeHttp({routes:[route]},router=>router.register('upload',request=>({status:200,headers:{},body:{title:request.multipart?.fields.title?.[0],file:request.multipart?.files[0]&&{name:request.multipart.files[0].filename,size:request.multipart.files[0].size,type:request.multipart.files[0].mediaType}}})));try{const response=await fetch(`${handle.url}/upload`,{method:'POST',headers:{'content-type':'multipart/form-data; boundary=bmec-boundary'},body:body('bmec-boundary')});expect(response.status).toBe(200);expect(await response.json()).toEqual({title:'Report',file:{name:'report.txt',size:5,type:'text/plain'}});}finally{await handle.close();}});
 it('injects one bounded file into a typed BMEC upload handler',async()=>{const compiled=compile('app Uploads\nasync function receive(body upload) -> task<text> { return uploadFilename(body) }\nhttp POST /upload -> receive');expect(compiled.diagnostics).toEqual([]);const handle=await startNodeHttpSource(compiled.ir!);try{const response=await fetch(`${handle.url}/upload`,{method:'POST',headers:{'content-type':'multipart/form-data; boundary=bmec-boundary'},body:body('bmec-boundary')});expect(response.status).toBe(200);expect(await response.json()).toBe('report.txt');}finally{await handle.close();}});
 it('injects multiple bounded files into a typed upload list',async()=>{const compiled=compile('app Uploads\nasync function receive(body list<upload>) -> task<integer> { return length(body) }\nhttp POST /upload -> receive');expect(compiled.diagnostics).toEqual([]);const handle=await startNodeHttpSource(compiled.ir!);try{const response=await fetch(`${handle.url}/upload`,{method:'POST',headers:{'content-type':'multipart/form-data; boundary=bmec-boundary'},body:multiBody('bmec-boundary')});expect(response.status).toBe(200);expect(await response.json()).toBe(2);}finally{await handle.close();}});
 it('binds multipart fields and named upload lists into a typed body record',async()=>{const compiled=compile('app Uploads\ntype UploadForm { title text required attachment upload required attachments list<upload> }\nasync function receive(body UploadForm) -> task<text> { return body.title }\nhttp POST /upload -> receive');expect(compiled.diagnostics).toEqual([]);const handle=await startNodeHttpSource(compiled.ir!);try{const response=await fetch(`${handle.url}/upload`,{method:'POST',headers:{'content-type':'multipart/form-data; boundary=bmec-boundary'},body:boundBody('bmec-boundary')});expect(response.status).toBe(200);expect(await response.json()).toBe('Report');}finally{await handle.close();}});
 it('keeps optional multipart fields absent and rejects missing required uploads',async()=>{const optional=compile('app Uploads\ntype OptionalForm { title text? attachment upload? }\nasync function receive(body OptionalForm) -> task<text> { return "ok" }\nhttp POST /upload -> receive');expect(optional.diagnostics).toEqual([]);const optionalHandle=await startNodeHttpSource(optional.ir!);try{const response=await fetch(`${optionalHandle.url}/upload`,{method:'POST',headers:{'content-type':'multipart/form-data; boundary=bmec-boundary'},body:titleOnlyBody('bmec-boundary')});expect(response.status).toBe(200);expect(await response.json()).toBe('ok');}finally{await optionalHandle.close();}const required=compile('app Uploads\ntype RequiredForm { title text attachment upload }\nasync function receive(body RequiredForm) -> task<text> { return "ok" }\nhttp POST /upload -> receive');expect(required.diagnostics).toEqual([]);const requiredHandle=await startNodeHttpSource(required.ir!);try{const response=await fetch(`${requiredHandle.url}/upload`,{method:'POST',headers:{'content-type':'multipart/form-data; boundary=bmec-boundary'},body:titleOnlyBody('bmec-boundary')});expect(response.status).toBe(400);expect(await response.json()).toEqual({error:'invalid_multipart',code:'PIPE-MULTIPART-007'});}finally{await requiredHandle.close();}});
 it('saves a typed upload only through filesystem capability and root',async()=>{const compiled=compile('app Uploads\nasync function receive(fs capability<filesystem>, body upload) -> task<result<boolean,text>> { return saveUpload(fs, body, "saved.txt") }\nhttp POST /upload requires filesystem -> receive');expect(compiled.diagnostics).toEqual([]);const root=mkdtempSync(join(tmpdir(),'bmec-upload-'));const handle=await startNodeHttpSource(compiled.ir!,{filesystemRoot:root,capabilityTokens:new Map([['filesystem',issueCapability('filesystem')]])});try{const response=await fetch(`${handle.url}/upload`,{method:'POST',headers:{'content-type':'multipart/form-data; boundary=bmec-boundary'},body:body('bmec-boundary')});expect(response.status).toBe(200);expect(await response.json()).toEqual({state:'ok',value:true});expect(readFileSync(join(root,'saved.txt'),'utf8')).toBe('hello');}finally{await handle.close();}});
 it('rejects upload save destinations outside the filesystem root',()=>{const compiled=compile('function save(fs capability<filesystem>, body upload) -> result<boolean,text> { return saveUpload(fs, body, "../escape.bin") }');expect(compiled.diagnostics).toEqual([]);const root=mkdtempSync(join(tmpdir(),'bmec-upload-'));const result=executeValue(compiled.ir!.functions,'save',[issueCapability('filesystem'),new UploadValue('x.txt','text/plain',1,Buffer.from('x'))],{filesystemRoot:root});expect(result).toEqual(new ResultValue('err','path_outside_root'));});
});
