import {describe,it,expect,afterEach} from 'vitest';
import {compile} from '../src/compiler.js';
import {startRuntime,type RuntimeHandle} from '../src/runtime/server.js';
import {mkdtempSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const source='app Todo\nmodel Task { title text required done boolean default false }\npage Home { crud Task }';
let handles:RuntimeHandle[]=[];
afterEach(async()=>{for(const h of handles.splice(0)) await h.close();});
async function boot(){const r=compile(source,'todo.pipe'); expect(r.ir).toBeDefined(); const root=mkdtempSync(join(tmpdir(),'pipe-runtime-')); const h=await startRuntime(r.ir!,join(root,'generated'),join(root,'data','todo.db'),0); handles.push(h); return {h,root};}
describe('SQLite runtime',()=>{
 it('keeps optional model absence explicit across JSON and SQLite boundaries',async()=>{const r=compile('app Profiles\nmodel Profile { name text required nickname text? }');expect(r.ir).toBeDefined();const root=mkdtempSync(join(tmpdir(),'pipe-runtime-'));const h=await startRuntime(r.ir!,join(root,'generated'),join(root,'data','profiles.db'),0);handles.push(h);const absent=await fetch(h.url+'/api/Profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Ada'})});expect(absent.status).toBe(201);const a=await absent.json() as any;expect(a.nickname).toBeNull();const present=await fetch(h.url+'/api/Profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Grace',nickname:'G'})});expect((await present.json()).nickname).toBe('G')});
 it('round-trips checked int64 and exact money through SQLite/API contracts',async()=>{const r=compile('app Ledger\nmodel Entry { count integer amount money }');const root=mkdtempSync(join(tmpdir(),'pipe-runtime-'));const h=await startRuntime(r.ir!,join(root,'generated'),join(root,'data','ledger.db'),0);handles.push(h);const response=await fetch(h.url+'/api/Entry',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({count:'9223372036854775807',amount:{minor:'1234',scale:2}})});expect(response.status).toBe(201);expect(await response.json()).toMatchObject({count:'9223372036854775807',amount:{minor:'1234',scale:2}})});
 it('creates a database and performs CRUD',async()=>{const {h}=await boot(); const post=await fetch(h.url+'/api/Task',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'Buy milk'})}); expect(post.status).toBe(201); const created=await post.json() as any; expect(created.done).toBe(0); expect((await (await fetch(h.url+'/api/Task')).json()).length).toBe(1); const put=await fetch(h.url+'/api/Task/'+created.id,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({title:'Buy oat milk'})}); expect((await put.json()).title).toBe('Buy oat milk'); expect((await fetch(h.url+'/api/Task/'+created.id,{method:'DELETE'})).status).toBe(204); expect((await (await fetch(h.url+'/api/Task')).json()).length).toBe(0);});
 it('serves declared API routes used by generated CRUD alongside compatibility routes',async()=>{const r=compile('app Items\nmodel Item { name text required }\napi /items from Item');expect(r.ir).toBeDefined();const root=mkdtempSync(join(tmpdir(),'pipe-runtime-'));const h=await startRuntime(r.ir!,join(root,'generated'),join(root,'data','items.db'),0);handles.push(h);const declared=await fetch(h.url+'/items');const declaredText=await declared.text();expect(declared.status,declaredText).toBe(200);expect(JSON.parse(declaredText)).toEqual([]);const compatibility=await fetch(h.url+'/api/Item');expect(compatibility.status).toBe(200);expect(await compatibility.json()).toEqual([]);});
 it('keeps compatibility CRUD aliases protected by the declared model API policy',async()=>{const r=compile('app Items\nmodel Item { name text required }\napi /items from Item requiring authenticated');expect(r.diagnostics).toEqual([]);const root=mkdtempSync(join(tmpdir(),'pipe-runtime-policy-'));const h=await startRuntime(r.ir!,join(root,'generated'),join(root,'data','items.db'),0);handles.push(h);for(const path of ['/items','/items/1','/api/Item','/api/Item/1','/api/items','/api/items/1']){const response=await fetch(h.url+path,{method:path.endsWith('/1')?'DELETE':'GET'});expect(response.status).toBe(403);}});
 it('persists records after restart',async()=>{const {h,root}=await boot(); await fetch(h.url+'/api/Task',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:'persisted'})}); await h.close(); handles=[]; const r=compile(source); const h2=await startRuntime(r.ir!,join(root,'generated2'),join(root,'data','todo.db'),0); handles.push(h2); expect((await (await fetch(h2.url+'/api/Task')).json())[0].title).toBe('persisted'); expect(existsSync(join(root,'data','todo.db'))).toBe(true);});
 it('rejects missing required fields',async()=>{const {h}=await boot(); const r=await fetch(h.url+'/api/Task',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}); expect(r.status).toBe(400); expect((await r.json()).error).toContain('required');});
 it('rejects calendar-invalid temporal model values',async()=>{const r=compile('app Calendar\nmodel Event { day date stamp datetime }');const root=mkdtempSync(join(tmpdir(),'pipe-runtime-'));const h=await startRuntime(r.ir!,join(root,'generated'),join(root,'data','calendar.db'),0);handles.push(h);const response=await fetch(h.url+'/api/Event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({day:'2025-02-29',stamp:'2026-01-01T24:00:00Z'})});expect(response.status).toBe(400);});
 it('rejects invalid JSON',async()=>{const {h}=await boot(); const r=await fetch(h.url+'/api/Task',{method:'POST',headers:{'content-type':'application/json'},body:'nope'}); expect(r.status).toBe(400);});
 it('serves generated UI',async()=>{const {h}=await boot(); const r=await fetch(h.url); expect(r.status).toBe(200); expect(await r.text()).toContain('Todo');});
});
