import {afterEach,describe,expect,it} from 'vitest';
import {readFileSync,mkdtempSync} from 'node:fs';
import {join} from 'node:path';
import Database from 'better-sqlite3';
import {compileProject} from '../src/compiler.js';
import {startNodeHttpSource,type NodeHttpHandle} from '../src/http/node-adapter.js';
import {ensureSqliteSchema} from '../src/db/sqlite.js';
import {sqliteAdapter} from '../src/db/adapter.js';
import {issueCapability} from '../src/runtime/capabilities.js';
import {executeValue} from '../src/core/interpreter.js';
import {serializeValue} from '../src/runtime/value-contract.js';
import {AuthService} from '../src/runtime/auth.js';
import {authenticatedSession,rolePolicy} from '../src/http/auth-policy.js';
import {generateClientBindings} from '../src/http/client-bindings.js';
import {buildRelease} from '../src/release/release.js';
import {tmpdir} from 'node:os';
import {migrateSqliteSchema} from '../src/db/sqlite.js';

const handles:NodeHttpHandle[]=[];const clients:InstanceType<typeof Database>[]=[];
afterEach(async()=>{for(const handle of handles.splice(0))await handle.close();for(const client of clients.splice(0))client.close()});
describe('BMEC Task Manager application',()=>it('compiles multiple modules and executes async typed DB HTTP handlers',async()=>{
 const entry=join(process.cwd(),'examples','task-manager','main.pipe');const source=readFileSync(entry,'utf8');expect(source).toContain('async function');const compiled=compileProject(entry);expect(compiled.diagnostics).toEqual([]);expect(compiled.modules.length).toBe(3);expect(compiled.ir?.http?.routes.some(route=>route.path==='/task-feed')).toBe(true);const previousName=process.env.APP_NAME,previousSecret=process.env.APP_SECRET;process.env.APP_NAME='Task Manager';process.env.APP_SECRET='test-secret';try{const env=issueCapability('environment');expect(executeValue(compiled.ir!.functions,'configuredName',[env])).toBe('Task Manager');expect(executeValue(compiled.ir!.functions,'configuredSecretExists',[env])).toBe(true)}finally{if(previousName===undefined)delete process.env.APP_NAME;else process.env.APP_NAME=previousName;if(previousSecret===undefined)delete process.env.APP_SECRET;else process.env.APP_SECRET=previousSecret}
 const client=new Database(':memory:');clients.push(client);ensureSqliteSchema(client,compiled.ir!.db!);const db=sqliteAdapter(client,compiled.ir!.db!);const token=issueCapability('database');const auth=new AuthService();await auth.register('owner','owner pass',{role:'admin'});const handle=await startNodeHttpSource(compiled.ir!,{capabilityTokens:new Map([['database',token]]),database:{adapter:db,schema:compiled.ir!.db!},configureRouter:router=>{router.registerPolicy('authenticated',authenticatedSession(auth.sessions));router.registerPolicy('role:admin',rolePolicy(auth,'admin'));}});handles.push(handle);
 const denied=await fetch(`${handle.url}/task-feed`);expect(denied.status).toBe(403);const apiDenied=await fetch(`${handle.url}/tasks`);expect(apiDenied.status).toBe(403);expect((await fetch(`${handle.url}/tasks/1`)).status).toBe(403);expect((await fetch(`${handle.url}/tasks/1`,{method:'DELETE'})).status).toBe(403);const session=await auth.login('owner','owner pass');const authHeaders={authorization:`Bearer ${session!.id}`};const apiEmpty=await fetch(`${handle.url}/tasks`,{headers:authHeaders});expect(apiEmpty.status).toBe(200);expect(await apiEmpty.json()).toEqual([]);const empty=await fetch(`${handle.url}/task-feed`,{headers:authHeaders});expect(empty.status).toBe(200);expect(await empty.json()).toEqual([]);
 const create=compiled.ir!.functions.find(fn=>fn.name==='createTask')!;const bodyType=create.parameters.find(parameter=>parameter.name==='body')!.typeRef;const body=serializeValue({kind:'model',type:bodyType,fields:{title:{kind:'text',value:'ship task'},done:{kind:'boolean',value:false}}});const deniedUpdate=await fetch(`${handle.url}/tasks/1`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)});expect(deniedUpdate.status).toBe(403);const response=await fetch(`${handle.url}/tasks`,{method:'POST',headers:{'content-type':'application/json',...authHeaders},body:JSON.stringify(body)});expect(response.status).toBe(200);expect(await response.json()).toBe(1);
 expect(await (await fetch(`${handle.url}/task-feed`,{headers:authHeaders})).json()).toEqual([{id:1,title:'ship task',done:false}]);const apiRows=await fetch(`${handle.url}/tasks`,{headers:authHeaders});expect(await apiRows.json()).toEqual([{id:1,title:'ship task',done:false}]);const updatedBody=serializeValue({kind:'model',type:bodyType,fields:{title:{kind:'text',value:'updated task'},done:{kind:'boolean',value:true}}});const updated=await fetch(`${handle.url}/tasks/1`,{method:'PUT',headers:{'content-type':'application/json',...authHeaders},body:JSON.stringify(updatedBody)});expect(updated.status).toBe(200);expect(await updated.json()).toBe(1);expect(await (await fetch(`${handle.url}/tasks/1`,{headers:authHeaders})).json()).toMatchObject({id:1,title:'updated task',done:true});const removed=await fetch(`${handle.url}/tasks/1`,{method:'DELETE',headers:authHeaders});expect(removed.status).toBe(200);expect(await removed.json()).toBe(1);expect(await (await fetch(`${handle.url}/tasks`,{headers:authHeaders})).json()).toEqual([]);
 }));
 it('uses controlled-English database routes with API authorization in canonical IR',()=>{const entry=join(process.cwd(),'examples','task-manager','main.pipe');const compiled=compileProject(entry);expect(compiled.diagnostics).toEqual([]);expect(compiled.ir!.apis).toEqual(expect.arrayContaining([expect.objectContaining({route:'/users',policyId:'role:admin'}),expect.objectContaining({route:'/tasks',policyId:'authenticated'})]));expect(compiled.ir!.http!.routes.filter(route=>route.path==='/task-feed'||route.path==='/tasks'||route.path==='/tasks/:id')).toEqual(expect.arrayContaining([expect.objectContaining({path:'/task-feed',method:'GET',capabilities:['database']}),expect.objectContaining({path:'/tasks',method:'POST',capabilities:['database'],policyId:'authenticated'}),expect.objectContaining({path:'/tasks/:id',method:'GET',policyId:'authenticated'}),expect.objectContaining({path:'/tasks/:id',method:'PUT',policyId:'authenticated'}),expect.objectContaining({path:'/tasks/:id',method:'DELETE',policyId:'authenticated'})]));expect(compiled.ir!.http!.routes.filter(route=>route.path==='/task-feed'||route.path==='/tasks'||route.path==='/tasks/:id').every(route=>route.policyId==='authenticated')).toBe(true);});
 it('uses controlled-English database handlers over the canonical typed IR',()=>{const entry=join(process.cwd(),'examples','task-manager','main.pipe');const source=readFileSync(entry,'utf8');expect(source).toContain('wait for get tasks from Task using db');expect(source).toContain('wait for add body to Task using db');const compiled=compileProject(entry);expect(compiled.diagnostics).toEqual([]);const list=(compiled.ir!.functions.find(fn=>fn.name==='listTasks')!.body[0] as any).value.operand;const create=(compiled.ir!.functions.find(fn=>fn.name==='createTask')!.body[0] as any).value.operand;expect(list).toMatchObject({kind:'call',callee:'databaseSelect'});expect(create).toMatchObject({kind:'call',callee:'databaseInsert'});});
 it('derives the client and deterministic browser/server release from the same IR',()=>{const entry=join(process.cwd(),'examples','task-manager','main.pipe');const compiled=compileProject(entry);expect(compiled.diagnostics).toEqual([]);const client=generateClientBindings(compiled.ir!.http!,compiled.ir!);expect(client).toContain('SOURCE_HTTP_001');expect(client).toContain('SOURCE_HTTP_001Params');expect(client).toContain('request("GET"');const output=join(mkdtempSync(join(tmpdir(),'pipe-task-release-')),'out');const release=buildRelease(compiled.ir!,output,{packageName:'task-manager',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});const server=readFileSync(join(output,release.artifacts.server),'utf8');const browser=readFileSync(join(output,release.artifacts.browser),'utf8');const bundle=readFileSync(join(output,'app.js'),'utf8');expect(server).toContain('databaseSelect');expect(browser).not.toContain('databaseSelect');expect(browser).not.toContain('"db":{');expect(browser).toContain('data-pipe-component="COMP-001"');expect(browser).toContain('data-api="/tasks"');expect(browser).toContain('data-pipe-event="create"');expect(browser).toContain('Create task');expect(browser).toContain('data-pipe-validation="nonempty"');expect(bundle).toContain('version:1');expect(bundle).toContain('pipeSourceApi');expect(bundle).toContain('PIPE_UI_EVENTS');});
 it('applies a safe additive migration without losing Task Manager rows',()=>{const entry=join(process.cwd(),'examples','task-manager','main.pipe');const compiled=compileProject(entry);const client=new Database(':memory:');clients.push(client);const previous={version:1 as const,models:[]};migrateSqliteSchema(client,previous,compiled.ir!.db!);client.prepare('INSERT INTO "Task" (title) VALUES (?)').run('preserve me');const task=compiled.ir!.db!.models.find(model=>model.name==='Task')!;const current={...compiled.ir!.db!,models:compiled.ir!.db!.models.map(model=>model.id===task.id?{...model,fields:[...model.fields,{id:'TASK-PRIORITY',name:'priority',type:{kind:'primitive' as const,name:'integer'}}]}:model)};const plan=migrateSqliteSchema(client,compiled.ir!.db!,current);expect(plan.requiresReview).toBe(false);expect(client.prepare('SELECT title, priority FROM "Task"').get()).toMatchObject({title:'preserve me',priority:null});});
