import {describe,expect,it} from 'vitest';
import {compile} from '../src/compiler.js';
import {DateValue,DateTimeValue,IdValue,executeValue} from '../src/core/interpreter.js';
import {issueCapability} from '../src/runtime/capabilities.js';

describe('owned temporal runtime values',()=>{
 it('validates, compares, and serializes date/datetime/id values',()=>{
  const r=compile('function before(a date, b date) -> boolean { return a < b } function same(a date, b date) -> boolean { return a == b } function sameTime(a datetime, b datetime) -> boolean { return a == b } function id(a id) -> id { return a }');
  expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'before',['2026-01-01','2026-02-01'])).toBe(true);expect(executeValue(r.ir!.functions,'same',['2026-01-01','2026-01-01'])).toBe(true);expect(executeValue(r.ir!.functions,'sameTime',['2026-01-01T00:00:00Z','2026-01-01T00:00:00Z'])).toBe(true);expect(executeValue(r.ir!.functions,'id',['user_1'])).toEqual(new IdValue('user_1'));
 });
 it('rejects invalid temporal arguments',()=>{const r=compile('function f(a date) -> date { return a }');expect(()=>executeValue(r.ir!.functions,'f',['2025-02-29'])).toThrow('Invalid date value');expect(()=>executeValue(r.ir!.functions,'f',['2026-01-01T00:00:00Z'])).toThrow('Invalid date value');expect(new DateValue('2026-09-16').toString()).toBe('2026-09-16');expect(new DateTimeValue('2026-09-16T00:00:00Z').toString()).toContain('2026-09-16');});
 it('parses temporal text into recoverable Results',()=>{const r=compile('function f(value text) -> result<date,text> { return parseDate(value) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'f',['2026-09-16'])).toEqual({kind:'result',state:'ok',payload:new DateValue('2026-09-16')});expect(executeValue(r.ir!.functions,'f',['bad'])).toEqual({kind:'result',state:'err',payload:'bad'});});
 it('types and executes expected temporal string literals',()=>{const r=compile('function d() -> date { return "2026-09-16" } function t() -> datetime { return "2026-09-16T12:30:00Z" } function i() -> id { return "user_1" }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'d',[])).toEqual(new DateValue('2026-09-16'));expect(executeValue(r.ir!.functions,'t',[])).toEqual(new DateTimeValue('2026-09-16T12:30:00Z'));expect(executeValue(r.ir!.functions,'i',[])).toEqual(new IdValue('user_1'));});
 it('rejects invalid expected temporal literals at compile time',()=>{const r=compile('function d() -> date { return "2025-02-29" } function t() -> datetime { return "2026-09-16T25:00:00Z" } function i() -> id { return "bad id" }');expect(r.diagnostics.filter(error=>error.code==='PIPE-TYPE-006')).toHaveLength(3);});
 it('extracts calendar parts through typed temporal helpers',()=>{const r=compile('function year(value date) -> integer { return dateYear(value) } function month(value datetime) -> integer { return dateMonth(value) } function day(value date) -> integer { return dateDay(value) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'year',['2026-09-16'])).toBe(2026n);expect(executeValue(r.ir!.functions,'month',['2026-09-16T12:30:00Z'])).toBe(9n);expect(executeValue(r.ir!.functions,'day',['2026-09-16'])).toBe(16n);});
 it('adds bounded UTC calendar days and reports overflow as a Result',()=>{const r=compile('function shift(value date, days integer) -> result<date,text> { return addDays(value, days) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'shift',['2024-02-28',1n])).toEqual({kind:'result',state:'ok',payload:new DateValue('2024-02-29')});expect(executeValue(r.ir!.functions,'shift',['2024-03-01',-1n])).toEqual({kind:'result',state:'ok',payload:new DateValue('2024-02-29')});expect(executeValue(r.ir!.functions,'shift',['2026-01-01',4000001n])).toEqual({kind:'result',state:'err',payload:'date_out_of_range'});expect(compile('function bad(value datetime, days integer) -> result<date,text> { return addDays(value, days) }').diagnostics.map(error=>error.code)).toContain('PIPE-FUNC-009');});
 it('adds bounded UTC seconds to datetimes and reports overflow as a Result',()=>{const r=compile('function shift(value datetime, seconds integer) -> result<datetime,text> { return addSeconds(value, seconds) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'shift',['2024-02-29T23:59:59Z',1n])).toEqual({kind:'result',state:'ok',payload:new DateTimeValue('2024-03-01T00:00:00.000Z')});expect(executeValue(r.ir!.functions,'shift',['2024-03-01T00:00:00.500Z',-1n])).toEqual({kind:'result',state:'ok',payload:new DateTimeValue('2024-02-29T23:59:59.500Z')});expect(executeValue(r.ir!.functions,'shift',['2026-01-01T00:00:00Z',315537897601n])).toEqual({kind:'result',state:'err',payload:'datetime_out_of_range'});expect(compile('function bad(value date, seconds integer) -> result<datetime,text> { return addSeconds(value, seconds) }').diagnostics.map(error=>error.code)).toContain('PIPE-FUNC-009');});
 it('computes signed whole UTC seconds between datetimes',()=>{const r=compile('function difference(start datetime, finish datetime) -> integer { return datetimeDifference(start, finish) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'difference',['2024-02-29T23:59:59.500Z','2024-03-01T00:00:00.900Z'])).toBe(1n);expect(executeValue(r.ir!.functions,'difference',['2024-03-01T00:00:00Z','2024-02-29T23:59:58Z'])).toBe(-2n);expect(compile('function bad(start date, finish datetime) -> integer { return datetimeDifference(start, finish) }').diagnostics.map(error=>error.code)).toContain('PIPE-FUNC-009');});
 it('computes signed UTC calendar-day differences for typed dates',()=>{const r=compile('function difference(start date, finish date) -> integer { return dateDifference(start, finish) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'difference',['2024-02-28','2024-03-01'])).toBe(2n);expect(executeValue(r.ir!.functions,'difference',['2024-03-01','2024-02-28'])).toBe(-2n);expect(compile('function bad(start datetime, finish date) -> integer { return dateDifference(start, finish) }').diagnostics.map(error=>error.code)).toContain('PIPE-FUNC-009');});
 it('provides a capability-gated UTC today value',()=>{const r=compile('function todayValue(clock capability<time>) -> date { return today(clock) }');expect(r.diagnostics).toEqual([]);expect(executeValue(r.ir!.functions,'todayValue',[issueCapability('time')])).toBe(new Date().toISOString().slice(0,10));expect(compile('function bad(clock capability<random>) -> date { return today(clock) }').diagnostics.map(error=>error.code)).toContain('PIPE-FUNC-009');});
 it('rejects non-temporal calendar helper arguments',()=>{expect(compile('function bad(value text) -> integer { return dateYear(value) }').diagnostics.map(error=>error.code)).toContain('PIPE-FUNC-009');});
});
