import {describe,expect,it} from 'vitest';
import {render} from '../src/ui/dom.js';
import {primitive} from '../src/types/type-ref.js';
import {compile} from '../src/compiler.js';

describe('controlled-English UI bindings',()=>{
 it('renders a bound list item field through the canonical UI IR',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},attributes:{},appendChild(child:any){this.children.push(child)},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Tasks\nmodel User { name text }\ncomponent Row { show task name }\npage Home { state tasks list<User> for each task in tasks show Row }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};
  render(result.ir!.ui!,root,{tasks:[{name:'Alex'},{name:'Sam'}]});const nodes=root.children.flatMap((node:any)=>node.tag==='fragment'?node.children:[node]);expect(nodes.flatMap((node:any)=>node.children??[]).filter((node:any)=>node.tag==='text').map((node:any)=>node.value)).toEqual(['Alex','Sam']);
 });
 it('renders an accessible empty message only when a page list has no rows',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},attributes:{},appendChild(child:any){this.children.push(child)},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Tasks\ncomponent Row { text "Task" }\npage Home { state loading boolean state error boolean state tasks list<text> loading "Loading tasks" error "Unable to load tasks" for each task in tasks show Row empty "No tasks yet" }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};
  render(result.ir!.ui!,root,{loading:true,error:false,tasks:[]});let nodes=root.children.flatMap((node:any)=>node.tag==='fragment'?node.children:[node]);expect(nodes.some((node:any)=>node.tag==='p'&&node.textContent==='No tasks yet')).toBe(false);
  render(result.ir!.ui!,root,{loading:false,error:true,tasks:[]});nodes=root.children.flatMap((node:any)=>node.tag==='fragment'?node.children:[node]);expect(nodes.some((node:any)=>node.tag==='p'&&node.textContent==='No tasks yet')).toBe(false);
  render(result.ir!.ui!,root,{loading:false,error:false,tasks:[]});nodes=root.children.flatMap((node:any)=>node.tag==='fragment'?node.children:[node]);expect(nodes).toContainEqual(expect.objectContaining({tag:'p',textContent:'No tasks yet',attributes:{role:'status','aria-live':'polite'}}));
  render(result.ir!.ui!,root,{loading:false,error:false,tasks:['first']});nodes=root.children.flatMap((node:any)=>node.tag==='fragment'?node.children:[node]);expect(nodes.some((node:any)=>node.tag==='p'&&node.textContent==='No tasks yet')).toBe(false);expect(nodes.filter((node:any)=>node.dataset?.pipeComponent==='COMP-001')).toHaveLength(1);
 });
 it('filters typed record lists by their declared text field',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},attributes:{},listeners:{},appendChild(child:any){this.children.push(child)},replaceChildren(...children:any[]){this.children=children},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Tasks\nmodel Task { title text }\ncomponent Row { show task title }\npage Home { state tasks list<Task> for each task in tasks show Row filter by title }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};
  render(result.ir!.ui!,root,{tasks:[{title:'Alpha'},{title:'Beta'}]});const wrapper=root.children[0],input=wrapper.children[0].children[0],list=wrapper.children[1];expect(list.children).toHaveLength(2);input.value='bet';input.listeners.input();expect(list.children).toHaveLength(1);expect(list.children[0].children[0].value).toBe('Beta');input.value='missing';input.listeners.input();expect(list.children[0]).toMatchObject({tag:'p',textContent:'No matching items.',attributes:{role:'status','aria-live':'polite'}});
 });
 it('paginates filtered page-list rows with accessible range and controls',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},attributes:{},listeners:{},appendChild(child:any){this.children.push(child)},replaceChildren(...children:any[]){this.children=children},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Tasks\nmodel Task { title text }\ncomponent Row { show task title }\npage Home { state tasks list<Task> for each task in tasks show Row filter by title paginate 2 }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};
  render(result.ir!.ui!,root,{tasks:[{title:'Alpha'},{title:'Beta'},{title:'Gamma'},{title:'Delta'},{title:'Epsilon'}]});const wrapper=root.children[0],search=wrapper.children[0].children[0],list=wrapper.children[1],navigation=wrapper.children[2],previous=navigation.children[0],range=navigation.children[1],next=navigation.children[2];expect(list.children.map((row:any)=>row.children[0].value)).toEqual(['Alpha','Beta']);expect(range.textContent).toBe('Showing 1-2 of 5');expect(previous.disabled).toBe(true);next.listeners.click();expect(list.children.map((row:any)=>row.children[0].value)).toEqual(['Gamma','Delta']);expect(range.textContent).toBe('Showing 3-4 of 5');expect(previous.disabled).toBe(false);search.value='epsilon';search.listeners.input();expect(list.children.map((row:any)=>row.children[0].value)).toEqual(['Epsilon']);expect(range.textContent).toBe('Showing 1-1 of 1');expect(next.disabled).toBe(true);
 });
});

describe('direct DOM UI backend',()=>{
 it('renders enum UI inputs as selects with only payload-free variants',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},appendChild(child:any){this.children.push(child)},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Work\nenum Status { Pending Assigned Done(text) }\ncomponent Form { input status Status }\npage Home { use Form }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};render(result.ir!.ui!,root);
  const select=root.children[0].children[0];expect(select.tag).toBe('select');expect(select.children.map((option:any)=>option.value)).toEqual(['Pending','Assigned']);
 });
 it('renders canonical UI nodes without framework semantics',()=>{(globalThis as any).document={createTextNode:(value:string)=>value};const root={children:[] as any[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}} as any;render({components:[{id:'C1',name:'Greeting',props:[],state:[],events:[],children:[{kind:'text',value:'hello'}]}],routes:[]},root);expect(root.children).toHaveLength(1);});
 it('renders conditions and lists and dispatches validated input events',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{} as Record<string,(event:any)=>void>,appendChild(child:any){this.children.push(child)},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};let seen='';
  let typed:unknown;render({components:[{id:'C1',name:'Form',props:[],state:[],events:[{name:'changed',parameters:{value:primitive('integer')}}],children:[{kind:'input',name:'count',type:primitive('integer'),event:'changed'},{kind:'input',name:'title',type:primitive('text'),validation:'nonempty',event:'changed'},{kind:'conditional',condition:'visible',then:[{kind:'text',value:'shown'}]},{kind:'list',source:'items',item:'item',body:[{kind:'text',value:'row'}]}]}],routes:[]},root,{visible:true,items:['a','b']},'/',{changed:(_event,value)=>{typed=value;seen=String(value)}});
  const nodes=root.children.flatMap((node:any)=>node.tag==='fragment'?node.children:[node]);expect(nodes.filter((x:any)=>x.tag==='text'&&x.value==='shown')).toHaveLength(1);expect(nodes.filter((x:any)=>x.tag==='text'&&x.value==='row')).toHaveLength(2);const input=nodes.find((x:any)=>x.name==='count');input.value='bad';input.listeners.input({target:input});expect(input.dataset.pipeError).toBe('expected int64 integer');input.value='7';input.listeners.input({target:input});expect(seen).toBe('7');expect(typed).toBe(7n);expect(input.dataset.pipeError).toBeUndefined();const title=nodes.find((x:any)=>x.name==='title');title.value='   ';title.listeners.input({target:title});expect(title.dataset.pipeError).toBe('value is required');expect(seen).toBe('7');title.value='Ready';title.listeners.input({target:title});expect(title.dataset.pipeError).toBeUndefined();expect(seen).toBe('Ready');
 });
 it('renders compiled BMEC source UI through the direct-DOM backend',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},attributes:{},appendChild(child:any){this.children.push(child)},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Tasks\ncomponent Row { text "task" }\npage Home { state items list<text> loading "Loading" list items item Row }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};
  render(result.ir!.ui!,root,{loading:true,items:['a','b']});const nodes=root.children.flatMap((node:any)=>node.tag==='fragment'?node.children:[node]);expect(nodes.find((node:any)=>node.textContent==='Loading')).toMatchObject({tag:'p',hidden:false,attributes:{role:'status','aria-live':'polite'},dataset:{pipeCondition:'loading'}});expect(nodes.filter((node:any)=>node.dataset?.pipeComponent==='COMP-001')).toHaveLength(2);
 });
 it('applies typed repeated-row append and remove updates through the direct-DOM backend',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},attributes:{},appendChild(child:any){this.children.push(child)},replaceChildren(...children:any[]){this.children=children},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Tasks\nmodel Task { title text required }\ncomponent TaskRow { button "Duplicate" on duplicate with task from task button "Remove" on remove with task from task }\npage Home { event duplicate(task Task) appends task to tasks event remove(task Task) removes task from tasks state tasks list<Task> = [] for each task in tasks show TaskRow }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(...children:any[]){this.children=children},appendChild(node:any){this.children.push(node)}};const state={tasks:[{id:1,title:'One'}]};render(result.ir!.ui!,root,state);const findButtons=()=>{const walk=(node:any):any[]=>[node,...(node.children??[]).flatMap(walk)];return walk(root).filter(node=>node.tag==='button')};findButtons().find(button=>button.textContent==='Duplicate')!.listeners.click({});expect(state.tasks).toHaveLength(2);findButtons().find(button=>button.textContent==='Remove')!.listeners.click({});expect(state.tasks).toHaveLength(1);
 });
 it('increments and decrements a typed numeric list field through the direct-DOM backend',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},attributes:{},appendChild(child:any){this.children.push(child)},replaceChildren(...children:any[]){this.children=children},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Shop\nmodel CartLine { product text required quantity integer required }\ncomponent CartRow { button "More" on more with line from line button "Less" on less with line from line }\npage Cart { event more(line CartLine) increases quantity of line in cart event less(line CartLine) decreases quantity of line in cart state cart list<CartLine> = [] for each line in cart show CartRow }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(...children:any[]){this.children=children},appendChild(node:any){this.children.push(node)}};const state={cart:[{id:9,product:'Book',quantity:1}]};render(result.ir!.ui!,root,state);const findButtons=()=>{const walk=(node:any):any[]=>[node,...(node.children??[]).flatMap(walk)];return walk(root).filter(node=>node.tag==='button')};findButtons().find(button=>button.textContent==='More')!.listeners.click({});expect(state.cart[0]!.quantity).toBe(2);findButtons().find(button=>button.textContent==='Less')!.listeners.click({});expect(state.cart[0]!.quantity).toBe(1);
 });
 it('recalculates a derived subtotal after list quantity changes in the direct-DOM backend',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},attributes:{},appendChild(child:any){this.children.push(child)},replaceChildren(...children:any[]){this.children=children},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Shop\nmodel CartLine { price integer quantity integer }\ncomponent CartRow { button "More" on more with line from line }\ncomponent Summary { show total of cart by price times quantity }\npage Cart { event more(line CartLine) increases quantity of line in cart state cart list<CartLine> for each line in cart show CartRow use Summary }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(...children:any[]){this.children=children},appendChild(node:any){this.children.push(node)}};const state={cart:[{id:9,price:12,quantity:2}]};render(result.ir!.ui!,root,state);const walk=(node:any):any[]=>[node,...(node.children??[]).flatMap(walk)];expect(walk(root).find(node=>node.tag==='text')!.value).toBe('24');walk(root).find(node=>node.tag==='button')!.listeners.click({});expect(state.cart[0]!.quantity).toBe(3);expect(walk(root).find(node=>node.tag==='text')!.value).toBe('36');
 });
 it('sums money aggregates in integer minor units and keeps two decimal places',()=>{
  const result=compile('app Shop\nmodel CartLine { price money quantity integer }\ncomponent Summary { text "Subtotal: $" show total of cart by price times quantity }\npage Cart { state cart list<CartLine> = [] use Summary }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(...children:any[]){this.children=children},appendChild(node:any){this.children.push(node)}};render(result.ir!.ui!,root,{cart:[{price:0.1,quantity:3},{price:0.2,quantity:1}]});const walk=(node:any):any[]=>[node,...(node.children??[]).flatMap(walk)];expect(walk(root).filter(node=>node.tag==='text').at(-1)!.value).toBe('0.50');
 });
 it('persists typed UI state through the direct-DOM storage contract',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},attributes:{},appendChild(child:any){this.children.push(child)},replaceChildren(...children:any[]){this.children=children},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler},setAttribute(name:string,value:string){this.attributes[name]=value}};return node};(globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};const storage=new Map<string,string>();(globalThis as any).localStorage={getItem:(key:string)=>storage.get(key)??null,setItem:(key:string,value:string)=>storage.set(key,value),removeItem:(key:string)=>storage.delete(key)};const result=compile('app Tasks\nmodel Task { title text required }\ncomponent TaskRow { button "Add" on add with task from task }\npage Home { event add(task Task) appends task to tasks state tasks list<Task> = [] persisted in local storage for each task in tasks show TaskRow }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(...children:any[]){this.children=children},appendChild(node:any){this.children.push(node)}};const state:any={tasks:[{id:2,title:'Sample'}]};render(result.ir!.ui!,root,state);const walk=(node:any):any[]=>[node,...(node.children??[]).flatMap(walk)];walk(root).find(node=>node.tag==='button')!.listeners.click({});expect(state.tasks).toEqual([{id:2,title:'Sample'},{id:2,title:'Sample'}]);const restored:any={};const otherRoot:any={children:[],replaceChildren(...children:any[]){this.children=children},appendChild(node:any){this.children.push(node)}};render(result.ir!.ui!,otherRoot,restored);expect(restored.tasks).toEqual([{id:2,title:'Sample'},{id:2,title:'Sample'}]);delete (globalThis as any).localStorage;
 });
 it('dispatches canonical button clicks to typed UI handlers',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},appendChild(child:any){this.children.push(child)},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};let clicked=0;
  render({components:[{id:'C1',name:'Form',props:[],state:[],events:[{name:'clicked',parameters:{}}],children:[{kind:'button',label:'Sign in',event:'clicked'}]}],routes:[]},root,{},'/', {clicked:()=>{clicked++}});
  const button=root.children[0];expect(button.textContent).toBe('Sign in');button.listeners.click({});expect(clicked).toBe(1);
 });
 it('dispatches compiled named click phrases through the direct-DOM backend',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},listeners:{},appendChild(child:any){this.children.push(child)},addEventListener(name:string,handler:(event:any)=>void){this.listeners[name]=handler}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Login component Form { button "Save" on Save } page Home { when Save is clicked use Form }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};let clicked=0;
  render(result.ir!.ui!,root,{},'/',{Save:()=>{clicked++}});const button=root.children[0].children[0];expect(button.textContent).toBe('Save');button.listeners.click({});expect(clicked).toBe(1);
 });
 it('renders typed internal page links as standard anchors in the direct-DOM backend',()=>{
  const make=(tag:string)=>({tag,children:[],dataset:{},appendChild(child:any){this.children.push(child)}} as any);
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Tasks page Home { link "View tasks" to Tasks } page Tasks {}');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};
  render(result.ir!.ui!,root,{},'/home');expect(root.children[0]).toMatchObject({tag:'a',textContent:'View tasks',href:'/tasks'});
 });
 it('opens and closes the native dialog through its typed trigger and close form',()=>{
  const make=(tag:string)=>{const node:any={tag,children:[],dataset:{},attributes:{},listeners:{},appendChild(child:any){this.children.push(child)},setAttribute(name:string,value:string){this.attributes[name]=value},addEventListener(name:string,handler:()=>void){this.listeners[name]=handler},showModal(){this.open=true}};return node};
  (globalThis as any).document={createTextNode:(value:string)=>({tag:'text',value}),createElement:make,createDocumentFragment:()=>make('fragment')};
  const result=compile('app Details page Home { dialog "Open details" title "Project details" message "Ready." }');expect(result.diagnostics).toEqual([]);const root:any={children:[],replaceChildren(){this.children=[]},appendChild(node:any){this.children.push(node)}};
  render(result.ir!.ui!,root,{},'/home');const wrapper=root.children[0],trigger=wrapper.children[0],dialog=wrapper.children[1];expect(trigger).toMatchObject({textContent:'Open details',attributes:{'aria-haspopup':'dialog','aria-controls':'DIALOG-001'}});trigger.listeners.click();expect(dialog.open).toBe(true);expect(dialog.attributes['aria-labelledby']).toBe('DIALOG-001-title');expect(dialog.children[0].children[2].textContent).toBe('Close');
 });
});
