import type {ProjectIR} from '../ir/ir.js';

export interface GraphNode {id:string;kind:string;name:string;children:string[];references:string[];facts?:Record<string,unknown>}

function uiNodeName(node:any):string{if(node.kind==='text')return `text ${JSON.stringify(node.value)}`;if(node.kind==='button')return `button ${JSON.stringify(node.label)}`;if(node.kind==='input')return `input ${node.name}`;if(node.kind==='component')return `component ${node.componentId}`;if(node.kind==='link')return `link ${JSON.stringify(node.label)}`;if(node.kind==='feedback')return `feedback ${node.state}`;if(node.kind==='dialog')return `dialog ${JSON.stringify(node.title)}`;if(node.kind==='list')return `list ${node.source}`;if(node.kind==='conditional')return `conditional ${node.condition}`;return node.kind}
function styleFacts(style:any):Record<string,unknown>{return {token:style.token??false,values:style.values??[],typedValues:style.typedValues??[],composes:style.composes??[],padding:style.padding,gap:style.gap,margin:style.margin,width:style.width,height:style.height,opacity:style.opacity,columns:style.columns,responsiveColumns:style.responsiveColumns,responsiveGap:style.responsiveGap,responsivePadding:style.responsivePadding,responsiveMargin:style.responsiveMargin,responsiveFontSize:style.responsiveFontSize,responsiveLineHeight:style.responsiveLineHeight,responsiveLayout:style.responsiveLayout,layout:style.layout,alignment:style.alignment,typography:style.typography,fontWeight:style.fontWeight,fontSize:style.fontSize,lineHeight:style.lineHeight,theme:style.theme,color:style.color,border:style.border,shadow:style.shadow,corners:style.corners,radius:style.radius,disabled:style.disabled,focus:style.focus,surface:style.surface,text:style.text,textColor:style.textColor,transitionDuration:style.transitionDuration,transitionProperty:style.transitionProperty,transitionEasing:style.transitionEasing,properties:style.properties??[],states:style.states??[],responsive:style.responsive}}
function addUiNodes(out:GraphNode[],ownerId:string,nodes:any[]):string[]{return nodes.map((node,index)=>{const id=`${ownerId}:ui:${index}`;const children=node.kind==='list'?addUiNodes(out,id,node.body??[]):node.kind==='conditional'?[...addUiNodes(out,`${id}:then`,node.then??[]),...addUiNodes(out,`${id}:else`,node.else??[])]:[];const references=node.kind==='component'?[node.componentId]:node.kind==='link'?[node.targetComponentId]:[];const facts=node.kind==='link'?{label:node.label,targetComponentId:node.targetComponentId}:node.kind==='feedback'?{state:node.state,message:node.value}:node.kind==='dialog'?{dialogId:node.dialogId,label:node.label,title:node.title,message:node.message}:node.kind==='list'?{source:node.source,item:node.item,empty:node.empty,filterBy:node.filterBy,pageSize:node.pageSize}:undefined;out.push({id,kind:'ui-node',name:uiNodeName(node),children,references,...(facts?{facts}:{})});return id})}

/** Graph edges use compiler-provided IDs when present; display paths are never resolved here. */
export function graph(ir:ProjectIR):GraphNode[]{
  const out:GraphNode[]=[{id:ir.app.id,kind:'app',name:ir.app.name,children:[],references:[]}];
  if(ir.modules){
    for(const m of ir.modules)out.push({id:m.id,kind:'module',name:m.file,children:[],references:[]});
    for(const m of ir.modules){const node=out.find(n=>n.id===m.id)!;node.references=(m.importIds??[]).slice();}
  }
  for(const m of ir.models){out.push({id:m.id,kind:'model',name:m.name,children:m.fields.map(f=>f.id),references:[]});for(const f of m.fields){const ref=ir.models.find(x=>x.name===f.type);out.push({id:f.id,kind:'field',name:f.name,children:[],references:ref?[ref.id]:[]});if(ref)out.find(n=>n.id===m.id)!.references.push(ref.id)}}
  for(const r of ir.records){out.push({id:r.id,kind:'type',name:r.name,children:r.fields.map(f=>f.id),references:[]});for(const f of r.fields)out.push({id:f.id,kind:'field',name:f.name,children:[],references:[]})}
  for(const p of ir.pages){const refs=p.crud.map(n=>ir.models.find(m=>m.name===n)?.id).filter(Boolean) as string[],ui=ir.ui?.components.find(component=>component.id===p.id),children=ui?addUiNodes(out,p.id,ui.children):[];out.push({id:p.id,kind:'page',name:p.name,children,references:refs})}
  for(const component of ir.ui?.components??[]){if(ir.pages.some(page=>page.id===component.id))continue;const children=addUiNodes(out,component.id,component.children);out.push({id:component.id,kind:'component',name:component.name,children,references:[]})}
  for(const a of ir.apis){const ref=ir.models.find(m=>m.name===a.model)?.id;out.push({id:a.id,kind:'api',name:a.route,children:[],references:ref?[ref]:[]})}
  for(const i of ir.interfaces??[]){out.push({id:i.id,kind:'interface',name:i.name,children:(i.methodIds??[]).map(String),references:[]});for(const [index,name] of i.methods.entries())out.push({id:String(i.methodIds?.[index]??`${i.id}:${name}`),kind:'interface-method',name,children:[],references:[i.id]})}
  for(const implementation of ir.implementations??[]){const id=implementation.id??`IMPL:${implementation.interfaceId}:${implementation.type}`;out.push({id,kind:'implementation',name:implementation.type,children:(implementation.methodIds??[]).map(String),references:[implementation.interfaceId]})}
  for(const f of ir.functions)out.push({id:String(f.id),kind:'function',name:f.name,children:[],references:[]});
  if(ir.style)out.push({id:ir.style.id,kind:'style',name:ir.style.values.join(' '),children:[],references:[],facts:styleFacts(ir.style)});
  for(const style of ir.styles??[]){const references=(style.composes??[]).map(name=>ir.styles?.find(candidate=>candidate.name===name)?.id).filter(Boolean) as string[];out.push({id:style.id,kind:'style',name:`${style.name??'style'} ${style.values.join(' ')}`,children:[],references,facts:styleFacts(style)});}
  out[0].children=out.filter(n=>['module','model','type','page','api','interface','implementation','function','style'].includes(n.kind)).map(n=>n.id);
  return out;
}
