import type {UIComponent, UINode, UIProgram} from './ir.js';
import {validateInput} from './validation.js';
import {invalidFormInput} from './form.js';
import type {TypeRef} from '../types/type-ref.js';

export type UIEventHandler = (event: Event, value: unknown) => void;
function validStoredValue(value: unknown, type: TypeRef): boolean { if (type.kind === 'optional') return value === null || validStoredValue(value, type.inner); if (type.kind === 'list') return Array.isArray(value) && value.every(item => validStoredValue(item, type.element)); if (type.kind === 'primitive') { if (type.name === 'text' || type.name === 'date' || type.name === 'datetime' || type.name === 'id') return typeof value === 'string'; if (type.name === 'integer') return Number.isSafeInteger(value); if (type.name === 'number') return typeof value === 'number' && Number.isFinite(value); if (type.name === 'boolean') return typeof value === 'boolean'; if (type.name === 'money') return typeof value === 'number' && Number.isFinite(value); } if (type.kind === 'model' || type.kind === 'record') return Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype); if (type.kind === 'enum') return typeof value === 'string' && type.variants.some(variant => variant.name === value); return false; }
function moneyMinor(value: unknown): bigint | undefined { if (value && typeof value === 'object' && 'minor' in value) { try { const money = value as {minor: bigint | number | string; scale?: number}; return Number(money.scale ?? 2) === 2 ? BigInt(money.minor) : undefined; } catch { return undefined; } } if (typeof value !== 'number' || !Number.isFinite(value)) return undefined; const match = String(value).match(/^(-?)(\d+)(?:\.(\d{1,2}))?$/); if (!match) return undefined; const amount = BigInt(match[2]!) * 100n + BigInt((match[3] ?? '').padEnd(2, '0')); return match[1] ? -amount : amount; }
function moneyAggregate(rows: Record<string, unknown>[], field: string, multiplier?: string): string { let total = 0n; for (const row of rows) { const minor = moneyMinor(row?.[field]), quantity = multiplier ? row?.[multiplier] : 1; if (minor === undefined || typeof quantity !== 'number' || !Number.isSafeInteger(quantity)) continue; total += minor * BigInt(quantity); } const absolute = total < 0n ? -total : total; return `${total < 0n ? '-' : ''}${absolute / 100n}.${String(absolute % 100n).padStart(2, '0')}`; }
function readBinding(state: Record<string, unknown>, path: string): unknown { return path.split('.').reduce<unknown>((value, key) => value && typeof value === 'object' ? (value as Record<string, unknown>)[key] : undefined, state); }
function typedInputValue(type: TypeRef, value: string): unknown { if (type.kind === 'optional') return value === '' ? undefined : typedInputValue(type.inner, value); if (type.kind !== 'primitive') return value; switch (type.name) { case 'integer': return BigInt(value); case 'number': return Number(value); case 'boolean': return value === 'true' || value === '1' || value === 'on'; default: return value; } }

export function renderNode(node: UINode, components: Map<string, UIComponent>, state: Record<string, unknown>, handlers: Readonly<Record<string, UIEventHandler>> = {}, routes: UIProgram['routes'] = [], updates: ReadonlyMap<string, UIComponent['events'][number]['stateUpdate']> = new Map(), rootState: Record<string, unknown> = state, redraw: () => void = () => {}): Node {
  if (node.kind === 'text') return document.createTextNode(node.value);
  if (node.kind === 'binding') return document.createTextNode(String(readBinding(state, node.path) ?? ''));
  if (node.kind === 'aggregate') { const rows = Array.isArray(state[node.source]) ? state[node.source] as Record<string, unknown>[] : []; if (node.money) return document.createTextNode(moneyAggregate(rows, node.field, node.multiplier)); const total = rows.reduce((sum, row) => { const value = Number(row?.[node.field]), factor = node.multiplier ? Number(row?.[node.multiplier]) : 1, part = value * factor; return Number.isFinite(part) ? sum + part : sum; }, 0); return document.createTextNode(String(total)); }
  if (node.kind === 'button') { const button = document.createElement('button'); button.textContent = node.label; if (node.event && (handlers[node.event] || updates.get(node.event))) button.addEventListener('click', event => { const form = button.closest?.('form') as HTMLFormElement | null; if (form && invalidFormInput(form)) return; const value = node.arguments ? Object.fromEntries(node.arguments.map(argument => [argument.name, readBinding(state, argument.path)])) : undefined; const update = updates.get(node.event!); if (update && value && Object.prototype.hasOwnProperty.call(value, update.parameter)) { let item = value[update.parameter]; if (update.projection) item = Object.fromEntries(Object.entries(update.projection.fields).map(([key, source]) => [key, source.kind === 'literal' ? source.value : source.path.split('.').reduce((current, part) => current && typeof current === 'object' ? (current as Record<string, unknown>)[part] : undefined, item)])); if (update.type && !validStoredValue(item, update.type)) return; const current = Array.isArray(rootState[update.state]) ? [...rootState[update.state] as unknown[]] : []; if (update.operation === 'append') current.push(item); else { const same = (left: unknown, right: unknown) => left && right && typeof left === 'object' && typeof right === 'object' ? (('id' in left && 'id' in right) ? (left as {id:unknown}).id === (right as {id:unknown}).id : JSON.stringify(left) === JSON.stringify(right)) : left === right; const index = current.findIndex(candidate => same(candidate, item)); if (index >= 0 && (update.operation === 'increment' || update.operation === 'decrement')) { const row = current[index]; const previous = row && typeof row === 'object' ? (row as Record<string, unknown>)[update.field!] : undefined; if (typeof previous !== 'number' || !Number.isFinite(previous)) return; const next = previous + (update.operation === 'increment' ? 1 : -1); if (!Number.isFinite(next) || (Number.isSafeInteger(previous) && !Number.isSafeInteger(next))) return; current[index] = { ...(row as Record<string, unknown>), [update.field!]: next }; } else if (index >= 0) current.splice(index, 1); } if (update.storageKey) { try { globalThis.localStorage?.setItem(update.storageKey, JSON.stringify(current)); } catch { return; } } rootState[update.state] = current; redraw(); } if (handlers[node.event!]) handlers[node.event!](event, value); }); return button; }
  if (node.kind === 'link') { const link = document.createElement('a'); link.textContent = node.label; link.href = routes.find(route => route.componentId === node.targetComponentId)?.path ?? '#'; return link; }
  if (node.kind === 'feedback') { const feedback = document.createElement('p'); feedback.textContent = node.value; feedback.hidden = !Boolean(state[node.state]); feedback.setAttribute('role', node.state === 'loading' ? 'status' : 'alert'); feedback.setAttribute('aria-live', node.state === 'loading' ? 'polite' : 'assertive'); feedback.dataset.pipeCondition = node.state; return feedback; }
  if (node.kind === 'dialog') { const wrapper = document.createElement('div'), trigger = document.createElement('button'), dialog = document.createElement('dialog'), form = document.createElement('form'), heading = document.createElement('h2'), message = document.createElement('p'), close = document.createElement('button'); trigger.type = 'button'; trigger.textContent = node.label; trigger.setAttribute('aria-haspopup', 'dialog'); trigger.setAttribute('aria-controls', node.dialogId); heading.id = `${node.dialogId}-title`; heading.textContent = node.title; dialog.id = node.dialogId; dialog.setAttribute('aria-labelledby', heading.id); form.method = 'dialog'; message.textContent = node.message; close.type = 'submit'; close.textContent = 'Close'; form.appendChild(heading); form.appendChild(message); form.appendChild(close); dialog.appendChild(form); trigger.addEventListener('click', () => (dialog as HTMLDialogElement).showModal()); wrapper.appendChild(trigger); wrapper.appendChild(dialog); return wrapper; }
  if (node.kind === 'input') {
    const enumType = node.type.kind === 'enum' ? node.type : node.type.kind === 'optional' && node.type.inner.kind === 'enum' ? node.type.inner : undefined; const input = enumType ? document.createElement('select') : document.createElement('input'); input.name = node.name; input.setAttribute?.('aria-label', node.label ?? node.name); input.dataset.pipeType = node.type.kind === 'primitive' ? node.type.name : 'compound'; input.dataset.pipeValidation = node.validation ?? '';
    if (node.placeholder && !enumType) input.setAttribute?.('placeholder', node.placeholder);
    if (node.help) input.setAttribute?.('aria-description', node.help);
    if (!enumType) input.setAttribute?.('type', node.password ? 'password' : node.validation === 'email' ? 'email' : 'text');
    if (node.disabled) {
      input.setAttribute?.('disabled', 'true');
      input.setAttribute?.('aria-disabled', 'true');
    }
    if (node.readOnly && !enumType) {
      input.setAttribute?.('readonly', 'true');
      input.setAttribute?.('aria-readonly', 'true');
    }
    if (enumType) { if (node.type.kind === 'optional') { const option = document.createElement('option'); option.value = ''; option.textContent = 'Choose…'; input.appendChild(option); } for (const variant of enumType.variants) if (!variant.payload) { const option = document.createElement('option'); option.value = variant.name; option.textContent = variant.name; input.appendChild(option); } }
    if (node.validation) { input.setAttribute?.('aria-invalid', 'false'); if (node.validation === 'nonempty') input.setAttribute?.('aria-required', 'true'); }
    const handler = node.event ? handlers[node.event] : undefined;
    if (handler || node.validation) input.addEventListener('input', event => { const value = (event.target as HTMLInputElement).value, validation = validateInput(value, node.type, node.validation); if (validation) { input.dataset.pipeError = validation; input.setAttribute?.('aria-invalid', 'true'); return; } delete input.dataset.pipeError; if (node.validation) input.setAttribute?.('aria-invalid', 'false'); if (handler) handler(event, typedInputValue(node.type, value)); });
    return input;
  }
  if (node.kind === 'component') { const component = components.get(node.componentId); if (!component) throw new Error(`PIPE-UI-001: unknown component ${node.componentId}`); const element = document.createElement(component.form ? 'form' : 'div'); element.dataset.pipeComponent = component.id; const parent = component.form ? document.createElement('fieldset') : element; if (component.form) { const legend = document.createElement('legend'); legend.textContent = component.name; parent.appendChild(legend); element.appendChild(parent); } for (const child of component.children) parent.appendChild(renderNode(child, components, state, handlers, routes, updates, rootState, redraw)); return element; }
  if (node.kind === 'conditional') { const branch = Boolean(state[node.condition]) ? node.then : node.else ?? []; const fragment = document.createDocumentFragment(); for (const child of branch) fragment.appendChild(renderNode(child, components, state, handlers, routes, updates, rootState, redraw)); return fragment; }
  const values: unknown[] = Array.isArray(state[node.source]) ? state[node.source] as unknown[] : [];
  const controlled = node.filterBy !== undefined || node.pageSize !== undefined;
  const container = controlled ? document.createElement('div') : document.createDocumentFragment();
  const listRoot = controlled ? document.createElement('div') : container;
  let input: HTMLInputElement | undefined, pageIndex = 0;
  if (node.filterBy) { const label = document.createElement('label'); const labelText = node.filterLabel ?? 'Filter list'; label.textContent = labelText; input = document.createElement('input'); input.setAttribute('type', 'search'); input.setAttribute('aria-label', labelText); label.appendChild(input); container.appendChild(label); }
  let previous: HTMLButtonElement | undefined, next: HTMLButtonElement | undefined, range: HTMLElement | undefined;
  if (controlled) container.appendChild(listRoot);
  if (node.pageSize) { const navigation = document.createElement('nav'); navigation.setAttribute('aria-label', 'List pages'); previous = document.createElement('button'); previous.type = 'button'; previous.textContent = 'Previous'; previous.setAttribute('aria-label', 'Previous page'); next = document.createElement('button'); next.type = 'button'; next.textContent = 'Next'; next.setAttribute('aria-label', 'Next page'); range = document.createElement('span'); navigation.appendChild(previous); navigation.appendChild(range); navigation.appendChild(next); container.appendChild(navigation); }
  if (controlled) {
    const draw = (): void => {
      const query = String(input?.value ?? '').trim().toLocaleLowerCase();
      const filtered = node.remoteSearch ? values : values.filter(value => { if (!node.filterBy) return true; if (!value || typeof value !== 'object') return false; const field = (value as Record<string, unknown>)[node.filterBy]; return typeof field === 'string' && field.toLocaleLowerCase().includes(query); });
      const pageCount = node.pageSize ? Math.max(1, Math.ceil(filtered.length / node.pageSize)) : 1; pageIndex = Math.min(pageIndex, pageCount - 1);
      const start = node.pageSize ? pageIndex * node.pageSize : 0, visible = node.pageSize ? filtered.slice(start, start + node.pageSize) : filtered;
      listRoot.replaceChildren();
      for (const value of visible) { const childState = {...state, [node.item]: value}; for (const child of node.body) listRoot.appendChild(renderNode(child, components, childState, handlers, routes, updates, rootState, redraw)); }
      if (previous) previous.disabled = pageIndex === 0;
      if (next) next.disabled = pageIndex >= pageCount - 1;
      if (range && node.pageSize) range.textContent = filtered.length === 0 ? 'Showing 0 of 0' : `Showing ${start + 1}-${Math.min(start + node.pageSize, filtered.length)} of ${filtered.length}`;
      if (filtered.length === 0) { const message = values.length === 0 ? node.empty : query ? 'No matching items.' : node.empty; if (message && !state.pipePageLoading && !state.pipePageError) { const status = document.createElement('p'); status.textContent = message; status.setAttribute('role', 'status'); status.setAttribute('aria-live', 'polite'); listRoot.appendChild(status); } }
    };
    input?.addEventListener('input', () => { pageIndex = 0; draw(); }); previous?.addEventListener('click', () => { pageIndex = Math.max(0, pageIndex - 1); draw(); }); next?.addEventListener('click', () => { pageIndex++; draw(); }); draw(); return container;
  }
  const fragment = container; if (values.length > 0) for (const value of values) { const childState = {...state, [node.item]: value}; for (const child of node.body) fragment.appendChild(renderNode(child, components, childState, handlers, routes, updates, rootState, redraw)); } else if (node.empty !== undefined && !state.pipePageLoading && !state.pipePageError) { const status = document.createElement('p'); status.textContent = node.empty; status.setAttribute('role', 'status'); status.setAttribute('aria-live', 'polite'); fragment.appendChild(status); } return fragment;
}
export function render(program: UIProgram, root: HTMLElement, state: Record<string, unknown> = {}, path = '/', handlers: Readonly<Record<string, UIEventHandler>> = {}): void { const components = new Map(program.components.map(component => [component.id, component])); const route = program.routes.find(candidate => candidate.path === path) || program.routes[0]; const component = route ? components.get(route.componentId) : program.components[0]; if (!component) throw new Error('PIPE-UI-002: no root component'); for (const pageState of component.state) if (!(pageState.name in state)) { if (pageState.initial !== undefined) state[pageState.name] = pageState.initial; else if (pageState.type.kind === 'list') state[pageState.name] = []; } for (const savedState of component.state) if (savedState.persisted === 'local' && savedState.storageKey) { try { const raw = globalThis.localStorage?.getItem(savedState.storageKey); if (raw !== null && raw !== undefined) { const saved = JSON.parse(raw); if (validStoredValue(saved, savedState.type)) state[savedState.name] = saved; else globalThis.localStorage?.removeItem(savedState.storageKey); } } catch { /* Keep the caller's initial state when storage is unavailable or invalid. */ } } const updates = new Map(component.events.filter(event => event.stateUpdate).map(event => [event.name, event.stateUpdate])); const draw = () => { root.replaceChildren(); const feedbackState = { ...state, pipePageLoading: Boolean(state.loading), pipePageError: Boolean(state.error) }; for (const child of component.children) root.appendChild(renderNode(child, components, feedbackState, handlers, program.routes, updates, state, draw)); }; draw(); }
