import {capabilityType,listType,optionalType,primitive,resultType,taskType,type TypeRef} from '../types/type-ref.js';

export const STDLIB_NAMES=new Set(['textLength','trim','lower','upper','textContains','startsWith','endsWith','textReplace','textIndexOf','substring','base64Encode','base64Decode','absInt','absNumber','minInt','maxInt','clamp','power','sqrt','floor','ceil','round','first','last','length','contains','sort','reverse','slice','distinct','join','split','parseInteger','parseNumber','parseBoolean','encodeJson','decodeJson','some','ok','err','isOk','isErr','isSome','isNone','map','filter','fold','find','any','all','range','parseDate','parseDateTime','parseId','formatDate','addDays','addSeconds','dateDifference','datetimeDifference','randomId','secureRandomId','dateYear','dateMonth','dateDay','currentTime','today','randomNumber','randomInteger','secureRandomInteger','pathJoin','pathBasename','pathDirname','pathRelative','httpRequest','httpRequestJson','httpRequestMultipart','sendEmail','delay','scheduleOnce','cancel','timeout','environmentArguments','environmentText','environmentSecret','revealSecret','environmentInteger','environmentBoolean','uploadFilename','uploadMediaType','uploadSize','saveUpload','readStdin','writeStdout','writeStderr','setExitCode','readTextFile','writeTextFile','appendTextFile','fileExists','listDirectory','createDirectory','copyTextFile','moveTextFile','removeTextFile','databaseSelect','databaseSelectWhere','databaseCount','databaseCountWhere','databaseDecrementWhere','databaseInsert','databaseInsertId','databaseInsertIdIfAbsent','databaseUpdate','databaseUpdateWhere','databaseUpdateUniqueWhere','databaseDelete','databaseDeleteWhere']);
export const PUBLIC_STDLIB_NAMES=[...STDLIB_NAMES].filter(name=>!name.startsWith('database')).sort();
export type StdlibContract={name:string;arity:number;arguments:string[];returns:string;capabilities?:string[];overloads?:{arity:number;arguments:string[]}[]};
const contract=(name:string,arity:number,arguments_:string[],returns:string,capabilities?:string[]):StdlibContract=>({name,arity,arguments:arguments_,returns,...(capabilities?{capabilities}:{})});
export const PUBLIC_STDLIB_CONTRACTS:StdlibContract[]=PUBLIC_STDLIB_NAMES.map(name=>{
 switch(name){
  case 'textLength':return contract(name,1,['text'],'integer');
  case 'trim':case 'lower':case 'upper':return contract(name,1,['text'],'text');
  case 'textContains':case 'startsWith':case 'endsWith':return contract(name,2,['text','text'],'boolean');
  case 'textIndexOf':return contract(name,2,['text','text'],'integer?');
  case 'textReplace':return contract(name,3,['text','text','text'],'text');
  case 'base64Encode':return contract(name,1,['text'],'text');
  case 'base64Decode':return contract(name,1,['text'],'result<text,text>');
  case 'substring':return contract(name,3,['text','integer','integer'],'text');
  case 'absInt':return contract(name,1,['integer'],'integer');
  case 'absNumber':case 'floor':case 'ceil':case 'round':return contract(name,1,['number'],'number');
  case 'minInt':case 'maxInt':return contract(name,2,['integer','integer'],'integer');
  case 'clamp':return contract(name,3,['number','number','number'],'number');
  case 'power':return contract(name,2,['number','number'],'number');
  case 'sqrt':return contract(name,1,['number'],'number');
  case 'first':case 'last':return contract(name,1,['list<T>'],'T?');
  case 'length':return contract(name,1,['list<T>'],'integer');
  case 'contains':return contract(name,2,['list<T>','T'],'boolean');
  case 'sort':return contract(name,1,['list<T>'],'list<T>');
  case 'reverse':case 'distinct':return contract(name,1,['list<T>'],'list<T>');
  case 'slice':return contract(name,3,['list<T>','integer','integer'],'list<T>');
  case 'join':return contract(name,2,['list<text>','text'],'text');
  case 'split':return contract(name,2,['text','text'],'list<text>');
  case 'parseInteger':return contract(name,1,['text'],'result<integer,text>');
  case 'parseNumber':return contract(name,1,['text'],'result<number,text>');
  case 'parseBoolean':return contract(name,1,['text'],'result<boolean,text>');
  case 'parseDate':return contract(name,1,['text'],'result<date,text>');
  case 'parseDateTime':return contract(name,1,['text'],'result<datetime,text>');
  case 'parseId':return contract(name,1,['text'],'result<id,text>');
  case 'encodeJson':return contract(name,1,['T'],'text');
  case 'decodeJson':return contract(name,1,['text'],'result<T,text>');
  case 'formatDate':return contract(name,1,['date|datetime'],'text');
  case 'addDays':return contract(name,2,['date','integer'],'result<date,text>');
  case 'addSeconds':return contract(name,2,['datetime','integer'],'result<datetime,text>');
  case 'dateDifference':return contract(name,2,['date','date'],'integer');
  case 'datetimeDifference':return contract(name,2,['datetime','datetime'],'integer');
  case 'dateYear':case 'dateMonth':case 'dateDay':return contract(name,1,['date|datetime'],'integer');
  case 'range':return contract(name,2,['integer','integer'],'list<integer>');
  case 'isOk':case 'isErr':return contract(name,1,['result<T,E>'],'boolean');
  case 'isSome':case 'isNone':return contract(name,1,['T?'],'boolean');
  case 'some':return contract(name,1,['T'],'T?');
  case 'ok':return contract(name,1,['T'],'result<T,E>');
  case 'err':return contract(name,1,['E'],'result<T,E>');
  case 'map':return contract(name,2,['list<T>','function(T)->U'],'list<U>');
  case 'filter':return contract(name,2,['list<T>','function(T)->boolean'],'list<T>');
  case 'fold':return contract(name,3,['list<T>','U','function(U,T)->U'],'U');
  case 'find':return contract(name,2,['list<T>','function(T)->boolean'],'T?');
  case 'any':case 'all':return contract(name,2,['list<T>','function(T)->boolean'],'boolean');
  case 'randomId':return contract(name,1,['capability<random>'],'id',['random']);
  case 'secureRandomId':return contract(name,1,['capability<secureRandom>'],'id',['secureRandom']);
  case 'currentTime':return contract(name,1,['capability<time>'],'integer',['time']);
  case 'today':return contract(name,1,['capability<time>'],'date',['time']);
  case 'environmentArguments':return contract(name,1,['capability<environment>'],'list<text>',['environment']);
  case 'environmentText':return contract(name,2,['capability<environment>','text'],'text?',['environment']);
  case 'environmentSecret':return contract(name,2,['capability<environment>','text'],'secret<text>?',['environment']);
  case 'revealSecret':return contract(name,2,['secret<text>','capability<environment>'],'text',['environment']);
  case 'environmentInteger':return contract(name,2,['capability<environment>','text'],'result<integer,text>',['environment']);
  case 'environmentBoolean':return contract(name,2,['capability<environment>','text'],'result<boolean,text>',['environment']);
  case 'uploadFilename':case 'uploadMediaType':return contract(name,1,['upload'],'text');
  case 'uploadSize':return contract(name,1,['upload'],'integer');
  case 'saveUpload':return contract(name,3,['capability<filesystem>','upload','text'],'result<boolean,text>',['filesystem']);
  case 'readStdin':return contract(name,1,['capability<environment>'],'task<result<text,text>>',['environment']);
  case 'writeStdout':case 'writeStderr':return contract(name,2,['capability<environment>','text'],'result<boolean,text>',['environment']);
  case 'setExitCode':return contract(name,2,['capability<environment>','integer'],'result<boolean,text>',['environment']);
  case 'randomNumber':return contract(name,1,['capability<random>'],'number',['random']);
  case 'randomInteger':return contract(name,3,['capability<random>','integer','integer'],'integer',['random']);
  case 'secureRandomInteger':return contract(name,3,['capability<secureRandom>','integer','integer'],'integer',['secureRandom']);
  case 'httpRequest':return {...contract(name,7,['capability<http>','text','text','text?','list<text>','list<text>','integer'],'task<result<text,text>>',['http']),overloads:[{arity:5,arguments:['capability<http>','text','text','text?','integer']}]};
  case 'httpRequestJson':return {...contract(name,7,['capability<http>','text','text','T?','list<text>','list<text>','integer'],'task<result<T,text>>',['http']),overloads:[{arity:5,arguments:['capability<http>','text','text','T?','integer']}]};
  case 'httpRequestMultipart':return contract(name,7,['capability<http>','text','text','list<text>','list<text>','list<upload>','integer'],'task<result<text,text>>',['http']);
  case 'sendEmail':return contract(name,4,['capability<email>','text','text','text'],'task<result<boolean,text>>',['email']);
  case 'delay':return contract(name,2,['capability<time>','integer'],'task<result<boolean,text>>',['time']);
  case 'scheduleOnce':return contract(name,3,['capability<time>','integer','()->task<result<boolean,text>>'],'task<result<boolean,text>>',['time']);
  case 'cancel':return contract(name,2,['capability<time>','task<T>'],'result<boolean,text>',['time']);
  case 'timeout':return contract(name,3,['capability<time>','task<T>','integer'],'task<result<T,text>>',['time']);
  case 'readTextFile':return contract(name,2,['capability<filesystem>','text'],'result<text,text>',['filesystem']);
  case 'writeTextFile':return contract(name,3,['capability<filesystem>','text','text'],'result<boolean,text>',['filesystem']);
  case 'appendTextFile':return contract(name,3,['capability<filesystem>','text','text'],'result<boolean,text>',['filesystem']);
  case 'fileExists':return contract(name,2,['capability<filesystem>','text'],'result<boolean,text>',['filesystem']);
  case 'listDirectory':return contract(name,2,['capability<filesystem>','text'],'result<list<text>,text>',['filesystem']);
  case 'createDirectory':return contract(name,2,['capability<filesystem>','text'],'result<boolean,text>',['filesystem']);
  case 'copyTextFile':return contract(name,3,['capability<filesystem>','text','text'],'result<boolean,text>',['filesystem']);
  case 'moveTextFile':return contract(name,3,['capability<filesystem>','text','text'],'result<boolean,text>',['filesystem']);
  case 'removeTextFile':return contract(name,2,['capability<filesystem>','text'],'result<boolean,text>',['filesystem']);
  case 'pathJoin':return contract(name,2,['text','text'],'text');
  case 'pathBasename':case 'pathDirname':return contract(name,1,['text'],'text');
  case 'pathRelative':return contract(name,2,['text','text'],'text');
  default:throw new Error(`Missing standard-library contract for ${name}`);
 }
});
export function stdlibType(name:string,args:TypeRef[],expected?:TypeRef):TypeRef|undefined {
 const text=primitive('text'),integer=primitive('integer'),number=primitive('number'),boolean=primitive('boolean');
 if(name==='map'&&args[0]?.kind==='list'&&args[1]?.kind==='function'&&args[1].parameters.length===1)return listType(args[1].returns);
 if(name==='filter'&&args[0]?.kind==='list'&&args[1]?.kind==='function'&&args[1].parameters.length===1)return listType(args[0].element);
 if(name==='fold'&&args[0]?.kind==='list'&&args[1]&&args[2]?.kind==='function'&&args[2].parameters.length===2)return args[1];
 if(name==='find'&&args[0]?.kind==='list'&&args[1]?.kind==='function'&&args[1].parameters.length===1)return optionalType(args[0].element);
 if(name==='any'||name==='all')return boolean;
 if(name==='range')return listType(integer);
 if(name==='parseInteger')return resultType(integer,text);
 if(name==='parseNumber')return resultType(number,text);
 if(name==='encodeJson')return text;
 if(name==='decodeJson')return expected?.kind==='result'?expected:resultType(text,text);
 if(name==='currentTime')return integer;
 if(name==='today')return primitive('date');
 if(name==='pathBasename'||name==='pathDirname'||name==='pathRelative')return text;
 if(name==='randomNumber')return number;
 if(name==='randomInteger')return integer;
 if(name==='randomId')return primitive('id');
 if(name==='secureRandomId')return primitive('id');
 if(name==='secureRandomInteger')return integer;
 if(name==='environmentArguments')return listType(text);
 if(name==='environmentText')return optionalType(text);
 if(name==='environmentSecret')return optionalType({kind:'secret',inner:text});
 if(name==='revealSecret')return text;
 if(name==='environmentInteger')return resultType(integer,text);
 if(name==='environmentBoolean')return resultType(boolean,text);
 if(name==='uploadFilename'||name==='uploadMediaType')return text;
 if(name==='uploadSize')return integer;
 if(name==='saveUpload')return resultType(boolean,text);
 if(name==='readStdin')return taskType(resultType(text,text));
 if(name==='httpRequest')return taskType(resultType(text,text));
 if(name==='httpRequestJson')return expected?.kind==='result'?taskType(expected):taskType(resultType(text,text));
 if(name==='httpRequestMultipart')return taskType(resultType(text,text));
 if(name==='sendEmail')return taskType(resultType(boolean,text));
 if(name==='delay')return taskType(resultType(boolean,text));
 if(name==='scheduleOnce')return taskType(resultType(boolean,text));
 if(name==='cancel')return resultType(boolean,text);
 if(name==='timeout'&&args[1]?.kind==='task')return taskType(resultType(args[1].result,text));
 switch(name){
  case 'textLength':case 'length':return integer;
  case 'trim':case 'lower':case 'upper':case 'textReplace':case 'substring':case 'base64Encode':return text;
  case 'base64Decode':return resultType(text,text);
  case 'textIndexOf':return optionalType(integer);
  case 'textContains':case 'startsWith':case 'endsWith':case 'contains':return boolean;
  case 'absInt':case 'minInt':case 'maxInt':return integer;
  case 'absNumber':case 'clamp':case 'power':case 'sqrt':case 'floor':case 'ceil':case 'round':return number;
  case 'reverse':case 'distinct':return args[0]&&args[0].kind==='list'?listType(args[0].element):undefined;
  case 'slice':return args[0]?.kind==='list'?listType(args[0].element):undefined;
  case 'first':case 'last':return args[0]&&args[0].kind==='list'?optionalType(args[0].element):undefined;
  case 'isOk':case 'isErr':case 'isSome':case 'isNone':return boolean;
  case 'parseDate':return resultType(primitive('date'),text);
  case 'parseDateTime':return resultType(primitive('datetime'),text);
  case 'parseId':return resultType(primitive('id'),text);
  case 'formatDate':return text;
  case 'addDays':return resultType(primitive('date'),text);
  case 'addSeconds':return resultType(primitive('datetime'),text);
  case 'dateDifference':return integer;
  case 'datetimeDifference':return integer;
  case 'dateYear':case 'dateMonth':case 'dateDay':return integer;
  case 'some':return expected?.kind==='optional'?expected:args[0]?optionalType(args[0]):undefined;
  case 'ok':return expected?.kind==='result'?{kind:'result',ok:expected.ok,error:expected.error}:args[0]?{kind:'result',ok:args[0],error:text}:undefined;
  case 'err':return expected?.kind==='result'?{kind:'result',ok:expected.ok,error:expected.error}:args[0]?{kind:'result',ok:text,error:args[0]}:undefined;
  default:return undefined;
 }
}
