import type {Program,FunctionDeclaration,HttpDeclaration,ImplDeclaration,InterfaceDeclaration} from '../ast/ast.js';
import {diagnostic,type Diagnostic} from '../diagnostics/diagnostics.js';
import {formatType,isSameType,parseTypeRef,primitive,type TypeRef} from '../types/type-ref.js';
import {symbolId,type SymbolId,type FunctionId,interfaceId,interfaceMethodId,implId,type InterfaceId,type InterfaceMethodId,type ImplId} from '../identity.js';
import type {DeclarationIndex} from './declaration-index.js';
export interface InterfaceContract { id:InterfaceId; name:string; module:string; visibility:'public'|'private'; methods:InterfaceMethodContract[] }
export interface InterfaceMethodContract { id:InterfaceMethodId; name:string; parameters:TypeRef[]; receiver:TypeRef|undefined; returnType:TypeRef }
export interface ImplContract { id:ImplId; interfaceId:InterfaceId; type:TypeRef; methods:Map<string,FunctionDeclaration>; methodIds:Map<string,FunctionId> }
export interface ContractResult { diagnostics:Diagnostic[]; interfaces:InterfaceContract[]; impls:ImplContract[] }
export interface ContractOptions { functionIds?:Map<FunctionDeclaration,FunctionId>; index?:DeclarationIndex; resolveInterfaceId?: (name:string,file:string)=>InterfaceId|undefined }
const scalar=(name:string):TypeRef=>primitive(name as any);
const typeKey=(type:TypeRef):string=>{switch(type.kind){case 'primitive':return `p:${type.name}`;case 'none':return 'none';case 'optional':return `o:${typeKey(type.inner)}`;case 'list':return `l:${typeKey(type.element)}`;case 'result':return `r:${typeKey(type.ok)},${typeKey(type.error)}`;case 'task':return `t:${typeKey(type.result)}`;case 'capability':return `cap:${type.name}`;case 'secret':return `secret:${typeKey(type.inner)}`;case 'upload':return 'upload';case 'record':return `record:${type.symbol}${type.typeArguments?.length?`<${type.typeArguments.map(typeKey).join(',')}>`:''}`;case 'model':return `model:${type.symbol}`;case 'enum':return `enum:${type.symbol}${type.typeArguments?.length?`<${type.typeArguments.map(typeKey).join(',')}>`:''}`;case 'function':return `fn:${type.parameters.map(typeKey).join(',')}->${typeKey(type.returns)}`;case 'typeParameter':return `param:${type.owner}:${type.ordinal}`;}};
function resolve(source:string,types:Map<string,any>):TypeRef|undefined{return parseTypeRef(source,(name,args)=>{const d=types.get(name);if(!d)return name==='upload'?{kind:'upload'}:['text','integer','number','money','boolean','date','datetime','id'].includes(name)?scalar(name):undefined;if(d.kind==='RecordDeclaration')return {kind:'record',name,symbol:symbolId(`${d.span.start.file}::${name}`),typeArguments:args};if(d.kind==='ModelDeclaration')return {kind:'model',name,symbol:symbolId(`${d.span.start.file}::${name}`)};return undefined})}
function declarations(p:Program){return p.declarations.filter(d=>['ModelDeclaration','RecordDeclaration','EnumDeclaration','InterfaceDeclaration','ImplDeclaration','FunctionDeclaration'].includes(d.kind));}
export function analyzeContracts(p:Program,options:ContractOptions={}):ContractResult {
 const diagnostics:Diagnostic[]=[];const all=declarations(p);const types=new Map<string,any>();
 for(const d of all as any[]){if(!['ModelDeclaration','RecordDeclaration','EnumDeclaration'].includes(d.kind))continue;types.set(d.name,d)}
 const interfaces=new Map<string,InterfaceContract>();const interfaceFiles=new Map<string,string>();
 for(const d of all.filter((x):x is InterfaceDeclaration=>x.kind==='InterfaceDeclaration')){const key=`${d.span.start.file}::interface::${d.name}`;const indexed=[...options.index?.interfaces.values()??[]].find(x=>x.declaration===d);const id=indexed?.id??interfaceId(key);if(interfaces.has(key))diagnostics.push(diagnostic('PIPE-IFACE-001',`Duplicate interface "${d.name}"`,d.span,{kind:'duplicate_interface'}));const methods=d.methods.map(m=>({id:indexed?.methods.get(m.name)??interfaceMethodId(`${id}::method::${d.methods.indexOf(m)}`),name:m.name,receiver:m.parameters.find(x=>x.name==='self')?resolve(m.parameters.find(x=>x.name==='self')!.type,types):undefined,parameters:m.parameters.filter(x=>x.name!=='self').map(x=>resolve(x.type,types)??scalar('text')),returnType:resolve(m.returnType,types)??scalar('text')}));interfaces.set(key,{id,name:d.name,module:d.span.start.file,visibility:d.visibility??'private',methods})}
 for(const d of all.filter((x):x is InterfaceDeclaration=>x.kind==='InterfaceDeclaration'))interfaceFiles.set(d.name,d.span.start.file);
 const impls:ImplContract[]=[];const keys=new Set<string>();
 for(const d of all.filter((x):x is ImplDeclaration=>x.kind==='ImplDeclaration')){const indexed=[...options.index?.impls.values()??[]].find(x=>x.declaration===d);const c=indexed?.interfaceId?[...interfaces.values()].find(x=>x.id===indexed.interfaceId):undefined;const candidates=[...interfaces.values()].filter(x=>x.name===d.interfaceName);if(!c){diagnostics.push(diagnostic(candidates.length?'PIPE-IFACE-008':'PIPE-IFACE-002',candidates.length?`Interface name "${d.interfaceName}" is ambiguous`:`Unknown interface "${d.interfaceName}"`,d.span,{kind:candidates.length?'ambiguous_interface':'unknown_interface'}));continue}if(!types.has(d.typeName)){diagnostics.push(diagnostic('PIPE-TYPE-001',`Unknown implementation type "${d.typeName}"`,d.span,{kind:'unknown_type'}));continue}const type=resolve(d.typeName,types)!;const key=`${c.id}::${typeKey(type)}`;if(keys.has(key))diagnostics.push(diagnostic('PIPE-IFACE-006',`Duplicate implementation for ${d.interfaceName} and ${d.typeName}`,d.span,{kind:'duplicate_impl'}));keys.add(key);const methods=new Map(d.methods.map(m=>[m.name,m] as const));const methodIds=new Map<string,FunctionId>();for(const req of c.methods){const m=methods.get(req.name);if(!m){diagnostics.push(diagnostic('PIPE-IFACE-003',`Missing required method "${req.name}"`,d.span,{kind:'missing_interface_method'}));continue}if(options.functionIds?.get(m))methodIds.set(req.name,options.functionIds.get(m)!);const supplied=m.parameters.filter(x=>x.name!=='self').map(x=>resolve(x.type,types)??scalar('text'));if(supplied.length!==req.parameters.length)diagnostics.push(diagnostic('PIPE-IFACE-004',`Wrong parameter count for "${req.name}"`,m.span,{kind:'implementation_arity'}));else for(let i=0;i<supplied.length;i++)if(!isSameType(supplied[i]!,req.parameters[i]!))diagnostics.push(diagnostic('PIPE-IFACE-005',`Wrong parameter type for "${req.name}"`,m.span,{kind:'implementation_parameter_type'}));const returned=resolve(m.returnType,types);if(returned&&!isSameType(returned,req.returnType))diagnostics.push(diagnostic('PIPE-IFACE-005',`Wrong return type for "${req.name}"`,m.span,{kind:'implementation_return_type'}))}impls.push({id:indexed?.id??implId(`IMPL:${d.span.start.file}:${d.interfaceName}:${d.typeName}`),interfaceId:c.id,type,methods,methodIds})}
 for(const implementation of impls){const typeName=formatType(implementation.type);for(const method of implementation.methods.values()){const receiver=method.parameters.find(p=>p.name==='self');if(receiver&&receiver.type!==typeName)diagnostics.push(diagnostic('PIPE-IFACE-004',`Wrong receiver type for interface method "${method.name}"`,method.span,{kind:'implementation_receiver_type'}));}}
 for(const d of all.filter((x):x is ImplDeclaration=>x.kind==='ImplDeclaration')){const target=types.get(d.typeName);const ifaceFile=[...interfaces.values()].find(x=>x.name===d.interfaceName)?.module;if(target&&ifaceFile&&d.span.start.file!==ifaceFile&&d.span.start.file!==target.span.start.file)diagnostics.push(diagnostic('PIPE-IFACE-007','Implementation must own the interface or concrete type',d.span,{kind:'illegal_foreign_impl'}));}
 const functions=new Map<string,FunctionDeclaration>();for(const d of all.filter((x):x is FunctionDeclaration=>x.kind==='FunctionDeclaration'))functions.set(d.name,d);
 const interfaceFor=(name:string,file:string):InterfaceContract|undefined=>{const resolved=options.resolveInterfaceId?.(name,file);if(resolved){const hit=[...interfaces.values()].find(x=>x.id===resolved);if(hit)return hit;}const indexed=[...options.index?.interfaces.values()??[]].filter(x=>x.declaration.name===name&&x.declaration.span.start.file===file);if(indexed.length===1)return [...interfaces.values()].find(x=>x.id===indexed[0]!.id);const candidates=[...interfaces.values()].filter(c=>c.name===name);return candidates.length===1?candidates[0]:undefined};
 const hasImpl=(iface:InterfaceId|undefined,type:TypeRef)=>Boolean(iface&&impls.some(i=>i.interfaceId===iface&&formatType(i.type)===formatType(type)));
 const inspect=(owner:FunctionDeclaration,expression:any,env:Map<string,TypeRef>)=>{if(!expression)return;if(expression.kind==='CallExpression'){const called=functions.get(expression.callee);if(called?.constraints?.length){for(const constraint of called.constraints){const index=called.typeParameters.indexOf(constraint.parameter);const actual=expression.args[index]?typeOf(expression.args[index],env,types):undefined;if(actual&&!hasImpl(interfaceFor(constraint.interfaceName,called.span.start.file)?.id,actual))diagnostics.push(diagnostic('PIPE-GEN-006',`Type ${formatType(actual)} does not satisfy ${constraint.parameter}: ${constraint.interfaceName}`,expression.span,{kind:'unsatisfied_generic_constraint'}));}}for(const argument of expression.args)inspect(owner,argument,env)}else if(expression.kind==='FieldAccessExpression')inspect(owner,expression.object,env);else if(expression.kind==='BinaryExpression'){inspect(owner,expression.left,env);inspect(owner,expression.right,env)}};
 const typeOf=(expression:any,env:Map<string,TypeRef>,known:Map<string,any>):TypeRef|undefined=>expression.kind==='IdentifierExpression'?env.get(expression.name):expression.kind==='LiteralExpression'?scalar(expression.valueType):expression.kind==='RecordValueExpression'?resolve(expression.typeName,known):undefined;
 for(const f of functions.values()){const env=new Map<string,TypeRef>();for(const parameter of f.parameters){const t=resolve(parameter.type,types);if(t)env.set(parameter.name,t)}const visit=(statement:any)=>{if(statement.kind==='LetStatement'){inspect(f,statement.value,env);const t=statement.declaredType?resolve(statement.declaredType,types):typeOf(statement.value,env,types);if(t)env.set(statement.name,t)}else if(statement.kind==='ReturnStatement')inspect(f,statement.value,env);else if(statement.kind==='IfStatement'){inspect(f,statement.condition,env);statement.thenBody.forEach(visit);statement.elseBody?.forEach(visit)}else if(statement.kind==='ForStatement'){inspect(f,statement.iterable,env);statement.body.forEach(visit)}};f.body.forEach(visit)}
 for(const route of p.declarations.filter((item):item is HttpDeclaration=>item.kind==='HttpDeclaration')){
  const handler=functions.get(route.handler);if(!handler)continue;
  const principalParameters=handler.parameters.filter(parameter=>{const type=resolve(parameter.type,types);return type?.kind==='record'&&type.name==='Principal'});
  if(principalParameters.length>1)diagnostics.push(diagnostic('PIPE-HTTP-005','An HTTP handler may declare only one Principal parameter',route.span,{kind:'duplicate_principal_parameter'}));
  const principal=principalParameters[0];
  if(principal&&!route.policyId)diagnostics.push(diagnostic('PIPE-HTTP-005','A handler Principal parameter requires an HTTP authorization policy',route.span,{kind:'unprotected_principal'}));
  if(principal){const declaration=types.get('Principal');const idField=declaration?.fields.find((field:any)=>field.name==='id');if(!idField||resolve(idField.type,types)?.kind!=='primitive'||(resolve(idField.type,types) as Extract<TypeRef,{kind:'primitive'}>).name!=='text')diagnostics.push(diagnostic('PIPE-HTTP-005','The Principal record must declare a required text id field',declaration?.span??principal.span,{kind:'invalid_principal_id'}));}
  if(principal&&(principal.name==='body'||(route.headers??[]).includes(principal.name)||[...route.path.matchAll(/:([A-Za-z_][A-Za-z0-9_]*)/g)].some(match=>match[1]===principal.name)))diagnostics.push(diagnostic('PIPE-HTTP-005','A handler Principal parameter cannot be a path, header, or body input',principal.span,{kind:'principal_input_collision',received:principal.name}));
 }
 return {diagnostics,interfaces:[...interfaces.values()],impls};
}
