import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Pool} from 'pg';
import {compileProject} from '../dist/compiler.js';
import {buildRelease} from '../dist/release/release.js';
import {startNodeRelease} from '../dist/release/server.js';
import {postgresPoolAdapter} from '../dist/db/postgres.js';
import {AuthService} from '../dist/runtime/auth.js';
import {rolePolicy} from '../dist/http/auth-policy.js';
import {issueCapability} from '../dist/runtime/capabilities.js';
import {serializeValue} from '../dist/runtime/value-contract.js';

const connection=process.env.BMEC_POSTGRES_URL;
if(!connection) throw new Error('BMEC_POSTGRES_URL is required for the Inventory soak gate');
const compiled=compileProject(join(process.cwd(),'examples','inventory','main.pipe'));
if(compiled.diagnostics.length) throw new Error(`Inventory compile failed: ${compiled.diagnostics.map(d=>d.code).join(', ')}`);
const output=join(mkdtempSync(join(tmpdir(),'bmec-inventory-soak-')),'release');
buildRelease(compiled.ir,output,{packageName:'inventory',packageVersion:'0.1.0',languageVersion:'0.1-alpha'});
const pool=new Pool({connectionString:connection});
const db=postgresPoolAdapter(pool);
const auth=new AuthService();
await auth.register('manager','manager pass',{role:'manager'});
const manager=await auth.login('manager','manager pass');
if(!manager) throw new Error('Inventory soak manager login failed');
const managerHeaders={authorization:`Bearer ${manager.id}`};
let handle;
try{
  await pool.query('DROP TABLE IF EXISTS "StockEntry", "Product" CASCADE');
  await pool.query('CREATE TABLE "Product" ("id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"name" text NOT NULL,"price" bigint NOT NULL,"category" text,"available" boolean NOT NULL DEFAULT true)');
  await pool.query('CREATE TABLE "StockEntry" ("id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"product" bigint NOT NULL REFERENCES "Product"("id"),"quantity" bigint NOT NULL,"received" timestamptz NOT NULL,"note" text)');
  const capabilityTokens=new Map([['database',issueCapability('database')]]);
  const start=async()=>{handle=await startNodeRelease(output,{database:{adapter:db,schema:compiled.ir.db},capabilityTokens,configureRouter:router=>router.registerPolicy('role:manager',rolePolicy(auth,'manager'))});};
  const stop=async()=>{if(handle){await handle.close();handle=undefined;}};
  await start();
  const createProduct=compiled.ir.functions.find(fn=>fn.name==='createProduct');
  const bodyType=createProduct?.parameters.find(parameter=>parameter.name==='body')?.typeRef;
  if(!bodyType) throw new Error('Inventory createProduct body type is missing');
  for(let round=1;round<=3;round++){
    const body=serializeValue({kind:'model',type:bodyType,fields:{name:{kind:'text',value:`Soak ${round}`},price:{kind:'money',minor:BigInt(round)*100n,scale:2},category:{kind:'optional',inner:null},available:{kind:'boolean',value:true}}});
    const created=await fetch(`${handle.url}/products`,{method:'POST',headers:{'content-type':'application/json',...managerHeaders},body:JSON.stringify(body)});
    if(created.status!==200) throw new Error(`Inventory soak create round ${round} returned ${created.status}`);
    const rows=await (await fetch(`${handle.url}/products`,{headers:managerHeaders})).json();
    if(rows.length!==round) throw new Error(`Inventory soak expected ${round} rows, received ${rows.length}`);
  }
  await stop();
  await start();
  const persisted=await (await fetch(`${handle.url}/products`,{headers:managerHeaders})).json();
  if(persisted.length!==3||persisted[0].name!=='Soak 1'||persisted[2].name!=='Soak 3') throw new Error('Inventory soak persistence failed across release restart');
  await stop();
  console.log('INVENTORY_SOAK PASS — three PostgreSQL CRUD workflows persisted across a release-server restart');
}finally{
  if(handle) await handle.close();
  await pool.query('DROP TABLE IF EXISTS "StockEntry", "Product" CASCADE').catch(()=>{});
  await pool.end();
  rmSync(output,{recursive:true,force:true});
}
