const byId=id=>document.getElementById(id);
const node=(tag,attributes={},text='')=>{const value=document.createElement(tag);for(const [name,entry] of Object.entries(attributes)){if(name==='className')value.className=entry;else if(name==='href')value.href=entry;else value.setAttribute(name,entry);}if(text)value.textContent=text;return value;};
const link=(label,href,className)=>node('a',{href,className},label);
function renderDocs(items){const root=byId('docs-grid');for(const item of items){const card=link('',item.href,'resource-card');card.append(node('span',{className:'resource-type'},item.type),node('h3',{},item.title),node('p',{},item.description),node('span',{},'Read guide →'));root.append(card);}}
function renderExamples(items){const root=byId('examples-grid');for(const item of items){const card=node('article',{className:'example-card'}),top=node('div',{className:'example-card-top'}),copy=node('div');copy.append(node('h3',{},item.title),node('p',{},item.purpose));top.append(copy,node('span',{className:'example-tag'},item.constructs.slice(0,3).join(' · ')));const details=node('details'),summary=node('summary',{},'View source');details.append(summary);const pre=node('pre'),code=node('code',{},item.source);pre.append(code);details.append(pre);const actions=node('div',{className:'example-card-actions'});actions.append(link('Open BMEC source',item.sourcePath),link('Download source',item.download));card.append(top,details,actions);root.append(card);}}
function renderLearning(snippets){const root=byId('learn-code');for(const snippet of snippets){const label=node('div',{className:'learn-code-label'},snippet.title),pre=node('pre'),code=node('code',{},snippet.source);pre.append(code);root.append(label,pre);}}
function renderShowcase(projects){const root=byId('showcase-grid');for(const project of projects){const article=node('article',{className:'showcase-card'}),copy=node('div',{className:'showcase-copy'}),imageWrap=node('div',{className:'showcase-image'}),image=node('img',{src:project.preview.src,alt:project.preview.alt,width:project.previewWidth,height:project.previewHeight,loading:'lazy'});copy.append(node('div',{className:'showcase-card-meta'},`${project.category} · ${project.status}`),node('h3',{},project.tagline),node('p',{},project.description));const tags=node('ul',{className:'showcase-tags','aria-label':'Built with'});for(const technology of project.builtWith)tags.append(node('li',{},technology));copy.append(tags,node('p',{className:'showcase-disclosure'},project.disclosure),link('Read project notes',project.source,'text-link'));imageWrap.append(image);article.append(copy,imageWrap);root.append(article);}}
async function start(){const nav=byId('site-nav'),toggle=document.querySelector('.nav-toggle');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});nav.addEventListener('click',event=>{if(event.target.closest('a')){toggle.setAttribute('aria-expanded','false');nav.classList.remove('is-open');}});try{const response=await fetch('/site-data.json');if(!response.ok)throw new Error('site data unavailable');const data=await response.json();byId('hero-version').textContent=`Developer preview · ${data.version}`;byId('hero-status').textContent=data.releaseStatus;byId('status-label').textContent='Current documentation';byId('status-detail').textContent=data.statusDetail;byId('status-source').href=data.statusUrl;byId('install-version').textContent=data.nodeRequirement;byId('footer-version').textContent=`BMEC ${data.version} · ${data.releaseStatus}`;byId('source-repo').href=data.sourceUrl;byId('cli-download').href=data.cliDownload;byId('cli-download').setAttribute('download','');byId('vscode-download').href=data.vscodeDownload;renderDocs(data.docs);renderLearning(data.learning);renderExamples(data.examples);renderShowcase(data.showcase);}catch(error){byId('status-detail').textContent='Site data could not be loaded. Browse the project source for current documentation.';byId('status-source').href='/README.md';}}
start();
